from __future__ import annotations

from .model import E, Exercise


EXERCISES: dict[str, list[Exercise]] = {
    "intro_sets": [
        E(
            "unique_values",
            "정수 중복 제거",
            "def unique_values(values: list[int]) -> set[int]:",
            "values의 모든 정수를 set으로 변환해 반환한다.",
            "set 생성과 중복 제거",
            "unique_values([1, 1, 2]) == {1, 2}",
            "unique_values([]) == set()",
            "unique_values([-1, -1, 0]) == {-1, 0}",
            60,
        ),
        E(
            "set_unique_word_count",
            "서로 다른 단어 수",
            "def set_unique_word_count(words: list[str]) -> int:",
            "대소문자를 구분해 서로 다른 단어의 개수를 반환한다.",
            "list를 set으로 바꾸고 len 사용",
            "set_unique_word_count(['red', 'blue', 'red']) == 2",
            "set_unique_word_count([]) == 0",
            "set_unique_word_count(['A', 'a']) == 2",
        ),
        E(
            "set_has_duplicate_ids",
            "중복 ID 감지",
            "def set_has_duplicate_ids(ids: list[str]) -> bool:",
            "같은 ID가 두 번 이상 등장하면 True를 반환한다.",
            "원본 길이와 set 길이 비교",
            "set_has_duplicate_ids(['a', 'b', 'a']) is True",
            "set_has_duplicate_ids(['a', 'b']) is False",
            "set_has_duplicate_ids([]) is False",
        ),
        E(
            "set_unique_characters",
            "고유 문자 모으기",
            "def set_unique_characters(text: str) -> set[str]:",
            "공백을 포함해 text에 등장하는 서로 다른 문자를 반환한다.",
            "문자열 iterable로 set 생성",
            "set_unique_characters('banana') == {'b', 'a', 'n'}",
            "set_unique_characters('') == set()",
            "set_unique_characters('a a') == {'a', ' '}",
        ),
        E(
            "set_distinct_word_lengths",
            "단어 길이 종류",
            "def set_distinct_word_lengths(words: list[str]) -> set[int]:",
            "각 단어의 길이를 모아 서로 다른 길이의 set을 반환한다.",
            "set comprehension",
            "set_distinct_word_lengths(['a', 'to', 'tea']) == {1, 2, 3}",
            "set_distinct_word_lengths([]) == set()",
            "set_distinct_word_lengths(['ab', 'cd']) == {2}",
        ),
        E(
            "set_add_candidate",
            "후보 값 추가",
            "def set_add_candidate(values: set[int], candidate: int) -> set[int]:",
            "원본 values를 바꾸지 않고 candidate를 포함한 새 set을 반환한다.",
            "set 복사와 add",
            "((items := {1, 2}), set_add_candidate(items, 3) == {1, 2, 3} and items == {1, 2})[-1] is True",
            "set_add_candidate({1, 2}, 2) == {1, 2}",
            "set_add_candidate(set(), 0) == {0}",
        ),
        E(
            "set_parse_tags",
            "쉼표 태그를 set으로",
            "def set_parse_tags(text: str) -> set[str]:",
            "쉼표로 나눈 각 조각의 앞뒤 공백을 제거하고 빈 태그를 제외해 반환한다.",
            "split, strip, 조건부 set comprehension",
            "set_parse_tags('python, api,python') == {'python', 'api'}",
            "set_parse_tags('') == set()",
            "set_parse_tags(' a, , b ') == {'a', 'b'}",
        ),
        E(
            "set_membership_flags",
            "허용값 포함 여부",
            "def set_membership_flags(allowed: set[str], candidates: list[str]) -> list[bool]:",
            "각 candidate가 allowed에 들어 있는지를 입력 순서대로 반환한다.",
            "set membership와 리스트 순회",
            "set_membership_flags({'read', 'write'}, ['read', 'delete']) == [True, False]",
            "set_membership_flags(set(), ['x']) == [False]",
            "set_membership_flags({'x'}, []) == []",
        ),
        E(
            "set_new_values",
            "처음 보는 값만 찾기",
            "def set_new_values(seen: set[int], incoming: list[int]) -> set[int]:",
            "incoming 중 seen에 없던 값만 set으로 반환한다.",
            "set 변환과 차집합의 기초",
            "set_new_values({1, 2}, [2, 3, 3, 4]) == {3, 4}",
            "set_new_values(set(), []) == set()",
            "set_new_values({1}, [1, 1]) == set()",
        ),
        E(
            "set_cardinality_report",
            "고유값 개수 보고서",
            "def set_cardinality_report(values: list[str]) -> dict[str, object]:",
            "unique에는 고유값 set, count에는 그 개수를 담아 반환한다.",
            "set 값과 cardinality를 딕셔너리로 구성",
            "set_cardinality_report(['a', 'b', 'a']) == {'unique': {'a', 'b'}, 'count': 2}",
            "set_cardinality_report([]) == {'unique': set(), 'count': 0}",
            "set_cardinality_report(['x']) == {'unique': {'x'}, 'count': 1}",
        ),
    ],
    "set_operations": [
        E(
            "set_report",
            "세 가지 집합 연산",
            "def set_report(left: set[int], right: set[int]) -> dict[str, set[int]]:",
            "union, intersection, difference(left-right)를 가진 딕셔너리를 반환한다.",
            "합집합, 교집합, 차집합",
            "set_report({1, 2}, {2, 3}) == {'union': {1, 2, 3}, 'intersection': {2}, 'difference': {1}}",
            "set_report(set(), {1}) == {'union': {1}, 'intersection': set(), 'difference': set()}",
            "set_report({1}, {1}) == {'union': {1}, 'intersection': {1}, 'difference': set()}",
        ),
        E(
            "set_symmetric_only",
            "한쪽에만 있는 값",
            "def set_symmetric_only(left: set[str], right: set[str]) -> set[str]:",
            "두 set 중 정확히 한쪽에만 존재하는 값을 반환한다.",
            "대칭차집합",
            "set_symmetric_only({'a', 'b'}, {'b', 'c'}) == {'a', 'c'}",
            "set_symmetric_only(set(), {'x'}) == {'x'}",
            "set_symmetric_only({'x'}, {'x'}) == set()",
        ),
        E(
            "set_is_subset",
            "요청 권한 포함 검사",
            "def set_is_subset(requested: set[str], granted: set[str]) -> bool:",
            "requested의 모든 권한이 granted에 포함되면 True를 반환한다.",
            "부분집합 비교",
            "set_is_subset({'read'}, {'read', 'write'}) is True",
            "set_is_subset({'delete'}, {'read'}) is False",
            "set_is_subset(set(), {'read'}) is True",
        ),
        E(
            "set_is_superset",
            "필수 기능 충족 검사",
            "def set_is_superset(available: set[str], required: set[str]) -> bool:",
            "available이 required의 모든 기능을 가지면 True를 반환한다.",
            "상위집합 비교",
            "set_is_superset({'a', 'b'}, {'a'}) is True",
            "set_is_superset({'a'}, {'a', 'b'}) is False",
            "set_is_superset(set(), set()) is True",
        ),
        E(
            "set_are_disjoint",
            "겹치지 않는 그룹",
            "def set_are_disjoint(left: set[int], right: set[int]) -> bool:",
            "두 set에 공통 원소가 하나도 없으면 True를 반환한다.",
            "isdisjoint 또는 교집합 truthiness",
            "set_are_disjoint({1, 2}, {3, 4}) is True",
            "set_are_disjoint({1}, {1, 2}) is False",
            "set_are_disjoint(set(), {1}) is True",
        ),
        E(
            "set_jaccard_score",
            "Jaccard 유사도",
            "def set_jaccard_score(left: set[str], right: set[str]) -> float:",
            "합집합이 비면 1.0, 아니면 교집합 크기를 합집합 크기로 나눈 값을 반환한다.",
            "교집합·합집합 크기와 나눗셈",
            "set_jaccard_score({'a', 'b'}, {'b', 'c'}) == 1 / 3",
            "set_jaccard_score(set(), set()) == 1.0",
            "set_jaccard_score({'x'}, {'x'}) == 1.0",
            150,
        ),
        E(
            "set_exclusive_sides",
            "좌우 전용 원소 분리",
            "def set_exclusive_sides(left: set[int], right: set[int]) -> dict[str, set[int]]:",
            "left_only와 right_only 차집합을 딕셔너리로 반환한다.",
            "양방향 차집합",
            "set_exclusive_sides({1, 2}, {2, 3}) == {'left_only': {1}, 'right_only': {3}}",
            "set_exclusive_sides(set(), {1}) == {'left_only': set(), 'right_only': {1}}",
            "set_exclusive_sides({1}, {1}) == {'left_only': set(), 'right_only': set()}",
        ),
        E(
            "set_union_many",
            "여러 set 합치기",
            "def set_union_many(groups: list[set[int]]) -> set[int]:",
            "groups의 모든 set을 하나의 합집합으로 반환한다.",
            "반복 누적 union",
            "set_union_many([{1, 2}, {2, 3}, {4}]) == {1, 2, 3, 4}",
            "set_union_many([]) == set()",
            "set_union_many([set(), {1}]) == {1}",
        ),
        E(
            "set_common_to_all",
            "모든 그룹의 공통값",
            "def set_common_to_all(groups: list[set[str]]) -> set[str]:",
            "groups가 비면 빈 set, 아니면 모든 set에 공통인 값을 반환한다.",
            "연속 intersection과 첫 원소 초기화",
            "set_common_to_all([{'a', 'b'}, {'b', 'c'}, {'b'}]) == {'b'}",
            "set_common_to_all([]) == set()",
            "set_common_to_all([{'x', 'y'}]) == {'x', 'y'}",
        ),
        E(
            "set_relation_label",
            "집합 관계 이름",
            "def set_relation_label(left: set[int], right: set[int]) -> str:",
            "같으면 equal, left가 진부분집합이면 subset, 진상위집합이면 superset, 그 밖은 overlap_or_disjoint를 반환한다.",
            "집합 동등·진부분·진상위 관계 분기",
            "set_relation_label({1}, {1}) == 'equal'",
            "set_relation_label({1}, {1, 2}) == 'subset'",
            "set_relation_label({1, 2}, {1}) == 'superset'",
            150,
        ),
    ],
    "set_practice": [
        E(
            "dedupe_preserve_order",
            "순서 보존 중복 제거",
            "def dedupe_preserve_order(values: list[int]) -> list[int]:",
            "set으로 등장 여부를 확인하며 최초 등장 순서만 남긴다.",
            "seen set과 순서 보존 리스트",
            "dedupe_preserve_order([2, 1, 2, 3]) == [2, 1, 3]",
            "dedupe_preserve_order([]) == []",
            "dedupe_preserve_order([1, 1, 1]) == [1]",
        ),
        E(
            "set_first_duplicate",
            "첫 중복값 찾기",
            "def set_first_duplicate(values: list[str]) -> str | None:",
            "왼쪽부터 보며 두 번째로 등장하는 순간의 값을 반환하고 중복이 없으면 None을 반환한다.",
            "seen membership와 조기 반환",
            "set_first_duplicate(['a', 'b', 'a', 'b']) == 'a'",
            "set_first_duplicate(['a', 'b']) is None",
            "set_first_duplicate([]) is None",
        ),
        E(
            "set_repeated_values",
            "반복된 값 모으기",
            "def set_repeated_values(values: list[int]) -> set[int]:",
            "두 번 이상 등장한 값만 set으로 반환한다.",
            "seen set과 duplicate set 두 개 사용",
            "set_repeated_values([1, 2, 1, 3, 2]) == {1, 2}",
            "set_repeated_values([]) == set()",
            "set_repeated_values([1, 2, 3]) == set()",
        ),
        E(
            "set_missing_numbers",
            "범위에서 빠진 숫자",
            "def set_missing_numbers(values: list[int], start: int, stop: int) -> set[int]:",
            "start 이상 stop 미만 정수 중 values에 없는 숫자를 반환한다.",
            "range를 set으로 만들고 차집합",
            "set_missing_numbers([1, 3], 1, 5) == {2, 4}",
            "set_missing_numbers([], 0, 0) == set()",
            "set_missing_numbers([0, 1], 0, 2) == set()",
        ),
        E(
            "set_shared_in_order",
            "공통값을 원래 순서로",
            "def set_shared_in_order(values: list[int], allowed: set[int]) -> list[int]:",
            "values 중 allowed에 속한 값을 최초 한 번씩만 원래 순서로 반환한다.",
            "membership set과 중복 방지 set",
            "set_shared_in_order([3, 1, 3, 2], {1, 3}) == [3, 1]",
            "set_shared_in_order([], {1}) == []",
            "set_shared_in_order([1, 2], set()) == []",
        ),
        E(
            "set_partition_seen",
            "기존값과 새 값 분리",
            "def set_partition_seen(seen: set[str], incoming: list[str]) -> dict[str, list[str]]:",
            "incoming을 seen 여부에 따라 known과 new 리스트로 나누며 중복도 입력 그대로 유지한다.",
            "set membership를 이용한 두 리스트 분기",
            "set_partition_seen({'a'}, ['a', 'b', 'a']) == {'known': ['a', 'a'], 'new': ['b']}",
            "set_partition_seen(set(), []) == {'known': [], 'new': []}",
            "set_partition_seen({'x'}, ['y']) == {'known': [], 'new': ['y']}",
        ),
        E(
            "set_unique_pair_sums",
            "고유한 두 수의 합",
            "def set_unique_pair_sums(values: list[int]) -> set[int]:",
            "서로 다른 인덱스 i<j의 두 값을 더해 가능한 합을 set으로 반환한다.",
            "중첩 순회와 set 누적",
            "set_unique_pair_sums([1, 2, 3]) == {3, 4, 5}",
            "set_unique_pair_sums([1]) == set()",
            "set_unique_pair_sums([1, 1, 1]) == {2}",
            150,
        ),
        E(
            "set_exactly_once",
            "정확히 한 번 나온 값",
            "def set_exactly_once(values: list[str]) -> set[str]:",
            "values에서 정확히 한 번만 등장한 문자열을 set으로 반환한다.",
            "seen과 repeated set의 차집합",
            "set_exactly_once(['a', 'b', 'a', 'c']) == {'b', 'c'}",
            "set_exactly_once([]) == set()",
            "set_exactly_once(['x', 'x']) == set()",
        ),
        E(
            "set_distinct_by_group",
            "그룹별 고유값 개수",
            "def set_distinct_by_group(groups: dict[str, list[int]]) -> dict[str, int]:",
            "각 그룹 리스트의 고유값 개수를 같은 key로 반환한다.",
            "딕셔너리 순회와 그룹별 set 변환",
            "set_distinct_by_group({'a': [1, 1, 2], 'b': []}) == {'a': 2, 'b': 0}",
            "set_distinct_by_group({}) == {}",
            "set_distinct_by_group({'x': [3]}) == {'x': 1}",
        ),
        E(
            "set_remove_blocked_once",
            "차단값 제외 후 중복 제거",
            "def set_remove_blocked_once(values: list[str], blocked: set[str]) -> list[str]:",
            "blocked 값은 버리고 나머지는 최초 등장 한 번씩만 순서대로 반환한다.",
            "필터링과 seen set 결합",
            "set_remove_blocked_once(['a', 'x', 'a', 'b'], {'x'}) == ['a', 'b']",
            "set_remove_blocked_once([], {'x'}) == []",
            "set_remove_blocked_once(['x', 'x'], {'x'}) == []",
        ),
    ],
    "intro_dicts": [
        E(
            "make_user",
            "사용자 딕셔너리",
            "def make_user(name: str, age: int) -> dict[str, object]:",
            "name과 age key를 가진 딕셔너리를 반환한다.",
            "딕셔너리 리터럴 생성",
            "make_user('Ada', 36) == {'name': 'Ada', 'age': 36}",
            "make_user('', 0) == {'name': '', 'age': 0}",
            "make_user('Kim', 1) == {'name': 'Kim', 'age': 1}",
            60,
        ),
        E(
            "dict_make_point",
            "좌표 딕셔너리",
            "def dict_make_point(x: int, y: int) -> dict[str, int]:",
            "x와 y 좌표를 같은 이름의 key에 담아 반환한다.",
            "매개변수에서 key-value 구성",
            "dict_make_point(2, 3) == {'x': 2, 'y': 3}",
            "dict_make_point(0, 0) == {'x': 0, 'y': 0}",
            "dict_make_point(-1, 5) == {'x': -1, 'y': 5}",
        ),
        E(
            "dict_make_book",
            "책 정보 레코드",
            "def dict_make_book(title: str, pages: int, available: bool) -> dict[str, object]:",
            "title, pages, available을 가진 책 정보 딕셔너리를 반환한다.",
            "서로 다른 타입의 value 저장",
            "dict_make_book('Python', 300, True) == {'title': 'Python', 'pages': 300, 'available': True}",
            "dict_make_book('', 0, False) == {'title': '', 'pages': 0, 'available': False}",
            "dict_make_book('A', 1, True) == {'title': 'A', 'pages': 1, 'available': True}",
        ),
        E(
            "dict_from_pairs",
            "pair 목록을 딕셔너리로",
            "def dict_from_pairs(pairs: list[tuple[str, int]]) -> dict[str, int]:",
            "pairs를 순서대로 딕셔너리에 넣는다. 같은 key가 다시 나오면 마지막 value를 사용한다.",
            "반복 할당과 key 갱신",
            "dict_from_pairs([('a', 1), ('b', 2)]) == {'a': 1, 'b': 2}",
            "dict_from_pairs([]) == {}",
            "dict_from_pairs([('a', 1), ('a', 3)]) == {'a': 3}",
        ),
        E(
            "dict_contact_card",
            "선택 전화번호가 있는 연락처",
            "def dict_contact_card(name: str, phone: str | None) -> dict[str, str]:",
            "항상 name을 넣고 phone이 None이 아닐 때만 phone key를 추가한다.",
            "조건부 key 추가",
            "dict_contact_card('Ada', '010') == {'name': 'Ada', 'phone': '010'}",
            "dict_contact_card('Ada', None) == {'name': 'Ada'}",
            "dict_contact_card('', '') == {'name': '', 'phone': ''}",
        ),
        E(
            "dict_nested_profile",
            "중첩 프로필 생성",
            "def dict_nested_profile(name: str, city: str, country: str) -> dict[str, object]:",
            "name과 address 딕셔너리를 가진 중첩 프로필을 반환한다. address에는 city와 country를 넣는다.",
            "중첩 딕셔너리 구성",
            "dict_nested_profile('Ada', 'London', 'UK') == {'name': 'Ada', 'address': {'city': 'London', 'country': 'UK'}}",
            "dict_nested_profile('', '', '') == {'name': '', 'address': {'city': '', 'country': ''}}",
            "dict_nested_profile('Kim', 'Seoul', 'KR') == {'name': 'Kim', 'address': {'city': 'Seoul', 'country': 'KR'}}",
        ),
        E(
            "dict_index_items",
            "인덱스로 항목 저장",
            "def dict_index_items(items: list[str]) -> dict[int, str]:",
            "각 항목을 0부터 시작하는 인덱스 key에 연결한다.",
            "enumerate로 key-value 생성",
            "dict_index_items(['a', 'b']) == {0: 'a', 1: 'b'}",
            "dict_index_items([]) == {}",
            "dict_index_items(['x']) == {0: 'x'}",
        ),
        E(
            "dict_build_inventory",
            "상품 재고 만들기",
            "def dict_build_inventory(names: list[str], quantities: list[int]) -> dict[str, int]:",
            "같은 인덱스의 name과 quantity를 연결한다. 두 리스트의 길이는 같다고 가정한다.",
            "zip을 이용한 딕셔너리 생성",
            "dict_build_inventory(['pen', 'book'], [3, 2]) == {'pen': 3, 'book': 2}",
            "dict_build_inventory([], []) == {}",
            "dict_build_inventory(['x'], [0]) == {'x': 0}",
        ),
        E(
            "dict_default_settings",
            "기본 설정 딕셔너리",
            "def dict_default_settings(theme: str = 'light', notifications: bool = True) -> dict[str, object]:",
            "theme과 notifications를 가진 설정 딕셔너리를 반환한다.",
            "기본 인자와 딕셔너리 value",
            "dict_default_settings() == {'theme': 'light', 'notifications': True}",
            "dict_default_settings('dark') == {'theme': 'dark', 'notifications': True}",
            "dict_default_settings('dark', False) == {'theme': 'dark', 'notifications': False}",
        ),
        E(
            "dict_single_entry",
            "동적 key 한 개 만들기",
            "def dict_single_entry(key: str, value: object) -> dict[str, object]:",
            "주어진 key와 value 하나만 가진 딕셔너리를 반환한다.",
            "변수를 딕셔너리 key로 사용",
            "dict_single_entry('score', 10) == {'score': 10}",
            "dict_single_entry('', None) == {'': None}",
            "dict_single_entry('active', False) == {'active': False}",
        ),
    ],
    "dict_operations": [
        E(
            "upsert",
            "key 추가 또는 갱신",
            "def upsert(mapping: dict[str, int], key: str, value: int) -> dict[str, int]:",
            "원본을 바꾸지 않고 key를 value로 추가하거나 갱신한 새 딕셔너리를 반환한다.",
            "dict 복사와 item 할당",
            "((items := {'a': 1}), upsert(items, 'a', 2) == {'a': 2} and items == {'a': 1})[-1] is True",
            "upsert({}, 'x', 0) == {'x': 0}",
            "upsert({'a': 1}, 'b', 2) == {'a': 1, 'b': 2}",
        ),
        E(
            "dict_get_or_default",
            "기본값으로 조회",
            "def dict_get_or_default(mapping: dict[str, int], key: str, default: int) -> int:",
            "key가 있으면 해당 value, 없으면 default를 반환한다.",
            "dict.get 사용",
            "dict_get_or_default({'a': 1}, 'a', 9) == 1",
            "dict_get_or_default({'a': 1}, 'x', 9) == 9",
            "dict_get_or_default({}, '', 0) == 0",
        ),
        E(
            "dict_increment_value",
            "카운터 증가",
            "def dict_increment_value(counts: dict[str, int], key: str, amount: int = 1) -> dict[str, int]:",
            "원본을 바꾸지 않고 key의 값을 amount만큼 늘린다. 없는 key는 0에서 시작한다.",
            "get 기본값과 갱신",
            "((items := {'a': 2}), dict_increment_value(items, 'a') == {'a': 3} and items == {'a': 2})[-1] is True",
            "dict_increment_value({}, 'x', 3) == {'x': 3}",
            "dict_increment_value({'a': 2}, 'b', -1) == {'a': 2, 'b': -1}",
        ),
        E(
            "dict_rename_key",
            "key 이름 바꾸기",
            "def dict_rename_key(mapping: dict[str, int], old: str, new: str) -> dict[str, int]:",
            "원본을 바꾸지 않고 old가 존재하면 그 value를 new key로 옮긴다. old가 없으면 복사본을 그대로 반환한다.",
            "membership, pop, 재할당",
            "((items := {'a': 1}), dict_rename_key(items, 'a', 'b') == {'b': 1} and items == {'a': 1})[-1] is True",
            "dict_rename_key({'a': 1}, 'x', 'b') == {'a': 1}",
            "dict_rename_key({'a': 1, 'b': 2}, 'a', 'b') == {'b': 1}",
            150,
        ),
        E(
            "dict_merge_prefer_right",
            "오른쪽 우선 병합",
            "def dict_merge_prefer_right(left: dict[str, int], right: dict[str, int]) -> dict[str, int]:",
            "두 딕셔너리를 합치되 같은 key는 right의 value를 사용한다. 원본은 바꾸지 않는다.",
            "dict unpacking 또는 update 우선순위",
            "((left := {'a': 1}), (right := {'a': 2, 'b': 3}), dict_merge_prefer_right(left, right) == {'a': 2, 'b': 3} and left == {'a': 1} and right == {'a': 2, 'b': 3})[-1] is True",
            "dict_merge_prefer_right({}, {}) == {}",
            "dict_merge_prefer_right({'x': 1}, {}) == {'x': 1}",
        ),
        E(
            "dict_set_if_absent",
            "없는 key만 설정",
            "def dict_set_if_absent(mapping: dict[str, str], key: str, value: str) -> dict[str, str]:",
            "원본을 바꾸지 않고 key가 없을 때만 value를 추가한다.",
            "setdefault 또는 조건부 할당",
            "dict_set_if_absent({'a': 'old'}, 'a', 'new') == {'a': 'old'}",
            "((items := {}), dict_set_if_absent(items, 'a', 'new') == {'a': 'new'} and items == {})[-1] is True",
            "dict_set_if_absent({'x': ''}, 'x', 'v') == {'x': ''}",
        ),
        E(
            "dict_swap_key_values",
            "두 key의 value 교환",
            "def dict_swap_key_values(mapping: dict[str, int], first: str, second: str) -> dict[str, int]:",
            "두 key가 모두 존재하면 복사본에서 value를 교환하고, 하나라도 없으면 복사본을 그대로 반환한다.",
            "membership와 다중 할당",
            "((items := {'a': 1, 'b': 2}), dict_swap_key_values(items, 'a', 'b') == {'a': 2, 'b': 1} and items == {'a': 1, 'b': 2})[-1] is True",
            "dict_swap_key_values({'a': 1}, 'a', 'b') == {'a': 1}",
            "dict_swap_key_values({}, 'a', 'b') == {}",
        ),
        E(
            "dict_apply_updates",
            "여러 갱신 순서대로 적용",
            "def dict_apply_updates(mapping: dict[str, int], updates: list[tuple[str, int]]) -> dict[str, int]:",
            "원본을 바꾸지 않고 updates를 왼쪽부터 적용한 결과를 반환한다.",
            "반복되는 item 할당과 마지막 값 우선",
            "((items := {'a': 1}), (updates := [('b', 2), ('a', 3)]), dict_apply_updates(items, updates) == {'a': 3, 'b': 2} and items == {'a': 1} and updates == [('b', 2), ('a', 3)])[-1] is True",
            "dict_apply_updates({}, []) == {}",
            "dict_apply_updates({}, [('x', 1), ('x', 2)]) == {'x': 2}",
        ),
        E(
            "dict_adjust_inventory",
            "재고 변화 적용",
            "def dict_adjust_inventory(stock: dict[str, int], changes: dict[str, int]) -> dict[str, int]:",
            "각 changes 값을 기존 재고에 더한다. 없는 상품은 0에서 시작하며 원본은 바꾸지 않는다.",
            "두 딕셔너리 조회와 누적 갱신",
            "((items := {'pen': 3}), (changes := {'pen': -1, 'book': 2}), dict_adjust_inventory(items, changes) == {'pen': 2, 'book': 2} and items == {'pen': 3} and changes == {'pen': -1, 'book': 2})[-1] is True",
            "dict_adjust_inventory({}, {}) == {}",
            "dict_adjust_inventory({'x': 0}, {'x': 0}) == {'x': 0}",
        ),
        E(
            "dict_toggle_flag",
            "bool 설정 반전",
            "def dict_toggle_flag(settings: dict[str, bool], key: str) -> dict[str, bool]:",
            "원본을 바꾸지 않고 key의 bool 값을 반전한다. 없는 key는 False로 본 뒤 True로 추가한다.",
            "get 기본값, 논리 부정, 갱신",
            "((items := {'dark': True}), dict_toggle_flag(items, 'dark') == {'dark': False} and items == {'dark': True})[-1] is True",
            "dict_toggle_flag({}, 'dark') == {'dark': True}",
            "dict_toggle_flag({'a': False}, 'b') == {'a': False, 'b': True}",
        ),
    ],
    "dict_looping": [
        E(
            "invert_dict",
            "key와 value 뒤집기",
            "def invert_dict(mapping: dict[str, int]) -> dict[int, str]:",
            "value가 모두 고유하다고 가정하고 key와 value를 뒤집는다.",
            "items 순회와 역방향 할당",
            "invert_dict({'a': 1}) == {1: 'a'}",
            "invert_dict({}) == {}",
            "invert_dict({'a': 1, 'b': 2}) == {1: 'a', 2: 'b'}",
        ),
        E(
            "dict_even_value_keys",
            "짝수 value의 key",
            "def dict_even_value_keys(mapping: dict[str, int]) -> list[str]:",
            "value가 짝수인 key를 입력 딕셔너리 순서대로 반환한다.",
            "items 순회와 조건 필터",
            "dict_even_value_keys({'a': 1, 'b': 2, 'c': 4}) == ['b', 'c']",
            "dict_even_value_keys({}) == []",
            "dict_even_value_keys({'x': 3}) == []",
        ),
        E(
            "dict_format_entries",
            "key=value 문자열 목록",
            "def dict_format_entries(mapping: dict[str, int]) -> list[str]:",
            "각 item을 'key=value' 형식으로 바꿔 딕셔너리 순서대로 반환한다.",
            "items unpacking과 f-string",
            "dict_format_entries({'a': 1, 'b': 2}) == ['a=1', 'b=2']",
            "dict_format_entries({}) == []",
            "dict_format_entries({'x': -1}) == ['x=-1']",
        ),
        E(
            "dict_sum_for_prefix",
            "접두사 key의 값 합계",
            "def dict_sum_for_prefix(mapping: dict[str, int], prefix: str) -> int:",
            "prefix로 시작하는 key들의 value 합계를 반환한다.",
            "key 조건 검사와 value 누적",
            "dict_sum_for_prefix({'app': 2, 'api': 3, 'web': 4}, 'ap') == 5",
            "dict_sum_for_prefix({}, 'a') == 0",
            "dict_sum_for_prefix({'a': 1, 'b': 2}, '') == 3",
        ),
        E(
            "dict_square_values",
            "모든 value 제곱",
            "def dict_square_values(mapping: dict[str, int]) -> dict[str, int]:",
            "같은 key를 유지하며 각 value를 제곱한 새 딕셔너리를 반환한다.",
            "dict comprehension의 key-value 변환",
            "dict_square_values({'a': 2, 'b': -3}) == {'a': 4, 'b': 9}",
            "dict_square_values({}) == {}",
            "dict_square_values({'z': 0}) == {'z': 0}",
        ),
        E(
            "dict_filter_minimum",
            "최솟값 이상 항목",
            "def dict_filter_minimum(mapping: dict[str, int], minimum: int) -> dict[str, int]:",
            "value가 minimum 이상인 item만 남긴 새 딕셔너리를 반환한다.",
            "dict comprehension과 비교 조건",
            "dict_filter_minimum({'a': 1, 'b': 3}, 2) == {'b': 3}",
            "dict_filter_minimum({}, 0) == {}",
            "dict_filter_minimum({'a': 2}, 2) == {'a': 2}",
        ),
        E(
            "dict_longest_key",
            "가장 긴 key",
            "def dict_longest_key(mapping: dict[str, object]) -> str | None:",
            "가장 긴 key를 반환한다. 길이가 같으면 먼저 나온 key, 비어 있으면 None을 반환한다.",
            "items 순회와 최댓값 상태 유지",
            "dict_longest_key({'a': 1, 'long': 2, 'mid': 3}) == 'long'",
            "dict_longest_key({}) is None",
            "dict_longest_key({'aa': 1, 'bb': 2}) == 'aa'",
        ),
        E(
            "dict_group_keys_by_value",
            "같은 value의 key 묶기",
            "def dict_group_keys_by_value(mapping: dict[str, int]) -> dict[int, list[str]]:",
            "value별로 key 목록을 딕셔너리 입력 순서대로 묶는다.",
            "items 순회와 setdefault 리스트 누적",
            "dict_group_keys_by_value({'a': 1, 'b': 2, 'c': 1}) == {1: ['a', 'c'], 2: ['b']}",
            "dict_group_keys_by_value({}) == {}",
            "dict_group_keys_by_value({'x': 0}) == {0: ['x']}",
            150,
        ),
        E(
            "dict_enumerate_entries",
            "item에 인덱스 붙이기",
            "def dict_enumerate_entries(mapping: dict[str, int]) -> list[tuple[int, str, int]]:",
            "각 item을 (0부터의 인덱스, key, value) tuple로 반환한다.",
            "enumerate와 items 동시 unpacking",
            "dict_enumerate_entries({'a': 1, 'b': 2}) == [(0, 'a', 1), (1, 'b', 2)]",
            "dict_enumerate_entries({}) == []",
            "dict_enumerate_entries({'x': -1}) == [(0, 'x', -1)]",
        ),
        E(
            "dict_flatten_entries",
            "key와 value 번갈아 펼치기",
            "def dict_flatten_entries(mapping: dict[str, str]) -> list[str]:",
            "각 item의 key와 value를 차례로 결과 리스트에 추가한다.",
            "items 순회와 append 두 번",
            "dict_flatten_entries({'a': '1', 'b': '2'}) == ['a', '1', 'b', '2']",
            "dict_flatten_entries({}) == []",
            "dict_flatten_entries({'': 'x'}) == ['', 'x']",
        ),
    ],
    "dict_practice": [
        E(
            "frequency",
            "문자열 빈도표",
            "def frequency(values: list[str]) -> dict[str, int]:",
            "각 문자열이 등장한 횟수를 딕셔너리로 반환한다.",
            "get 기본값을 이용한 빈도 누적",
            "frequency(['a', 'b', 'a']) == {'a': 2, 'b': 1}",
            "frequency([]) == {}",
            "frequency(['x']) == {'x': 1}",
        ),
        E(
            "dict_word_lengths",
            "단어별 길이",
            "def dict_word_lengths(words: list[str]) -> dict[str, int]:",
            "각 단어를 key, 길이를 value로 저장한다. 중복 단어는 하나의 key로 남는다.",
            "문자열 리스트를 파생 value 딕셔너리로 변환",
            "dict_word_lengths(['cat', 'python']) == {'cat': 3, 'python': 6}",
            "dict_word_lengths([]) == {}",
            "dict_word_lengths(['a', 'a']) == {'a': 1}",
        ),
        E(
            "dict_index_records_by_id",
            "ID로 레코드 색인",
            "def dict_index_records_by_id(records: list[dict[str, object]]) -> dict[int, dict[str, object]]:",
            "각 record의 정수 id를 key로 사용한다. 같은 id가 다시 나오면 마지막 record를 저장한다.",
            "딕셔너리 리스트 순회와 동적 key 색인",
            "dict_index_records_by_id([{'id': 1, 'name': 'A'}, {'id': 2, 'name': 'B'}]) == {1: {'id': 1, 'name': 'A'}, 2: {'id': 2, 'name': 'B'}}",
            "dict_index_records_by_id([]) == {}",
            "dict_index_records_by_id([{'id': 1, 'name': 'A'}, {'id': 1, 'name': 'Z'}]) == {1: {'id': 1, 'name': 'Z'}}",
            150,
        ),
        E(
            "dict_group_words_by_first",
            "첫 글자로 단어 묶기",
            "def dict_group_words_by_first(words: list[str]) -> dict[str, list[str]]:",
            "비어 있지 않은 단어를 첫 글자별 리스트로 입력 순서대로 묶는다.",
            "동적 key와 리스트 누적",
            "dict_group_words_by_first(['apple', 'ant', 'banana']) == {'a': ['apple', 'ant'], 'b': ['banana']}",
            "dict_group_words_by_first([]) == {}",
            "dict_group_words_by_first(['x']) == {'x': ['x']}",
        ),
        E(
            "dict_character_frequency",
            "문자 빈도표",
            "def dict_character_frequency(text: str) -> dict[str, int]:",
            "공백을 포함해 text의 각 문자 등장 횟수를 반환한다.",
            "문자열 순회와 딕셔너리 카운팅",
            "dict_character_frequency('aba') == {'a': 2, 'b': 1}",
            "dict_character_frequency('') == {}",
            "dict_character_frequency('a a') == {'a': 2, ' ': 1}",
        ),
        E(
            "dict_most_frequent",
            "가장 자주 나온 값",
            "def dict_most_frequent(values: list[str]) -> str | None:",
            "가장 많이 등장한 값을 반환한다. 동률이면 먼저 등장한 값, 입력이 비면 None을 반환한다.",
            "빈도 딕셔너리와 안정적인 최댓값 선택",
            "dict_most_frequent(['a', 'b', 'a']) == 'a'",
            "dict_most_frequent([]) is None",
            "dict_most_frequent(['b', 'a']) == 'b'",
            150,
        ),
        E(
            "dict_merge_counts",
            "두 빈도표 합치기",
            "def dict_merge_counts(left: dict[str, int], right: dict[str, int]) -> dict[str, int]:",
            "같은 key의 count를 더해 새 딕셔너리로 반환한다.",
            "key별 누적 병합",
            "dict_merge_counts({'a': 2}, {'a': 3, 'b': 1}) == {'a': 5, 'b': 1}",
            "dict_merge_counts({}, {}) == {}",
            "dict_merge_counts({'x': 0}, {'y': 2}) == {'x': 0, 'y': 2}",
        ),
        E(
            "dict_missing_required_keys",
            "누락 필수 key",
            "def dict_missing_required_keys(mapping: dict[str, object], required: set[str]) -> set[str]:",
            "required 중 mapping에 존재하지 않는 key를 반환한다.",
            "dict key view와 set 차집합",
            "dict_missing_required_keys({'name': 'A'}, {'name', 'age'}) == {'age'}",
            "dict_missing_required_keys({}, set()) == set()",
            "dict_missing_required_keys({'x': 1}, {'x'}) == set()",
        ),
        E(
            "dict_score_histogram",
            "10점 단위 점수 구간",
            "def dict_score_histogram(scores: list[int]) -> dict[int, int]:",
            "각 점수를 10으로 내림한 구간 시작값에 묶어 개수를 센다. 예: 87은 80 구간이다.",
            "계산된 key로 빈도 누적",
            "dict_score_histogram([87, 82, 91]) == {80: 2, 90: 1}",
            "dict_score_histogram([]) == {}",
            "dict_score_histogram([0, 9, 10]) == {0: 2, 10: 1}",
        ),
        E(
            "dict_duplicate_counts",
            "중복된 항목의 횟수",
            "def dict_duplicate_counts(values: list[str]) -> dict[str, int]:",
            "두 번 이상 등장한 값과 그 전체 등장 횟수만 반환한다.",
            "전체 빈도 계산 후 딕셔너리 필터링",
            "dict_duplicate_counts(['a', 'b', 'a', 'c', 'b', 'b']) == {'a': 2, 'b': 3}",
            "dict_duplicate_counts([]) == {}",
            "dict_duplicate_counts(['x']) == {}",
        ),
    ],
    "dict_remove": [
        E(
            "remove_keys",
            "여러 key 안전하게 제거",
            "def remove_keys(mapping: dict[str, int], keys: list[str]) -> dict[str, int]:",
            "원본을 바꾸지 않고 존재하는 keys만 제거한다.",
            "dict 복사와 pop 기본값",
            "((items := {'a': 1, 'b': 2}), (keys := ['a', 'x']), remove_keys(items, keys) == {'b': 2} and items == {'a': 1, 'b': 2} and keys == ['a', 'x'])[-1] is True",
            "remove_keys({}, ['x']) == {}",
            "remove_keys({'a': 1}, []) == {'a': 1}",
        ),
        E(
            "dict_pop_with_removed",
            "제거 결과와 value 반환",
            "def dict_pop_with_removed(mapping: dict[str, int], key: str) -> tuple[dict[str, int], int | None]:",
            "원본을 바꾸지 않고 key를 제거한 딕셔너리와 제거된 value를 반환한다. key가 없으면 value는 None이다.",
            "pop과 반환값 처리",
            "((items := {'a': 1, 'b': 2}), dict_pop_with_removed(items, 'a') == ({'b': 2}, 1) and items == {'a': 1, 'b': 2})[-1] is True",
            "dict_pop_with_removed({'a': 1}, 'x') == ({'a': 1}, None)",
            "dict_pop_with_removed({}, 'x') == ({}, None)",
        ),
        E(
            "dict_keep_only_keys",
            "선택한 key만 유지",
            "def dict_keep_only_keys(mapping: dict[str, int], allowed: set[str]) -> dict[str, int]:",
            "allowed에 포함된 key의 item만 유지한다.",
            "dict comprehension과 membership",
            "dict_keep_only_keys({'a': 1, 'b': 2}, {'b'}) == {'b': 2}",
            "dict_keep_only_keys({}, {'a'}) == {}",
            "dict_keep_only_keys({'a': 1}, set()) == {}",
        ),
        E(
            "dict_remove_none_values",
            "None value 제거",
            "def dict_remove_none_values(mapping: dict[str, object | None]) -> dict[str, object]:",
            "value가 None인 item만 제거한다. 0, False, 빈 문자열은 유지한다.",
            "None identity 검사와 필터링",
            "dict_remove_none_values({'a': 1, 'b': None}) == {'a': 1}",
            "dict_remove_none_values({}) == {}",
            "dict_remove_none_values({'zero': 0, 'false': False, 'empty': ''}) == {'zero': 0, 'false': False, 'empty': ''}",
        ),
        E(
            "dict_remove_below",
            "기준 미만 value 제거",
            "def dict_remove_below(mapping: dict[str, int], minimum: int) -> dict[str, int]:",
            "value가 minimum 미만인 item을 제거한 새 딕셔너리를 반환한다.",
            "value 비교를 이용한 제거 필터",
            "dict_remove_below({'a': 1, 'b': 3}, 2) == {'b': 3}",
            "dict_remove_below({}, 0) == {}",
            "dict_remove_below({'a': 2}, 2) == {'a': 2}",
        ),
        E(
            "dict_drop_prefix_keys",
            "접두사 key 제거",
            "def dict_drop_prefix_keys(mapping: dict[str, int], prefix: str) -> dict[str, int]:",
            "prefix로 시작하는 key를 모두 제거한다.",
            "startswith 조건과 딕셔너리 필터",
            "dict_drop_prefix_keys({'tmp_a': 1, 'keep': 2}, 'tmp_') == {'keep': 2}",
            "dict_drop_prefix_keys({}, 'x') == {}",
            "dict_drop_prefix_keys({'a': 1}, '') == {}",
        ),
        E(
            "dict_remove_empty_text",
            "빈 문자열 value 제거",
            "def dict_remove_empty_text(mapping: dict[str, str]) -> dict[str, str]:",
            "정확히 빈 문자열인 value를 제거한다. 공백 문자열은 유지한다.",
            "문자열 동등 비교로 선택 제거",
            "dict_remove_empty_text({'a': '', 'b': 'x'}) == {'b': 'x'}",
            "dict_remove_empty_text({}) == {}",
            "dict_remove_empty_text({'space': ' '}) == {'space': ' '}",
        ),
        E(
            "dict_split_selected_keys",
            "선택 key와 나머지 분리",
            "def dict_split_selected_keys(mapping: dict[str, int], selected: set[str]) -> dict[str, dict[str, int]]:",
            "selected에 포함된 item은 selected 딕셔너리, 나머지는 remaining 딕셔너리에 담는다.",
            "하나의 딕셔너리를 두 딕셔너리로 분기",
            "dict_split_selected_keys({'a': 1, 'b': 2}, {'a'}) == {'selected': {'a': 1}, 'remaining': {'b': 2}}",
            "dict_split_selected_keys({}, {'a'}) == {'selected': {}, 'remaining': {}}",
            "dict_split_selected_keys({'a': 1}, set()) == {'selected': {}, 'remaining': {'a': 1}}",
            150,
        ),
        E(
            "dict_remove_duplicate_values",
            "중복 value의 뒤쪽 item 제거",
            "def dict_remove_duplicate_values(mapping: dict[str, int]) -> dict[str, int]:",
            "같은 value가 여러 번 나오면 첫 item만 남긴다.",
            "seen value set과 순서 보존",
            "dict_remove_duplicate_values({'a': 1, 'b': 2, 'c': 1}) == {'a': 1, 'b': 2}",
            "dict_remove_duplicate_values({}) == {}",
            "dict_remove_duplicate_values({'x': 0}) == {'x': 0}",
        ),
        E(
            "dict_remove_matching_value",
            "특정 value 모두 제거",
            "def dict_remove_matching_value(mapping: dict[str, str], target: str) -> dict[str, str]:",
            "value가 target과 같은 item을 모두 제거한다.",
            "value 기준 딕셔너리 필터",
            "dict_remove_matching_value({'a': 'x', 'b': 'y', 'c': 'x'}, 'x') == {'b': 'y'}",
            "dict_remove_matching_value({}, 'x') == {}",
            "dict_remove_matching_value({'a': ''}, '') == {}",
        ),
    ],
    "dict_values": [
        E(
            "sum_values",
            "모든 value 합계",
            "def sum_values(mapping: dict[str, int]) -> int:",
            "mapping의 모든 value 합계를 반환한다.",
            "values view와 sum",
            "sum_values({'a': 2, 'b': 3}) == 5",
            "sum_values({}) == 0",
            "sum_values({'x': -1, 'y': 1}) == 0",
        ),
        E(
            "dict_average_value",
            "value 평균",
            "def dict_average_value(mapping: dict[str, float]) -> float:",
            "비어 있으면 0.0, 아니면 모든 value의 평균을 반환한다.",
            "values 합계와 개수",
            "dict_average_value({'a': 2.0, 'b': 4.0}) == 3.0",
            "dict_average_value({}) == 0.0",
            "dict_average_value({'x': -1.0, 'y': 1.0}) == 0.0",
        ),
        E(
            "dict_key_of_max_value",
            "최댓값의 key",
            "def dict_key_of_max_value(mapping: dict[str, int]) -> str | None:",
            "value가 가장 큰 key를 반환한다. 동률이면 먼저 나온 key, 비어 있으면 None을 반환한다.",
            "items에서 안정적인 최댓값 선택",
            "dict_key_of_max_value({'a': 1, 'b': 3}) == 'b'",
            "dict_key_of_max_value({}) is None",
            "dict_key_of_max_value({'a': 2, 'b': 2}) == 'a'",
        ),
        E(
            "dict_values_above",
            "기준 초과 value 목록",
            "def dict_values_above(mapping: dict[str, int], threshold: int) -> list[int]:",
            "threshold보다 큰 value를 딕셔너리 순서대로 반환한다.",
            "values 순회와 비교 필터",
            "dict_values_above({'a': 1, 'b': 3, 'c': 2}, 1) == [3, 2]",
            "dict_values_above({}, 0) == []",
            "dict_values_above({'a': 1}, 1) == []",
        ),
        E(
            "dict_scale_values",
            "value 배율 적용",
            "def dict_scale_values(mapping: dict[str, float], factor: float) -> dict[str, float]:",
            "각 value에 factor를 곱한 새 딕셔너리를 반환한다.",
            "values 변환 dict comprehension",
            "dict_scale_values({'a': 2.0, 'b': -1.0}, 0.5) == {'a': 1.0, 'b': -0.5}",
            "dict_scale_values({}, 2.0) == {}",
            "dict_scale_values({'x': 3.0}, 0.0) == {'x': 0.0}",
        ),
        E(
            "dict_all_values_positive",
            "모든 value 양수 검사",
            "def dict_all_values_positive(mapping: dict[str, int]) -> bool:",
            "모든 value가 0보다 크면 True를 반환한다. 빈 딕셔너리는 True다.",
            "values와 all",
            "dict_all_values_positive({'a': 1, 'b': 2}) is True",
            "dict_all_values_positive({'a': 0}) is False",
            "dict_all_values_positive({}) is True",
        ),
        E(
            "dict_value_frequencies",
            "value 자체의 빈도",
            "def dict_value_frequencies(mapping: dict[str, int]) -> dict[int, int]:",
            "mapping의 value마다 등장 횟수를 반환한다.",
            "values 순회와 빈도 딕셔너리",
            "dict_value_frequencies({'a': 1, 'b': 2, 'c': 1}) == {1: 2, 2: 1}",
            "dict_value_frequencies({}) == {}",
            "dict_value_frequencies({'x': 0}) == {0: 1}",
        ),
        E(
            "dict_sum_selected_values",
            "선택 key의 value 합계",
            "def dict_sum_selected_values(mapping: dict[str, int], keys: list[str]) -> int:",
            "keys 중 mapping에 존재하는 key의 value만 합한다. 같은 key가 keys에 반복되면 반복해서 더한다.",
            "membership와 선택 조회 누적",
            "dict_sum_selected_values({'a': 2, 'b': 3}, ['a', 'x']) == 2",
            "dict_sum_selected_values({}, ['a']) == 0",
            "dict_sum_selected_values({'a': 2}, ['a', 'a']) == 4",
        ),
        E(
            "dict_value_range",
            "value 최솟값과 최댓값",
            "def dict_value_range(mapping: dict[str, int]) -> tuple[int, int] | None:",
            "비어 있으면 None, 아니면 (최솟값, 최댓값)을 반환한다.",
            "values에 min과 max 적용",
            "dict_value_range({'a': 3, 'b': 1}) == (1, 3)",
            "dict_value_range({}) is None",
            "dict_value_range({'x': -2}) == (-2, -2)",
        ),
        E(
            "dict_clamp_values",
            "value 범위 제한",
            "def dict_clamp_values(mapping: dict[str, int], low: int, high: int) -> dict[str, int]:",
            "각 value를 low 이상 high 이하로 제한한 새 딕셔너리를 반환한다. low<=high라고 가정한다.",
            "min과 max를 조합한 value 변환",
            "dict_clamp_values({'a': -1, 'b': 5, 'c': 20}, 0, 10) == {'a': 0, 'b': 5, 'c': 10}",
            "dict_clamp_values({}, 0, 1) == {}",
            "dict_clamp_values({'x': 3}, 3, 3) == {'x': 3}",
        ),
    ],
    "reading_input": [
        E(
            "normalize_line",
            "입력 한 줄 정리",
            "def normalize_line(line: str) -> str:",
            "line 앞뒤의 모든 공백 문자를 제거해 반환한다.",
            "str.strip으로 입력 경계 정리",
            "normalize_line('  hello  ') == 'hello'",
            "normalize_line('') == ''",
            "normalize_line('  a b ') == 'a b'",
        ),
        E(
            "line_split_words",
            "공백 단어 나누기",
            "def line_split_words(line: str) -> list[str]:",
            "연속 공백을 하나의 구분으로 보아 단어 목록을 반환한다.",
            "인자 없는 split의 공백 처리",
            "line_split_words('one  two three') == ['one', 'two', 'three']",
            "line_split_words('   ') == []",
            "line_split_words('single') == ['single']",
        ),
        E(
            "line_clean_nonempty",
            "빈 줄 제외하고 정리",
            "def line_clean_nonempty(lines: list[str]) -> list[str]:",
            "각 줄을 strip한 뒤 빈 문자열이 아닌 줄만 순서대로 반환한다.",
            "여러 입력 줄의 정규화와 필터링",
            "line_clean_nonempty([' a ', '   ', 'b']) == ['a', 'b']",
            "line_clean_nonempty([]) == []",
            "line_clean_nonempty([' x ']) == ['x']",
        ),
        E(
            "line_strip_line_ending",
            "줄바꿈 문자만 제거",
            "def line_strip_line_ending(line: str) -> str:",
            "문자열 끝의 연속된 CR과 LF만 제거하고 다른 공백은 유지한다.",
            "rstrip에 제거할 문자 집합 지정",
            "line_strip_line_ending('hello' + chr(10)) == 'hello'",
            "line_strip_line_ending('x ' + chr(13) + chr(10)) == 'x '",
            "line_strip_line_ending('plain') == 'plain'",
        ),
        E(
            "line_parse_command",
            "명령어와 인자 분리",
            "def line_parse_command(line: str) -> tuple[str, list[str]]:",
            "strip 후 공백으로 나눠 첫 단어를 command, 나머지를 args로 반환한다. 내용이 없으면 ('', [])를 반환한다.",
            "입력 token 목록의 head와 tail 분리",
            "line_parse_command('add 10 20') == ('add', ['10', '20'])",
            "line_parse_command('   ') == ('', [])",
            "line_parse_command('quit') == ('quit', [])",
        ),
        E(
            "line_join_clean",
            "정리한 줄 다시 합치기",
            "def line_join_clean(lines: list[str]) -> str:",
            "각 줄을 strip하고 빈 줄은 버린 뒤 LF 한 글자로 연결한다.",
            "strip, 필터링, join",
            "line_join_clean([' a ', '', ' b']) == 'a' + chr(10) + 'b'",
            "line_join_clean([]) == ''",
            "line_join_clean([' x ']) == 'x'",
        ),
        E(
            "line_first_token",
            "첫 입력 token",
            "def line_first_token(line: str) -> str | None:",
            "공백으로 나눈 첫 token을 반환하고 token이 없으면 None을 반환한다.",
            "split 결과의 빈 목록 처리",
            "line_first_token('  alpha beta') == 'alpha'",
            "line_first_token('   ') is None",
            "line_first_token('x') == 'x'",
        ),
        E(
            "line_last_nonempty",
            "마지막 유효 입력 줄",
            "def line_last_nonempty(lines: list[str]) -> str | None:",
            "뒤에서부터 찾아 strip 결과가 비지 않은 첫 줄을 반환하고 없으면 None을 반환한다.",
            "역순 탐색과 조기 반환",
            "line_last_nonempty(['a', ' ', ' b ']) == 'b'",
            "line_last_nonempty([]) is None",
            "line_last_nonempty([' ', '']) is None",
        ),
        E(
            "line_count_nonempty",
            "유효 입력 줄 개수",
            "def line_count_nonempty(lines: list[str]) -> int:",
            "strip 결과가 비지 않은 줄의 개수를 반환한다.",
            "문자열 truthiness와 count 누적",
            "line_count_nonempty(['a', ' ', 'b']) == 2",
            "line_count_nonempty([]) == 0",
            "line_count_nonempty(['', '   ']) == 0",
        ),
        E(
            "line_normalize_spaces",
            "단어 사이 공백 하나로",
            "def line_normalize_spaces(line: str) -> str:",
            "앞뒤 공백을 없애고 단어 사이의 연속 공백 문자를 공백 한 칸으로 바꾼다.",
            "split과 단일 공백 join 조합",
            "line_normalize_spaces('  a   b  ') == 'a b'",
            "line_normalize_spaces('') == ''",
            "line_normalize_spaces('single') == 'single'",
        ),
    ],
    "input_type_conversion": [
        E(
            "parse_int",
            "정수 입력 변환",
            "def parse_int(text: str) -> int:",
            "앞뒤 공백이 있을 수 있는 text를 int로 변환한다.",
            "int 생성자의 문자열 변환",
            "parse_int(' 12 ') == 12",
            "parse_int('-1') == -1",
            "parse_int('0') == 0",
            60,
        ),
        E(
            "input_parse_float",
            "실수 입력 변환",
            "def input_parse_float(text: str) -> float:",
            "text를 float로 변환한다.",
            "float 생성자와 부호·소수점",
            "input_parse_float('3.5') == 3.5",
            "input_parse_float(' 0 ') == 0.0",
            "input_parse_float('-2') == -2.0",
        ),
        E(
            "input_parse_bool",
            "bool 문자열 해석",
            "def input_parse_bool(text: str) -> bool | None:",
            "strip 후 대소문자를 무시해 true면 True, false면 False, 그 밖은 None을 반환한다.",
            "문자열 정규화와 다중 조건 반환",
            "input_parse_bool(' TRUE ') is True",
            "input_parse_bool('false') is False",
            "input_parse_bool('yes') is None",
        ),
        E(
            "input_parse_optional_int",
            "선택 정수 입력",
            "def input_parse_optional_int(text: str) -> int | None:",
            "strip 결과가 비면 None, 아니면 int 변환 결과를 반환한다. 비어 있지 않은 입력은 유효한 정수라고 가정한다.",
            "빈 입력 분기와 int 변환",
            "input_parse_optional_int('42') == 42",
            "input_parse_optional_int('   ') is None",
            "input_parse_optional_int('-3') == -3",
        ),
        E(
            "input_parse_two_ints",
            "두 정수 token",
            "def input_parse_two_ints(line: str) -> tuple[int, int]:",
            "공백으로 구분된 정확히 두 token을 int로 변환해 tuple로 반환한다.",
            "다중 할당과 두 번의 타입 변환",
            "input_parse_two_ints('10 20') == (10, 20)",
            "input_parse_two_ints(' -1   0 ') == (-1, 0)",
            "input_parse_two_ints('3 3') == (3, 3)",
        ),
        E(
            "input_parse_number_fields",
            "정수와 실수 필드",
            "def input_parse_number_fields(line: str) -> tuple[int, float]:",
            "쉼표로 구분된 첫 필드는 int, 두 번째 필드는 float로 변환한다.",
            "서로 다른 생성자를 이용한 필드별 변환",
            "input_parse_number_fields('21,98.5') == (21, 98.5)",
            "input_parse_number_fields('0,0') == (0, 0.0)",
            "input_parse_number_fields(' -1 , 2.5 ') == (-1, 2.5)",
        ),
        E(
            "input_parse_percent",
            "퍼센트 문자열을 비율로",
            "def input_parse_percent(text: str) -> float:",
            "strip 후 마지막의 % 한 글자를 제거하고 숫자를 100으로 나눈다.",
            "문자열 suffix 제거와 float 계산",
            "input_parse_percent('25%') == 0.25",
            "input_parse_percent(' 100% ') == 1.0",
            "input_parse_percent('0%') == 0.0",
        ),
        E(
            "input_parse_binary",
            "2진 문자열 변환",
            "def input_parse_binary(text: str) -> int:",
            "text를 2진수 표현으로 해석해 int를 반환한다.",
            "int의 base 인자",
            "input_parse_binary('1010') == 10",
            "input_parse_binary('0') == 0",
            "input_parse_binary(' 111 ') == 7",
        ),
        E(
            "input_int_or_default",
            "잘못된 정수의 기본값",
            "def input_int_or_default(text: str, default: int) -> int:",
            "int 변환에 실패하면 default를 반환한다.",
            "ValueError 처리와 타입 변환",
            "input_int_or_default('10', 0) == 10",
            "input_int_or_default('x', 7) == 7",
            "input_int_or_default('', -1) == -1",
        ),
        E(
            "input_parse_person_score",
            "이름·나이·점수 변환",
            "def input_parse_person_score(line: str) -> tuple[str, int, float]:",
            "쉼표로 구분된 name, age, score를 각각 str, int, float로 변환한다. 각 필드의 공백을 제거한다.",
            "세 필드 분리와 필드별 타입 캐스팅",
            "input_parse_person_score('Ada,36,98.5') == ('Ada', 36, 98.5)",
            "input_parse_person_score(' Kim , 0 , 0 ') == ('Kim', 0, 0.0)",
            "input_parse_person_score('A,-1,2.5') == ('A', -1, 2.5)",
            150,
        ),
    ],
    "parse_input": [
        E(
            "parse_int_list",
            "공백 정수 목록",
            "def parse_int_list(line: str) -> list[int]:",
            "공백으로 구분된 모든 token을 int로 변환한다.",
            "split 결과를 list comprehension으로 변환",
            "parse_int_list('1 2 3') == [1, 2, 3]",
            "parse_int_list('') == []",
            "parse_int_list('-1 0 1') == [-1, 0, 1]",
        ),
        E(
            "input_parse_csv_ints",
            "CSV 정수 목록",
            "def input_parse_csv_ints(line: str) -> list[int]:",
            "쉼표로 나눈 조각을 strip해 int로 바꾼다. strip한 전체 line이 비면 빈 리스트를 반환한다.",
            "빈 입력 처리와 구분자 기반 파싱",
            "input_parse_csv_ints('1, 2,-3') == [1, 2, -3]",
            "input_parse_csv_ints('   ') == []",
            "input_parse_csv_ints('0') == [0]",
        ),
        E(
            "input_parse_key_value",
            "첫 등호 기준 key-value",
            "def input_parse_key_value(line: str) -> tuple[str, str]:",
            "첫 번째 '='만 구분자로 사용하고 양쪽 공백을 제거해 (key, value)를 반환한다.",
            "split 최대 횟수와 tuple 구성",
            "input_parse_key_value('name = Ada') == ('name', 'Ada')",
            "input_parse_key_value('x=a=b') == ('x', 'a=b')",
            "input_parse_key_value(' = ') == ('', '')",
        ),
        E(
            "input_parse_matrix",
            "여러 줄 정수 행렬",
            "def input_parse_matrix(lines: list[str]) -> list[list[int]]:",
            "각 줄의 공백 구분 정수를 하나의 행으로 변환한다. 빈 줄은 빈 행이 된다.",
            "중첩 list comprehension과 행 단위 파싱",
            "input_parse_matrix(['1 2', '3 4']) == [[1, 2], [3, 4]]",
            "input_parse_matrix([]) == []",
            "input_parse_matrix(['']) == [[]]",
        ),
        E(
            "input_parse_range",
            "콜론 범위 표현",
            "def input_parse_range(text: str) -> list[int]:",
            "'start:stop:step' 세 정수를 파싱해 list(range(start, stop, step))을 반환한다.",
            "문자열 필드 unpacking과 range",
            "input_parse_range('1:6:2') == [1, 3, 5]",
            "input_parse_range('0:0:1') == []",
            "input_parse_range('5:0:-2') == [5, 3, 1]",
        ),
        E(
            "input_parse_coordinates",
            "좌표 문자열",
            "def input_parse_coordinates(text: str) -> tuple[float, float]:",
            "쉼표로 구분된 x와 y를 float로 변환한다.",
            "두 실수 필드 파싱",
            "input_parse_coordinates('1.5,2') == (1.5, 2.0)",
            "input_parse_coordinates(' 0 , 0 ') == (0.0, 0.0)",
            "input_parse_coordinates('-1,-2.5') == (-1.0, -2.5)",
        ),
        E(
            "input_parse_semicolon_records",
            "세미콜론 key:value 레코드",
            "def input_parse_semicolon_records(text: str) -> dict[str, int]:",
            "'key:value' 항목들을 세미콜론으로 나눠 int value 딕셔너리로 반환한다. 빈 text는 빈 딕셔너리다.",
            "두 단계 구분자 파싱과 dict 구축",
            "input_parse_semicolon_records('a:1;b:2') == {'a': 1, 'b': 2}",
            "input_parse_semicolon_records('') == {}",
            "input_parse_semicolon_records('x:-1') == {'x': -1}",
        ),
        E(
            "input_parse_counted_values",
            "개수가 앞에 있는 입력",
            "def input_parse_counted_values(line: str) -> list[int]:",
            "첫 정수 n 뒤에 정확히 n개의 정수가 온다고 가정하고 뒤의 n개 정수만 반환한다.",
            "첫 token과 나머지 token 분리",
            "input_parse_counted_values('3 10 20 30') == [10, 20, 30]",
            "input_parse_counted_values('0') == []",
            "input_parse_counted_values('1 -5') == [-5]",
        ),
        E(
            "input_parse_name_scores",
            "이름별 점수 입력",
            "def input_parse_name_scores(text: str) -> dict[str, int]:",
            "쉼표로 구분된 'name=score' 항목을 딕셔너리로 반환한다. 빈 text는 빈 딕셔너리다.",
            "반복되는 복합 필드 파싱",
            "input_parse_name_scores('Ada=90,Kim=80') == {'Ada': 90, 'Kim': 80}",
            "input_parse_name_scores('') == {}",
            "input_parse_name_scores('A=-1') == {'A': -1}",
        ),
        E(
            "input_parse_query",
            "간단한 query 문자열",
            "def input_parse_query(text: str) -> dict[str, str]:",
            "&로 항목을 나누고 각 항목의 첫 '='로 key와 value를 분리한다. 빈 text는 빈 딕셔너리다.",
            "중첩 구분자와 split 최대 횟수",
            "input_parse_query('a=1&b=two') == {'a': '1', 'b': 'two'}",
            "input_parse_query('') == {}",
            "input_parse_query('q=a=b') == {'q': 'a=b'}",
        ),
    ],
    "input_practice": [
        E(
            "parse_record",
            "이름·나이·활성 상태",
            "def parse_record(line: str) -> tuple[str, int, bool]:",
            "'name age active'를 파싱한다. active는 대소문자를 무시해 true일 때만 True다.",
            "여러 타입의 입력 레코드 변환",
            "parse_record('Ada 36 true') == ('Ada', 36, True)",
            "parse_record('Kim 0 false') == ('Kim', 0, False)",
            "parse_record('A -1 TRUE') == ('A', -1, True)",
        ),
        E(
            "input_parse_product",
            "상품·수량·가격 레코드",
            "def input_parse_product(line: str) -> dict[str, object]:",
            "공백 구분 item, quantity, price를 각각 str, int, float로 변환해 딕셔너리로 반환한다.",
            "구조화된 한 줄을 typed record로 변환",
            "input_parse_product('pen 2 1.5') == {'item': 'pen', 'quantity': 2, 'price': 1.5}",
            "input_parse_product('x 0 0') == {'item': 'x', 'quantity': 0, 'price': 0.0}",
            "input_parse_product('book 1 10.25') == {'item': 'book', 'quantity': 1, 'price': 10.25}",
        ),
        E(
            "input_parse_log",
            "로그 레벨과 메시지",
            "def input_parse_log(line: str) -> tuple[str, str]:",
            "첫 '|'를 기준으로 level과 message를 나누고 양쪽 공백을 제거한다.",
            "최대 한 번 split하는 로그 파싱",
            "input_parse_log('INFO | started') == ('INFO', 'started')",
            "input_parse_log('ERROR|a|b') == ('ERROR', 'a|b')",
            "input_parse_log(' | ') == ('', '')",
        ),
        E(
            "input_parse_inventory_lines",
            "여러 재고 줄 합산",
            "def input_parse_inventory_lines(lines: list[str]) -> dict[str, int]:",
            "각 'item quantity' 줄을 파싱해 item별 quantity를 합산한다.",
            "여러 줄 파싱과 딕셔너리 누적",
            "input_parse_inventory_lines(['pen 2', 'book 1', 'pen 3']) == {'pen': 5, 'book': 1}",
            "input_parse_inventory_lines([]) == {}",
            "input_parse_inventory_lines(['x -1']) == {'x': -1}",
            150,
        ),
        E(
            "input_parse_flags",
            "bool token 목록",
            "def input_parse_flags(line: str) -> list[bool]:",
            "공백 token 각각을 대소문자 무시 true 여부로 bool 변환한다.",
            "token별 문자열 정규화와 bool 생성",
            "input_parse_flags('true false TRUE') == [True, False, True]",
            "input_parse_flags('') == []",
            "input_parse_flags('yes 1') == [False, False]",
        ),
        E(
            "input_parse_student_rows",
            "학생별 마지막 점수",
            "def input_parse_student_rows(lines: list[str]) -> dict[str, int]:",
            "각 'name score' 줄을 파싱한다. 같은 name이 다시 나오면 마지막 score를 저장한다.",
            "여러 레코드 파싱과 key 갱신",
            "input_parse_student_rows(['Ada 90', 'Kim 80']) == {'Ada': 90, 'Kim': 80}",
            "input_parse_student_rows([]) == {}",
            "input_parse_student_rows(['A 1', 'A 2']) == {'A': 2}",
        ),
        E(
            "input_parse_person_csv",
            "CSV 사람 레코드",
            "def input_parse_person_csv(line: str) -> tuple[str, int, str]:",
            "쉼표 구분 name, age, city의 공백을 제거하고 age만 int로 변환한다.",
            "필드 정리와 선택적 타입 변환",
            "input_parse_person_csv('Ada,36,London') == ('Ada', 36, 'London')",
            "input_parse_person_csv(' Kim , 0 , Seoul ') == ('Kim', 0, 'Seoul')",
            "input_parse_person_csv('A,-1,') == ('A', -1, '')",
        ),
        E(
            "input_sum_score_lines",
            "점수 줄 합계",
            "def input_sum_score_lines(lines: list[str]) -> int:",
            "각 'name score' 줄에서 score만 int로 변환해 모두 합한다.",
            "필요한 필드만 unpacking하고 누적",
            "input_sum_score_lines(['Ada 10', 'Kim 20']) == 30",
            "input_sum_score_lines([]) == 0",
            "input_sum_score_lines(['A -1', 'B 1']) == 0",
        ),
        E(
            "input_split_header_body",
            "첫 줄과 나머지 줄",
            "def input_split_header_body(lines: list[str]) -> tuple[str | None, list[str]]:",
            "각 줄을 strip한다. 입력이 비면 (None, []), 아니면 첫 줄과 나머지 줄을 반환한다.",
            "빈 리스트 분기와 sequence head-tail 분리",
            "input_split_header_body([' TITLE ', ' a ', ' b ']) == ('TITLE', ['a', 'b'])",
            "input_split_header_body([]) == (None, [])",
            "input_split_header_body([' only ']) == ('only', [])",
        ),
        E(
            "input_parse_operations",
            "연산명과 피연산자 목록",
            "def input_parse_operations(lines: list[str]) -> list[tuple[str, int]]:",
            "각 줄의 operation과 정수 operand를 tuple로 변환한다.",
            "여러 명령 줄의 반복 파싱",
            "input_parse_operations(['add 3', 'sub 1']) == [('add', 3), ('sub', 1)]",
            "input_parse_operations([]) == []",
            "input_parse_operations(['move -2']) == [('move', -2)]",
        ),
    ],
    "try_except": [
        E(
            "to_int_or_default",
            "정수 변환 실패 기본값",
            "def to_int_or_default(text: str, default: int = 0) -> int:",
            "int 변환 중 ValueError가 발생하면 default를 반환한다.",
            "try-except ValueError의 기본 구조",
            "to_int_or_default('x', 7) == 7",
            "to_int_or_default('10') == 10",
            "to_int_or_default('-1', 0) == -1",
        ),
        E(
            "exc_float_or_none",
            "실수 변환 실패 None",
            "def exc_float_or_none(text: str) -> float | None:",
            "float 변환에 성공하면 값, ValueError면 None을 반환한다.",
            "성공 경로와 예외 경로 반환 분리",
            "exc_float_or_none('3.5') == 3.5",
            "exc_float_or_none('bad') is None",
            "exc_float_or_none(' 0 ') == 0.0",
        ),
        E(
            "exc_divide_text_or_none",
            "문자열 정수 나눗셈",
            "def exc_divide_text_or_none(left: str, right: str) -> float | None:",
            "두 문자열을 int로 바꿔 나눈다. ValueError 또는 ZeroDivisionError가 나면 None을 반환한다.",
            "하나의 try에서 여러 실패 가능성 처리",
            "exc_divide_text_or_none('6', '2') == 3.0",
            "exc_divide_text_or_none('x', '2') is None",
            "exc_divide_text_or_none('1', '0') is None",
        ),
        E(
            "exc_bool_or_default",
            "엄격한 bool 변환",
            "def exc_bool_or_default(text: str, default: bool) -> bool:",
            "대소문자를 무시해 true/false만 허용한다. 그 밖의 값은 ValueError를 발생시킨 뒤 except에서 default를 반환한다.",
            "직접 raise한 ValueError 처리",
            "exc_bool_or_default('TRUE', False) is True",
            "exc_bool_or_default('false', True) is False",
            "exc_bool_or_default('yes', True) is True",
        ),
        E(
            "exc_lookup_or_default",
            "누락 key 기본값",
            "def exc_lookup_or_default(mapping: dict[str, int], key: str, default: int) -> int:",
            "대괄호로 key를 조회하고 KeyError가 발생하면 default를 반환한다.",
            "KeyError 포착",
            "exc_lookup_or_default({'a': 1}, 'a', 9) == 1",
            "exc_lookup_or_default({'a': 1}, 'x', 9) == 9",
            "exc_lookup_or_default({}, '', 0) == 0",
        ),
        E(
            "exc_index_or_default",
            "범위 밖 인덱스 기본값",
            "def exc_index_or_default(values: list[object], index: int, default: object) -> object:",
            "values[index]를 반환하고 IndexError가 발생하면 default를 반환한다. Python의 음수 인덱스는 그대로 허용한다.",
            "IndexError와 유효한 음수 인덱스 구분",
            "exc_index_or_default(['a'], 0, 'x') == 'a'",
            "exc_index_or_default(['a'], 2, 'x') == 'x'",
            "exc_index_or_default(['a', 'b'], -1, 'x') == 'b'",
        ),
        E(
            "exc_convert_all_or_empty",
            "전체 정수 변환 또는 빈 목록",
            "def exc_convert_all_or_empty(texts: list[str]) -> list[int]:",
            "모든 문자열을 int로 변환한다. 하나라도 ValueError가 나면 부분 결과를 버리고 빈 리스트를 반환한다.",
            "list comprehension 전체를 감싸는 try-except",
            "exc_convert_all_or_empty(['1', '2']) == [1, 2]",
            "exc_convert_all_or_empty(['1', 'x', '2']) == []",
            "exc_convert_all_or_empty([]) == []",
        ),
        E(
            "exc_reciprocal_or_default",
            "역수 계산 기본값",
            "def exc_reciprocal_or_default(text: str, default: float) -> float:",
            "text를 float로 바꿔 역수를 계산한다. 변환 실패 또는 0 나눗셈이면 default를 반환한다.",
            "ValueError와 ZeroDivisionError 동시 처리",
            "exc_reciprocal_or_default('4', -1.0) == 0.25",
            "exc_reciprocal_or_default('0', -1.0) == -1.0",
            "exc_reciprocal_or_default('x', 2.0) == 2.0",
        ),
        E(
            "exc_positive_int_or_none",
            "양의 정수만 허용",
            "def exc_positive_int_or_none(text: str) -> int | None:",
            "int 변환 후 값이 0 이하이면 직접 ValueError를 발생시킨다. ValueError는 잡아서 None을 반환한다.",
            "검증 실패를 예외로 통합",
            "exc_positive_int_or_none('5') == 5",
            "exc_positive_int_or_none('0') is None",
            "exc_positive_int_or_none('bad') is None",
        ),
        E(
            "exc_sum_valid_ints",
            "변환 가능한 정수만 합산",
            "def exc_sum_valid_ints(texts: list[str]) -> int:",
            "각 문자열을 int로 변환해 더하고 ValueError가 난 항목만 건너뛴다.",
            "반복문 내부의 좁은 try-except",
            "exc_sum_valid_ints(['1', 'x', '2']) == 3",
            "exc_sum_valid_ints([]) == 0",
            "exc_sum_valid_ints(['bad']) == 0",
        ),
    ],
    "error_catching": [
        E(
            "safe_index",
            "안전한 리스트 인덱스",
            "def safe_index(values: list[object], index: int) -> object | None:",
            "values[index]를 반환하고 IndexError면 None을 반환한다.",
            "IndexError를 최소 범위에서 처리",
            "safe_index([1], 2) is None",
            "safe_index([1], 0) == 1",
            "safe_index([], 0) is None",
        ),
        E(
            "exc_key_or_none",
            "안전한 딕셔너리 대괄호 조회",
            "def exc_key_or_none(mapping: dict[str, object], key: str) -> object | None:",
            "mapping[key]를 반환하고 KeyError면 None을 반환한다.",
            "KeyError가 발생하는 표현식 식별",
            "exc_key_or_none({'a': 1}, 'a') == 1",
            "exc_key_or_none({'a': 1}, 'x') is None",
            "exc_key_or_none({}, '') is None",
        ),
        E(
            "exc_nested_index_or_none",
            "중첩 리스트 안전 조회",
            "def exc_nested_index_or_none(matrix: list[list[int]], row: int, column: int) -> int | None:",
            "matrix[row][column]을 반환하고 어느 단계에서든 IndexError가 나면 None을 반환한다.",
            "한 표현식의 여러 IndexError 지점 처리",
            "exc_nested_index_or_none([[1, 2], [3]], 0, 1) == 2",
            "exc_nested_index_or_none([[1]], 2, 0) is None",
            "exc_nested_index_or_none([[1]], 0, 2) is None",
        ),
        E(
            "exc_character_or_empty",
            "문자열 안전 인덱스",
            "def exc_character_or_empty(text: str, index: int) -> str:",
            "text[index]를 반환하고 IndexError면 빈 문자열을 반환한다.",
            "문자열에서도 발생하는 IndexError 처리",
            "exc_character_or_empty('abc', 1) == 'b'",
            "exc_character_or_empty('', 0) == ''",
            "exc_character_or_empty('abc', -1) == 'c'",
        ),
        E(
            "exc_pop_last_copy",
            "빈 리스트 안전 pop",
            "def exc_pop_last_copy(values: list[int]) -> tuple[list[int], int | None]:",
            "원본을 복사한 뒤 pop한 결과 리스트와 제거값을 반환한다. 비어 있어 IndexError면 ([], None)을 반환한다.",
            "복사본 mutation과 IndexError 처리",
            "((items := [1, 2]), exc_pop_last_copy(items) == ([1], 2) and items == [1, 2])[-1] is True",
            "exc_pop_last_copy([]) == ([], None)",
            "exc_pop_last_copy([-1]) == ([], -1)",
        ),
        E(
            "exc_min_or_none",
            "빈 sequence 안전 최솟값",
            "def exc_min_or_none(values: list[int]) -> int | None:",
            "min(values)를 반환하고 빈 리스트로 ValueError가 발생하면 None을 반환한다.",
            "내장 함수가 발생시키는 ValueError 처리",
            "exc_min_or_none([3, 1, 2]) == 1",
            "exc_min_or_none([]) is None",
            "exc_min_or_none([-1]) == -1",
        ),
        E(
            "exc_unpack_pair_or_none",
            "정확히 두 token unpack",
            "def exc_unpack_pair_or_none(line: str) -> tuple[str, str] | None:",
            "split 결과를 정확히 두 변수에 unpack한다. 개수가 달라 ValueError가 나면 None을 반환한다.",
            "sequence unpacking의 ValueError 처리",
            "exc_unpack_pair_or_none('a b') == ('a', 'b')",
            "exc_unpack_pair_or_none('a') is None",
            "exc_unpack_pair_or_none('a b c') is None",
        ),
        E(
            "exc_fixed_float_or_none",
            "실수 변환 후 소수점 형식화",
            "def exc_fixed_float_or_none(text: str, digits: int) -> str | None:",
            "text를 float로 변환해 소수점 digits자리 문자열로 반환한다. ValueError면 None이다.",
            "변환 예외 처리 후 동적 format specifier",
            "exc_fixed_float_or_none('3.1415', 2) == '3.14'",
            "exc_fixed_float_or_none('bad', 2) is None",
            "exc_fixed_float_or_none('2', 0) == '2'",
        ),
        E(
            "exc_int_at_or_none",
            "문자열 목록의 특정 정수",
            "def exc_int_at_or_none(texts: list[str], index: int) -> int | None:",
            "texts[index]를 int로 변환한다. IndexError 또는 ValueError면 None을 반환한다.",
            "조회와 변환의 두 오류 경계",
            "exc_int_at_or_none(['10', '20'], 1) == 20",
            "exc_int_at_or_none(['x'], 0) is None",
            "exc_int_at_or_none([], 0) is None",
        ),
        E(
            "exc_matrix_cell_or_default",
            "행렬 셀 기본값 조회",
            "def exc_matrix_cell_or_default(matrix: list[list[object]], row: int, column: int, default: object) -> object:",
            "matrix[row][column]을 반환하고 IndexError면 default를 반환한다.",
            "중첩 컨테이너 조회 오류 복구",
            "exc_matrix_cell_or_default([[1, 2]], 0, 1, 9) == 2",
            "exc_matrix_cell_or_default([], 0, 0, 9) == 9",
            "exc_matrix_cell_or_default([[1]], 0, 2, None) is None",
        ),
    ],
    "multiple_except": [
        E(
            "parse_ratio",
            "두 예외를 나눈 비율 파싱",
            "def parse_ratio(left: str, right: str) -> float | None:",
            "int 변환의 ValueError와 나눗셈의 ZeroDivisionError를 별도 except 블록으로 처리하고 둘 다 None을 반환한다.",
            "여러 except 블록의 기본 형태",
            "parse_ratio('6', '2') == 3.0",
            "parse_ratio('x', '2') is None",
            "parse_ratio('1', '0') is None",
        ),
        E(
            "exc_ratio_status",
            "비율 계산 상태 구분",
            "def exc_ratio_status(left: str, right: str) -> str:",
            "정상이면 'ok:<결과>', ValueError면 'invalid_number', ZeroDivisionError면 'division_by_zero'를 반환한다.",
            "예외 타입별 서로 다른 복구 결과",
            "exc_ratio_status('6', '2') == 'ok:3.0'",
            "exc_ratio_status('x', '2') == 'invalid_number'",
            "exc_ratio_status('1', '0') == 'division_by_zero'",
        ),
        E(
            "exc_divide_list_item_status",
            "목록 값 나눗셈 상태",
            "def exc_divide_list_item_status(values: list[int], index: int, divisor: int) -> tuple[str, float | None]:",
            "성공하면 ('ok', 결과), IndexError면 ('bad_index', None), ZeroDivisionError면 ('zero_divisor', None)를 반환한다.",
            "IndexError와 ZeroDivisionError 구별",
            "exc_divide_list_item_status([10], 0, 2) == ('ok', 5.0)",
            "exc_divide_list_item_status([], 0, 2) == ('bad_index', None)",
            "exc_divide_list_item_status([10], 0, 0) == ('zero_divisor', None)",
        ),
        E(
            "exc_percentage_status",
            "백분율 파싱 상태",
            "def exc_percentage_status(part: str, whole: str) -> tuple[str, float | None]:",
            "float 변환 후 part/whole*100을 계산한다. ValueError와 ZeroDivisionError를 각각 invalid, zero_whole 상태로 구분한다.",
            "실수 변환과 0 나눗셈의 예외 분기",
            "exc_percentage_status('1', '4') == ('ok', 25.0)",
            "exc_percentage_status('x', '4') == ('invalid', None)",
            "exc_percentage_status('1', '0') == ('zero_whole', None)",
        ),
        E(
            "exc_lookup_int_status",
            "딕셔너리 문자열 숫자 조회",
            "def exc_lookup_int_status(mapping: dict[str, str], key: str) -> tuple[str, int | None]:",
            "mapping[key]를 int로 바꾼다. KeyError면 missing, ValueError면 invalid, 성공하면 ok 상태를 반환한다.",
            "KeyError와 ValueError의 발생 순서 이해",
            "exc_lookup_int_status({'a': '10'}, 'a') == ('ok', 10)",
            "exc_lookup_int_status({}, 'a') == ('missing', None)",
            "exc_lookup_int_status({'a': 'x'}, 'a') == ('invalid', None)",
        ),
        E(
            "exc_slice_with_step_status",
            "slice step 오류 구분",
            "def exc_slice_with_step_status(values: list[int], step_text: str) -> tuple[str, list[int]]:",
            "먼저 step_text를 int로 변환한다. 이 변환의 ValueError는 invalid_step이다. 변환 후 values[::step]을 실행하며 step이 0이라 발생한 ValueError는 zero_step으로 구분한다.",
            "변환 단계와 슬라이싱 단계를 별도 try-except로 나눠 같은 ValueError의 원인을 구분",
            "exc_slice_with_step_status([1, 2, 3], '2') == ('ok', [1, 3])",
            "exc_slice_with_step_status([1, 2], 'x') == ('invalid_step', [])",
            "exc_slice_with_step_status([1, 2], ' 00 ') == ('zero_step', [])",
            150,
        ),
        E(
            "exc_convert_and_index_status",
            "변환과 인덱스 오류 구분",
            "def exc_convert_and_index_status(texts: list[str], index: int) -> tuple[str, int | None]:",
            "texts[index]를 int로 변환한다. IndexError면 bad_index, ValueError면 bad_value 상태를 반환한다.",
            "조회 후 변환 순서와 다중 except",
            "exc_convert_and_index_status(['10'], 0) == ('ok', 10)",
            "exc_convert_and_index_status([], 0) == ('bad_index', None)",
            "exc_convert_and_index_status(['x'], 0) == ('bad_value', None)",
        ),
        E(
            "exc_divide_mapping_status",
            "딕셔너리 값 나눗셈",
            "def exc_divide_mapping_status(mapping: dict[str, int], key: str, divisor: int) -> tuple[str, float | None]:",
            "mapping[key]/divisor를 계산한다. KeyError와 ZeroDivisionError를 missing과 zero로 구분한다.",
            "컨테이너 조회와 산술 예외 분리",
            "exc_divide_mapping_status({'a': 8}, 'a', 2) == ('ok', 4.0)",
            "exc_divide_mapping_status({}, 'a', 2) == ('missing', None)",
            "exc_divide_mapping_status({'a': 8}, 'a', 0) == ('zero', None)",
        ),
        E(
            "exc_parse_division_message",
            "나눗셈 결과 메시지",
            "def exc_parse_division_message(numerator: str, denominator: str) -> str:",
            "두 문자열을 float로 바꿔 나눈 결과를 str로 반환한다. ValueError면 'not-a-number', ZeroDivisionError면 'cannot-divide-by-zero'다.",
            "성공값 문자열화와 타입별 오류 메시지",
            "exc_parse_division_message('5', '2') == '2.5'",
            "exc_parse_division_message('x', '2') == 'not-a-number'",
            "exc_parse_division_message('1', '0') == 'cannot-divide-by-zero'",
        ),
        E(
            "exc_sum_valid_ratios",
            "유효한 비율만 합산",
            "def exc_sum_valid_ratios(pairs: list[tuple[str, str]]) -> float:",
            "각 pair를 float로 변환해 나눈다. ValueError나 ZeroDivisionError가 난 pair만 건너뛰고 나머지 결과를 합한다.",
            "반복문 내부 다중 except와 continue",
            "exc_sum_valid_ratios([('6', '2'), ('1', '0'), ('x', '2')]) == 3.0",
            "exc_sum_valid_ratios([]) == 0.0",
            "exc_sum_valid_ratios([('1', '2'), ('3', '2')]) == 2.0",
            150,
        ),
    ],
}
