from __future__ import annotations

from .model import E, Exercise


EXERCISES: dict[str, list[Exercise]] = {
    "string_length": [
        E(
            "measure_text_length",
            "문자열 길이 재기",
            "def string_length(text: str) -> int:",
            "text에 들어 있는 문자의 개수를 반환한다.",
            "len으로 빈 문자열과 유니코드 문자열의 길이를 일관되게 구한다.",
            "string_length('python') == 6",
            "string_length('') == 0",
            "string_length('한글!') == 3",
        ),
        E(
            "compare_text_length",
            "더 긴 문자열 고르기",
            "def longer_text(left: str, right: str) -> str:",
            "두 문자열 중 길이가 더 긴 것을 반환하고, 길이가 같으면 left를 반환한다.",
            "각 문자열의 길이를 비교하고 동률 규칙을 적용한다.",
            "longer_text('cat', 'python') == 'python'",
            "longer_text('same', 'size') == 'same'",
            "longer_text('', 'a') == 'a'",
        ),
        E(
            "check_exact_text_length",
            "정확한 길이 확인하기",
            "def has_exact_length(text: str, expected: int) -> bool:",
            "text의 길이가 expected와 정확히 같을 때만 True를 반환한다.",
            "len의 결과를 정수 조건과 비교한다.",
            "has_exact_length('code', 4) is True",
            "has_exact_length('code', 3) is False",
            "has_exact_length('', 0) is True",
        ),
        E(
            "calculate_length_gap",
            "문자열 길이 차이 구하기",
            "def text_length_gap(left: str, right: str) -> int:",
            "두 문자열 길이의 절댓값 차이를 반환한다.",
            "len 결과끼리 뺀 뒤 abs로 방향과 무관한 차이를 만든다.",
            "text_length_gap('hello', 'hi') == 3",
            "text_length_gap('a', 'four') == 3",
            "text_length_gap('', '') == 0",
        ),
        E(
            "sum_piece_lengths",
            "조각 문자열 전체 길이",
            "def total_text_length(parts: list[str]) -> int:",
            "parts에 든 모든 문자열 길이의 합을 반환한다.",
            "여러 len 결과를 누적하고 빈 리스트에서는 0을 반환한다.",
            "total_text_length(['ab', 'cde']) == 5",
            "total_text_length(['', 'x', '']) == 1",
            "total_text_length([]) == 0",
        ),
        E(
            "filter_words_by_length",
            "지정 길이 단어만 고르기",
            "def words_of_length(words: list[str], size: int) -> list[str]:",
            "words에서 길이가 size인 문자열만 원래 순서대로 반환한다.",
            "각 원소에 len을 적용해 리스트 필터 조건으로 사용한다.",
            "words_of_length(['a', 'to', 'sun'], 2) == ['to']",
            "words_of_length(['', 'x', ''], 0) == ['', '']",
            "words_of_length([], 3) == []",
        ),
        E(
            "find_first_long_word",
            "처음 나오는 긴 단어",
            "def first_word_at_least(words: list[str], minimum: int) -> str | None:",
            "길이가 minimum 이상인 첫 문자열을 반환하고 없으면 None을 반환한다.",
            "순서대로 길이를 검사하며 첫 일치에서 반환한다.",
            "first_word_at_least(['a', 'tree', 'forest'], 4) == 'tree'",
            "first_word_at_least(['hi', 'ok'], 3) is None",
            "first_word_at_least([''], 0) == ''",
        ),
        E(
            "calculate_average_word_length",
            "평균 단어 길이",
            "def average_text_length(words: list[str]) -> float:",
            "문자열 길이의 평균을 반환하고 words가 비어 있으면 0.0을 반환한다.",
            "전체 문자 수와 원소 수를 각각 구해 평균을 계산한다.",
            "average_text_length(['a', 'abc']) == 2.0",
            "average_text_length(['', 'ab']) == 1.0",
            "average_text_length([]) == 0.0",
        ),
        E(
            "classify_text_length",
            "길이 등급 붙이기",
            "def text_size_label(text: str, short_max: int, long_min: int) -> str:",
            "short_max < long_min이라고 가정한다. 길이가 short_max 이하면 'short', 그렇지 않고 long_min 이상이면 'long', 그 사이는 'medium'을 반환한다.",
            "서로 겹치지 않는 두 경계의 포함 여부와 분기 우선순위를 구분한다.",
            "text_size_label('cat', 3, 7) == 'short'",
            "text_size_label('hello', 3, 7) == 'medium'",
            "text_size_label('elephant', 3, 7) == 'long'",
        ),
        E(
            "pad_text_to_minimum_length",
            "최소 길이까지 채우기",
            "def pad_to_width(text: str, width: int, fill: str) -> str:",
            "text가 width보다 짧으면 한 글자인 fill을 오른쪽에 반복해 붙이고, 이미 충분히 길면 그대로 반환한다.",
            "현재 길이와 목표 길이의 차이만큼 문자열을 반복한다.",
            "pad_to_width('cat', 5, '.') == 'cat..'",
            "pad_to_width('python', 3, '-') == 'python'",
            "pad_to_width('', 3, '0') == '000'",
        ),
    ],
    "string_indexing": [
        E(
            "read_first_and_last",
            "첫 글자와 마지막 글자",
            "def first_last(text: str) -> tuple[str, str]:",
            "비어 있지 않은 text의 첫 글자와 마지막 글자를 tuple로 반환한다.",
            "0번 인덱스와 -1번 인덱스로 양쪽 끝에 접근한다.",
            "first_last('code') == ('c', 'e')",
            "first_last('A') == ('A', 'A')",
            "first_last('한글') == ('한', '글')",
        ),
        E(
            "read_character_with_fallback",
            "안전하게 글자 읽기",
            "def character_or(text: str, index: int, default: str) -> str:",
            "index가 text의 유효한 양수 또는 음수 인덱스면 해당 글자를, 아니면 default를 반환한다.",
            "문자열 인덱스의 양수·음수 유효 범위를 직접 판단한다.",
            "character_or('python', 2, '?') == 't'",
            "character_or('python', -1, '?') == 'n'",
            "character_or('python', 8, '?') == '?'",
        ),
        E(
            "read_second_character",
            "두 번째 글자 읽기",
            "def second_character(text: str) -> str | None:",
            "text에 글자가 두 개 이상이면 두 번째 글자를, 아니면 None을 반환한다.",
            "길이를 먼저 확인한 뒤 고정 인덱스 1에 접근한다.",
            "second_character('cat') == 'a'",
            "second_character('x') is None",
            "second_character('') is None",
        ),
        E(
            "combine_edge_characters",
            "양 끝 글자 합치기",
            "def edge_characters(text: str) -> str:",
            "빈 문자열이면 '', 한 글자면 그 글자, 그 외에는 첫 글자와 마지막 글자를 이어 반환한다.",
            "길이에 따른 분기 후 양 끝 인덱스를 조합한다.",
            "edge_characters('planet') == 'pt'",
            "edge_characters('Z') == 'Z'",
            "edge_characters('') == ''",
        ),
        E(
            "read_middle_character",
            "가운데 글자 찾기",
            "def middle_character(text: str) -> str | None:",
            "길이가 홀수인 문자열은 가운데 글자를 반환하고, 빈 문자열이나 짝수 길이는 None을 반환한다.",
            "len과 정수 나눗셈으로 가운데 인덱스를 계산한다.",
            "middle_character('abcde') == 'c'",
            "middle_character('abcd') is None",
            "middle_character('') is None",
        ),
        E(
            "select_indexed_characters",
            "여러 위치의 글자 고르기",
            "def characters_at(text: str, indices: list[int]) -> str:",
            "모든 indices가 text의 유효한 인덱스라고 가정하고 해당 글자들을 순서대로 이어 반환한다.",
            "인덱스 리스트를 순회하며 문자열에서 선택한다.",
            "characters_at('python', [0, 2, 5]) == 'ptn'",
            "characters_at('abc', [-1, 0]) == 'ca'",
            "characters_at('hello', []) == ''",
        ),
        E(
            "swap_text_edges",
            "양 끝 글자 자리 바꾸기",
            "def swap_edge_characters(text: str) -> str:",
            "길이가 2 이상이면 첫 글자와 마지막 글자의 자리를 바꾼 새 문자열을 만들고, 더 짧으면 그대로 반환한다.",
            "인덱싱으로 양 끝을 읽고 가운데 부분과 재조합한다.",
            "swap_edge_characters('abcd') == 'dbca'",
            "swap_edge_characters('a') == 'a'",
            "swap_edge_characters('') == ''",
        ),
        E(
            "compare_text_edges",
            "같은 양 끝인지 비교하기",
            "def same_edge_characters(left: str, right: str) -> bool:",
            "두 문자열이 모두 비어 있지 않고 첫 글자끼리와 마지막 글자끼리가 모두 같을 때 True를 반환한다.",
            "각 문자열의 0번과 -1번 인덱스를 안전하게 비교한다.",
            "same_edge_characters('start', 'street') is True",
            "same_edge_characters('cat', 'car') is False",
            "same_edge_characters('', '') is False",
        ),
        E(
            "read_character_neighbors",
            "이웃 글자 확인하기",
            "def character_neighbors(text: str, index: int) -> tuple[str | None, str | None]:",
            "유효한 0 이상 인덱스 index의 바로 왼쪽과 오른쪽 글자를 반환하며 경계 밖 이웃은 None으로 표시한다.",
            "현재 인덱스 양옆의 경계를 각각 검사한다.",
            "character_neighbors('abcd', 1) == ('a', 'c')",
            "character_neighbors('abcd', 0) == (None, 'b')",
            "character_neighbors('abcd', 3) == ('c', None)",
        ),
        E(
            "read_nth_from_end",
            "뒤에서 n번째 글자",
            "def nth_character_from_end(text: str, n: int) -> str | None:",
            "n이 1 이상이고 text 길이 이하이면 뒤에서 n번째 글자를, 아니면 None을 반환한다.",
            "1부터 시작하는 위치를 음수 인덱스로 변환한다.",
            "nth_character_from_end('python', 1) == 'n'",
            "nth_character_from_end('python', 3) == 'h'",
            "nth_character_from_end('python', 0) is None",
        ),
    ],
    "string_looping": [
        E(
            "collect_character_codes",
            "문자 코드 모으기",
            "def char_codes(text: str) -> list[int]:",
            "text를 왼쪽부터 순회하며 각 문자의 ord 값을 리스트로 반환한다.",
            "문자열 for 순회와 ord 호출을 연습한다.",
            "char_codes('AB') == [65, 66]",
            "char_codes('a!') == [97, 33]",
            "char_codes('') == []",
        ),
        E(
            "sum_character_codes",
            "문자 코드 합계",
            "def codepoint_total(text: str) -> int:",
            "text의 모든 문자 ord 값을 순회해 합산한다.",
            "문자 단위 반복과 정수 누적 변수를 사용한다.",
            "codepoint_total('AB') == 131",
            "codepoint_total('a') == 97",
            "codepoint_total('') == 0",
        ),
        E(
            "pair_characters_with_positions",
            "글자와 위치 짝짓기",
            "def indexed_characters(text: str) -> list[tuple[int, str]]:",
            "각 문자를 0부터 시작하는 인덱스와 묶어 순서대로 반환한다.",
            "enumerate 또는 인덱스 누적으로 문자열 순회 위치를 기록한다.",
            "indexed_characters('cat') == [(0, 'c'), (1, 'a'), (2, 't')]",
            "indexed_characters('Z') == [(0, 'Z')]",
            "indexed_characters('') == []",
        ),
        E(
            "locate_uppercase_characters",
            "대문자 위치 찾기",
            "def uppercase_positions(text: str) -> list[int]:",
            "text를 순회해 대문자인 문자의 인덱스만 반환한다.",
            "인덱스가 있는 반복과 str.isupper 조건을 함께 사용한다.",
            "uppercase_positions('PyTHon') == [0, 2, 3]",
            "uppercase_positions('abc') == []",
            "uppercase_positions('A1B!') == [0, 2]",
        ),
        E(
            "repeat_each_character",
            "글자마다 반복하기",
            "def repeat_characters(text: str, count: int) -> str:",
            "count는 0 이상이라고 가정한다. 각 문자를 count번 연속으로 붙인 문자열을 반환하며 count가 0이면 빈 문자열을 반환한다.",
            "문자열을 순회하면서 문자별 반복 결과를 누적한다.",
            "repeat_characters('abc', 2) == 'aabbcc'",
            "repeat_characters('Hi', 1) == 'Hi'",
            "repeat_characters('abc', 0) == ''",
        ),
        E(
            "track_running_code_totals",
            "문자 코드 누적 합",
            "def running_codepoint_totals(text: str) -> list[int]:",
            "각 문자를 처리한 직후까지의 ord 누적 합을 리스트로 반환한다.",
            "반복할 때마다 누적 상태를 갱신하고 결과에 추가한다.",
            "running_codepoint_totals('ABC') == [65, 131, 198]",
            "running_codepoint_totals('a!') == [97, 130]",
            "running_codepoint_totals('') == []",
        ),
        E(
            "build_character_list_by_loop",
            "반복문으로 글자 리스트 만들기",
            "def collect_characters(text: str) -> list[str]:",
            "list(text)를 사용하지 말고 문자열을 순회해 한 글자씩 리스트에 담는다.",
            "for 반복과 append로 문자열을 리스트로 변환한다.",
            "collect_characters('dog') == ['d', 'o', 'g']",
            "collect_characters(' ') == [' ']",
            "collect_characters('') == []",
        ),
        E(
            "build_adjacent_character_pairs",
            "이웃한 글자 쌍 만들기",
            "def adjacent_character_pairs(text: str) -> list[str]:",
            "서로 이웃한 두 글자를 이어 붙인 문자열들을 순서대로 반환한다.",
            "인덱스 반복 범위를 마지막 이전 위치까지만 설정한다.",
            "adjacent_character_pairs('abcd') == ['ab', 'bc', 'cd']",
            "adjacent_character_pairs('a') == []",
            "adjacent_character_pairs('') == []",
        ),
        E(
            "find_first_adjacent_repeat",
            "처음 연속으로 반복된 글자",
            "def first_adjacent_repeat(text: str) -> str | None:",
            "같은 글자가 연속으로 나온 첫 위치의 글자를 반환하고 없으면 None을 반환한다.",
            "이전 글자와 현재 글자를 반복 중 비교하고 첫 일치에서 멈춘다.",
            "first_adjacent_repeat('bookkeeper') == 'o'",
            "first_adjacent_repeat('abc') is None",
            "first_adjacent_repeat('aa') == 'a'",
        ),
        E(
            "count_codes_above_limit",
            "기준보다 큰 문자 코드 세기",
            "def count_codepoints_above(text: str, limit: int) -> int:",
            "ord 값이 limit보다 큰 문자의 개수를 반환한다.",
            "문자열 순회 중 조건을 만족할 때만 카운터를 증가시킨다.",
            "count_codepoints_above('ABC', 65) == 2",
            "count_codepoints_above('az', 122) == 0",
            "count_codepoints_above('', 0) == 0",
        ),
    ],
    "string_looping_shorthand": [
        E(
            "count_vowels_shorthand",
            "모음 개수 세기",
            "def count_vowels(text: str) -> int:",
            "대소문자를 구분하지 않고 a, e, i, o, u의 개수를 반환한다.",
            "문자열 직접 순회와 membership 조건을 짧은 표현으로 결합한다.",
            "count_vowels('Apple') == 2",
            "count_vowels('rhythm') == 0",
            "count_vowels('AEIOU') == 5",
        ),
        E(
            "collect_digit_characters",
            "숫자 글자만 모으기",
            "def digit_characters(text: str) -> str:",
            "text에서 숫자인 글자만 원래 순서대로 이어 반환한다.",
            "조건부 컴프리헨션과 str.isdigit을 사용한다.",
            "digit_characters('a1b2c3') == '123'",
            "digit_characters('no digits') == ''",
            "digit_characters('007') == '007'",
        ),
        E(
            "collect_uppercase_characters",
            "대문자만 골라내기",
            "def uppercase_characters(text: str) -> list[str]:",
            "text에서 대문자 글자만 리스트로 반환한다.",
            "리스트 컴프리헨션의 필터 조건을 연습한다.",
            "uppercase_characters('PyTHon') == ['P', 'T', 'H']",
            "uppercase_characters('abc') == []",
            "uppercase_characters('A1!B') == ['A', 'B']",
        ),
        E(
            "remove_whitespace_characters",
            "공백 문자 제거하기",
            "def without_whitespace(text: str) -> str:",
            "str.isspace가 True인 모든 문자를 제거한 새 문자열을 반환한다.",
            "generator 표현식의 부정 조건과 join을 결합한다.",
            "without_whitespace('a b c') == 'abc'",
            "without_whitespace(' a\\t b\\n') == 'ab'",
            "without_whitespace('') == ''",
        ),
        E(
            "count_specific_character",
            "특정 글자 세기",
            "def count_character(text: str, target: str) -> int:",
            "target이 한 글자라고 가정하고 text에서 target과 같은 글자의 개수를 반환한다.",
            "불리언 조건을 정수로 합산하는 짧은 순회 표현을 연습한다.",
            "count_character('banana', 'a') == 3",
            "count_character('banana', 'x') == 0",
            "count_character('', 'a') == 0",
        ),
        E(
            "replace_vowels_compactly",
            "모음을 기호로 바꾸기",
            "def mask_vowels(text: str, mask: str) -> str:",
            "대소문자 모음을 한 글자인 mask로 바꾸고 나머지 글자는 유지한다.",
            "조건 표현식을 포함한 generator와 join을 사용한다.",
            "mask_vowels('Apple', '*') == '*ppl*'",
            "mask_vowels('sky', '?') == 'sky'",
            "mask_vowels('AE', '-') == '--'",
        ),
        E(
            "alternate_character_case",
            "짝수 위치만 대문자로",
            "def alternating_case(text: str) -> str:",
            "짝수 인덱스 글자는 대문자, 홀수 인덱스 글자는 소문자로 바꿔 반환한다.",
            "enumerate와 조건 표현식을 한 번의 문자열 생성에 사용한다.",
            "alternating_case('python') == 'PyThOn'",
            "alternating_case('ABC') == 'AbC'",
            "alternating_case('') == ''",
        ),
        E(
            "mask_non_alphanumeric",
            "문자와 숫자 외 글자 가리기",
            "def mask_non_alphanumeric(text: str, mask: str = '_') -> str:",
            "영문자·한글·숫자 등 str.isalnum이 참인 글자는 유지하고 나머지는 mask로 바꾼다.",
            "문자 판별 메서드와 조건부 generator 표현식을 결합한다.",
            "mask_non_alphanumeric('a-b c') == 'a_b_c'",
            "mask_non_alphanumeric('A1!', '*') == 'A1*'",
            "mask_non_alphanumeric('한글2') == '한글2'",
        ),
        E(
            "check_all_ascii_characters",
            "모두 ASCII인지 확인하기",
            "def all_ascii(text: str) -> bool:",
            "모든 문자의 ord 값이 128보다 작으면 True를 반환하며 빈 문자열도 True로 본다.",
            "all과 generator 표현식의 빈 입력 동작을 익힌다.",
            "all_ascii('Python 3!') is True",
            "all_ascii('한글') is False",
            "all_ascii('') is True",
        ),
        E(
            "check_any_decimal_digit",
            "숫자 글자 존재 확인하기",
            "def contains_digit(text: str) -> bool:",
            "text에 str.isdigit이 참인 글자가 하나라도 있으면 True를 반환한다.",
            "any와 generator 표현식으로 조기 성공 조건을 표현한다.",
            "contains_digit('room 101') is True",
            "contains_digit('python') is False",
            "contains_digit('') is False",
        ),
    ],
    "string_concatenation": [
        E(
            "join_words_with_separator",
            "구분자로 단어 연결하기",
            "def join_words(words: list[str], separator: str) -> str:",
            "words를 separator로 연결하되 처음과 끝에는 separator를 붙이지 않는다.",
            "문자열 누적 시 구분자를 넣는 위치를 구분한다.",
            "join_words(['a', 'b'], '-') == 'a-b'",
            "join_words(['solo'], ',') == 'solo'",
            "join_words([], '/') == ''",
        ),
        E(
            "concatenate_two_texts",
            "두 문자열 바로 붙이기",
            "def concatenate_text(left: str, right: str) -> str:",
            "left 뒤에 right를 그대로 붙인 문자열을 반환한다.",
            "+ 연산자의 문자열 결합 동작과 빈 문자열을 확인한다.",
            "concatenate_text('hello', 'world') == 'helloworld'",
            "concatenate_text('', 'x') == 'x'",
            "concatenate_text('a', '') == 'a'",
        ),
        E(
            "build_slash_path",
            "경로 조각 연결하기",
            "def build_path(parts: list[str]) -> str:",
            "각 part에는 슬래시가 없다고 가정하고 '/'로 연결한 절대 경로를 만들며 빈 parts는 '/'를 반환한다.",
            "고정 접두사와 반복되는 구분자 결합을 처리한다.",
            "build_path(['users', 'ada']) == '/users/ada'",
            "build_path(['tmp']) == '/tmp'",
            "build_path([]) == '/'",
        ),
        E(
            "interleave_two_texts",
            "두 문자열 번갈아 붙이기",
            "def interleave_text(left: str, right: str) -> str:",
            "양쪽 글자를 같은 인덱스 순서로 번갈아 붙이고, 더 긴 쪽의 남은 부분은 끝에 붙인다.",
            "인덱스별 문자열 결합과 서로 다른 길이의 나머지 처리를 연습한다.",
            "interleave_text('abc', '123') == 'a1b2c3'",
            "interleave_text('ab', '1234') == 'a1b234'",
            "interleave_text('', 'xy') == 'xy'",
        ),
        E(
            "surround_text_with_tokens",
            "양쪽 장식 붙이기",
            "def surround_text(text: str, left: str, right: str) -> str:",
            "left, text, right 순서로 이어 붙여 반환한다.",
            "세 문자열의 결합 순서를 정확히 유지한다.",
            "surround_text('title', '[', ']') == '[title]'",
            "surround_text('', '<', '>') == '<>'",
            "surround_text('x', '', '!') == 'x!'",
        ),
        E(
            "repeat_text_with_separator",
            "구분자를 넣어 반복하기",
            "def repeat_with_separator(text: str, count: int, separator: str) -> str:",
            "count는 0 이상이라고 가정한다. text를 count번 연결하고 각 복사본 사이에만 separator를 넣으며 count가 0이면 ''를 반환한다.",
            "반복 결합에서 마지막 뒤의 불필요한 구분자를 피한다.",
            "repeat_with_separator('ha', 3, '-') == 'ha-ha-ha'",
            "repeat_with_separator('x', 1, ',') == 'x'",
            "repeat_with_separator('x', 0, ',') == ''",
        ),
        E(
            "build_initials",
            "이름 첫 글자 연결하기",
            "def make_initials(words: list[str]) -> str:",
            "비어 있지 않은 각 단어의 첫 글자를 대문자로 바꾸어 이어 붙인다.",
            "인덱싱한 한 글자를 변환한 뒤 결과 문자열에 누적한다.",
            "make_initials(['ada', 'lovelace']) == 'AL'",
            "make_initials(['grace', '', 'hopper']) == 'GH'",
            "make_initials([]) == ''",
        ),
        E(
            "concatenate_nonempty_parts",
            "빈 조각을 건너뛰어 연결하기",
            "def concatenate_nonempty(parts: list[str], separator: str) -> str:",
            "빈 문자열을 제외한 parts만 separator로 연결한다.",
            "결합 대상 선별과 구분자 위치 관리를 함께 연습한다.",
            "concatenate_nonempty(['a', '', 'b'], ':') == 'a:b'",
            "concatenate_nonempty(['', ''], '-') == ''",
            "concatenate_nonempty(['x'], '/') == 'x'",
        ),
        E(
            "build_sentence_from_words",
            "단어로 문장 만들기",
            "def sentence_from_words(words: list[str]) -> str:",
            "words를 공백 하나로 연결하고, 단어가 있으면 끝에 마침표 하나를 붙이며 빈 리스트는 ''를 반환한다.",
            "단어 사이 결합과 문장 끝 구두점을 별도로 처리한다.",
            "sentence_from_words(['Python', 'is', 'fun']) == 'Python is fun.'",
            "sentence_from_words(['Hello']) == 'Hello.'",
            "sentence_from_words([]) == ''",
        ),
        E(
            "attach_suffix_to_each_word",
            "각 단어에 접미사 붙이기",
            "def words_with_suffix(words: list[str], suffix: str) -> str:",
            "각 단어 뒤에 suffix를 붙인 뒤 결과들을 공백 하나로 연결한다.",
            "원소별 문자열 결합과 전체 결과 결합의 두 단계를 구분한다.",
            "words_with_suffix(['read', 'walk'], 'ing') == 'reading walking'",
            "words_with_suffix(['cat'], 's') == 'cats'",
            "words_with_suffix([], '!') == ''",
        ),
    ],
    "string_slicing_1": [
        E(
            "take_prefix_and_suffix",
            "앞뒤 조각 함께 자르기",
            "def prefix_suffix(text: str, size: int) -> tuple[str, str]:",
            "text의 앞 size글자와 뒤 size글자를 tuple로 반환하며 size는 0 이상이다.",
            "양수 범위 슬라이스와 음수 시작 슬라이스를 나란히 사용한다.",
            "prefix_suffix('python', 2) == ('py', 'on')",
            "prefix_suffix('cat', 5) == ('cat', 'cat')",
            "prefix_suffix('abc', 0) == ('', '')",
        ),
        E(
            "take_text_prefix",
            "앞에서 n글자 가져오기",
            "def take_prefix(text: str, size: int) -> str:",
            "size가 0 이상이라고 가정하고 text의 앞 size글자를 반환한다.",
            "시작을 생략한 슬라이스가 길이를 넘어가도 안전함을 익힌다.",
            "take_prefix('python', 3) == 'pyt'",
            "take_prefix('hi', 5) == 'hi'",
            "take_prefix('abc', 0) == ''",
        ),
        E(
            "take_text_suffix",
            "뒤에서 n글자 가져오기",
            "def take_suffix(text: str, size: int) -> str:",
            "size가 0 이상이라고 가정하고 뒤 size글자를 반환하되 size가 0이면 ''를 반환한다.",
            "음수 시작 슬라이스와 -0의 예외적인 의미를 구분한다.",
            "take_suffix('python', 3) == 'hon'",
            "take_suffix('hi', 5) == 'hi'",
            "take_suffix('abc', 0) == ''",
        ),
        E(
            "remove_text_edges",
            "양 끝 글자 제거하기",
            "def remove_text_edges(text: str) -> str:",
            "첫 글자와 마지막 글자를 제외한 가운데 부분을 반환하며 길이가 2 이하면 ''를 반환한다.",
            "고정된 시작·끝 경계의 슬라이싱을 연습한다.",
            "remove_text_edges('python') == 'ytho'",
            "remove_text_edges('ab') == ''",
            "remove_text_edges('') == ''",
        ),
        E(
            "extract_center_slice",
            "가운데 구간 자르기",
            "def center_slice(text: str, size: int) -> str:",
            "size가 text 길이 이하이고 둘의 홀짝이 같다고 가정해, 정확히 size글자인 가운데 부분을 반환한다.",
            "전체 길이와 목표 길이 차이로 대칭 슬라이스 경계를 계산한다.",
            "center_slice('abcdefgh', 4) == 'cdef'",
            "center_slice('abcde', 3) == 'bcd'",
            "center_slice('abc', 0) == ''",
        ),
        E(
            "split_text_at_index",
            "한 위치에서 문자열 나누기",
            "def split_text_at(text: str, index: int) -> tuple[str, str]:",
            "Python 슬라이스 규칙에 따라 index 앞부분과 index 이후 부분을 tuple로 반환한다.",
            "같은 경계를 끝 인덱스와 시작 인덱스로 사용한다.",
            "split_text_at('python', 2) == ('py', 'thon')",
            "split_text_at('abc', 0) == ('', 'abc')",
            "split_text_at('abc', 10) == ('abc', '')",
        ),
        E(
            "trim_different_edge_sizes",
            "앞뒤에서 서로 다르게 잘라내기",
            "def trim_text(text: str, left_count: int, right_count: int) -> str:",
            "앞 left_count글자와 뒤 right_count글자를 제거하며 두 값은 0 이상이고 합이 text 길이 이하라고 가정한다.",
            "0인 오른쪽 제거량을 포함해 동적인 슬라이스 끝 경계를 처리한다.",
            "trim_text('abcdefgh', 2, 3) == 'cde'",
            "trim_text('python', 0, 2) == 'pyth'",
            "trim_text('abc', 1, 0) == 'bc'",
        ),
        E(
            "take_first_half",
            "문자열 앞 절반",
            "def first_half(text: str) -> str:",
            "text의 앞 len(text) // 2글자를 반환해 홀수 길이에서는 가운데 글자를 제외한다.",
            "정수 나눗셈 결과를 슬라이스 끝으로 사용한다.",
            "first_half('abcdef') == 'abc'",
            "first_half('abcde') == 'ab'",
            "first_half('') == ''",
        ),
        E(
            "take_last_half",
            "문자열 뒤 절반",
            "def last_half(text: str) -> str:",
            "text의 뒤 len(text) // 2글자를 반환해 홀수 길이에서는 가운데 글자를 제외한다.",
            "길이에서 절반을 뺀 위치를 슬라이스 시작으로 사용한다.",
            "last_half('abcdef') == 'def'",
            "last_half('abcde') == 'de'",
            "last_half('') == ''",
        ),
        E(
            "extract_text_window",
            "고정 길이 창 자르기",
            "def text_window(text: str, start: int, size: int) -> str:",
            "start가 0 이상이고 size가 0 이상이라고 가정해 start부터 최대 size글자를 반환한다.",
            "시작 위치와 길이를 끝 위치로 변환해 슬라이스한다.",
            "text_window('abcdefgh', 2, 3) == 'cde'",
            "text_window('abc', 1, 5) == 'bc'",
            "text_window('abc', 3, 2) == ''",
        ),
    ],
    "string_slicing_2": [
        E(
            "take_every_other_character",
            "한 글자씩 건너뛰기",
            "def every_other(text: str) -> str:",
            "0번 인덱스부터 두 칸 간격으로 선택한 문자열을 반환한다.",
            "슬라이스의 step 자리에 2를 사용한다.",
            "every_other('abcdef') == 'ace'",
            "every_other('abcde') == 'ace'",
            "every_other('') == ''",
        ),
        E(
            "take_odd_position_characters",
            "홀수 인덱스 글자 모으기",
            "def odd_index_characters(text: str) -> str:",
            "1번 인덱스부터 두 칸 간격으로 선택한 문자열을 반환한다.",
            "시작점 1과 step 2가 있는 슬라이스를 사용한다.",
            "odd_index_characters('abcdef') == 'bdf'",
            "odd_index_characters('abcde') == 'bd'",
            "odd_index_characters('a') == ''",
        ),
        E(
            "slice_text_with_custom_step",
            "사용자가 정한 간격으로 자르기",
            "def stepped_text(text: str, start: int, step: int) -> str:",
            "step이 양수라고 가정하고 start부터 끝까지 step 간격의 글자를 반환한다.",
            "슬라이스의 시작점과 보폭을 매개변수로 적용한다.",
            "stepped_text('abcdefgh', 1, 3) == 'beh'",
            "stepped_text('abcdef', 0, 2) == 'ace'",
            "stepped_text('abc', 5, 2) == ''",
        ),
        E(
            "separate_even_and_odd_characters",
            "짝수·홀수 위치로 분리하기",
            "def split_alternating_characters(text: str) -> tuple[str, str]:",
            "짝수 인덱스 글자 문자열과 홀수 인덱스 글자 문자열을 tuple로 반환한다.",
            "같은 문자열에 시작점만 다른 step 슬라이스 두 개를 적용한다.",
            "split_alternating_characters('abcdef') == ('ace', 'bdf')",
            "split_alternating_characters('abcde') == ('ace', 'bd')",
            "split_alternating_characters('') == ('', '')",
        ),
        E(
            "take_text_in_reverse_steps",
            "뒤에서 간격을 두고 읽기",
            "def reverse_step_text(text: str, step: int) -> str:",
            "step이 양수라고 가정하고 마지막 글자부터 왼쪽으로 step칸씩 이동한 글자를 반환한다.",
            "음수 슬라이스 보폭을 동적으로 구성한다.",
            "reverse_step_text('abcdef', 2) == 'fdb'",
            "reverse_step_text('abcdefg', 3) == 'gda'",
            "reverse_step_text('', 2) == ''",
        ),
        E(
            "slice_bounded_stride",
            "범위와 간격을 함께 지정하기",
            "def bounded_stride(text: str, start: int, stop: int, step: int) -> str:",
            "Python의 text[start:stop:step]과 같은 결과를 반환하며 step은 0이 아니다.",
            "세 요소를 모두 가진 슬라이스 문법을 연습한다.",
            "bounded_stride('abcdefgh', 1, 7, 2) == 'bdf'",
            "bounded_stride('abcdefgh', 6, 0, -2) == 'gec'",
            "bounded_stride('abc', 0, 0, 1) == ''",
        ),
        E(
            "rotate_text_by_slicing",
            "문자열 왼쪽 회전하기",
            "def rotate_text_left(text: str, amount: int) -> str:",
            "빈 문자열은 그대로 반환하고, 그 외에는 amount를 길이로 나눈 나머지만큼 왼쪽으로 회전한다.",
            "두 슬라이스를 순서를 바꿔 결합하고 큰 회전량을 정규화한다.",
            "rotate_text_left('abcdef', 2) == 'cdefab'",
            "rotate_text_left('abc', 4) == 'bca'",
            "rotate_text_left('', 3) == ''",
        ),
        E(
            "take_every_third_block_start",
            "세 글자 블록의 첫 글자",
            "def block_starts(text: str, block_size: int) -> str:",
            "block_size가 양수라고 가정하고 각 block_size 길이 블록의 첫 글자들을 반환한다.",
            "0에서 시작하는 가변 step 슬라이스를 블록 선택으로 해석한다.",
            "block_starts('abcdefghij', 3) == 'adgj'",
            "block_starts('abc', 5) == 'a'",
            "block_starts('', 2) == ''",
        ),
        E(
            "drop_every_other_character",
            "첫 글자를 버리고 번갈아 선택하기",
            "def drop_then_stride(text: str, drop: int, step: int) -> str:",
            "drop과 step이 양수라고 가정해 앞 drop글자를 제외한 뒤 남은 문자열에서 step 간격으로 선택한다.",
            "슬라이스 시작과 보폭을 실제 요구사항으로 변환한다.",
            "drop_then_stride('abcdefgh', 2, 2) == 'ceg'",
            "drop_then_stride('python', 1, 3) == 'yo'",
            "drop_then_stride('abc', 5, 2) == ''",
        ),
        E(
            "reverse_selected_text_range",
            "선택 구간을 거꾸로 읽기",
            "def reverse_text_range(text: str, start: int, stop: int) -> str:",
            "0 이상인 start와 stop이 start 이하라고 가정하고, start 인덱스부터 stop 초과 위치까지 역순으로 반환한다.",
            "음수 step 슬라이스에서 stop 경계가 제외됨을 익힌다.",
            "reverse_text_range('abcdef', 5, 1) == 'fedc'",
            "reverse_text_range('abcdef', 3, 0) == 'dcb'",
            "reverse_text_range('abc', 2, 2) == ''",
        ),
    ],
    "reverse_string": [
        E(
            "reverse_complete_text",
            "문자열 전체 뒤집기",
            "def reverse_text(text: str) -> str:",
            "text의 글자 순서를 완전히 뒤집은 새 문자열을 반환한다.",
            "음수 step 슬라이스로 처음부터 끝까지 역방향 선택한다.",
            "reverse_text('abc') == 'cba'",
            "reverse_text('A') == 'A'",
            "reverse_text('') == ''",
        ),
        E(
            "check_exact_palindrome",
            "그대로 읽어 같은지 확인하기",
            "def is_exact_palindrome(text: str) -> bool:",
            "대소문자와 공백을 그대로 유지한 text가 뒤집어도 같으면 True를 반환한다.",
            "원본과 전체 역순 슬라이스를 직접 비교한다.",
            "is_exact_palindrome('level') is True",
            "is_exact_palindrome('Level') is False",
            "is_exact_palindrome('') is True",
        ),
        E(
            "reverse_word_order",
            "단어 순서 뒤집기",
            "def reverse_word_order(sentence: str) -> str:",
            "공백 하나로 구분된 단어들의 순서만 뒤집어 공백 하나로 다시 연결한다.",
            "split 결과 리스트에 역방향 슬라이스를 적용한다.",
            "reverse_word_order('one two three') == 'three two one'",
            "reverse_word_order('hello') == 'hello'",
            "reverse_word_order('') == ''",
        ),
        E(
            "reverse_each_word",
            "각 단어 내부 뒤집기",
            "def reverse_words_inside(sentence: str) -> str:",
            "공백 하나로 구분된 각 단어의 글자 순서만 뒤집고 단어 순서는 유지한다.",
            "여러 문자열 각각에 역순 슬라이스를 적용한 뒤 재결합한다.",
            "reverse_words_inside('cat dog') == 'tac god'",
            "reverse_words_inside('Python') == 'nohtyP'",
            "reverse_words_inside('') == ''",
        ),
        E(
            "build_mirrored_text",
            "거울 문자열 만들기",
            "def mirror_text(text: str) -> str:",
            "text 뒤에 text의 역순을 붙여 좌우 대칭 문자열을 반환한다.",
            "원본 문자열과 역방향 슬라이스를 결합한다.",
            "mirror_text('abc') == 'abccba'",
            "mirror_text('x') == 'xx'",
            "mirror_text('') == ''",
        ),
        E(
            "reverse_text_prefix",
            "앞부분만 뒤집기",
            "def reverse_prefix(text: str, size: int) -> str:",
            "size가 0 이상이라고 가정해 앞 size글자만 뒤집고 나머지는 원래 순서로 둔다.",
            "앞부분 슬라이스를 역순으로 바꾼 뒤 뒤쪽 슬라이스와 연결한다.",
            "reverse_prefix('abcdef', 3) == 'cbadef'",
            "reverse_prefix('abc', 8) == 'cba'",
            "reverse_prefix('abc', 0) == 'abc'",
        ),
        E(
            "reverse_text_suffix",
            "뒷부분만 뒤집기",
            "def reverse_suffix(text: str, size: int) -> str:",
            "0 <= size <= len(text)라고 가정해 뒤 size글자만 뒤집고 앞부분은 유지한다.",
            "동적 분할 지점 양쪽에서 한쪽에만 역순 슬라이스를 적용한다.",
            "reverse_suffix('abcdef', 3) == 'abcfed'",
            "reverse_suffix('abc', 3) == 'cba'",
            "reverse_suffix('abc', 0) == 'abc'",
        ),
        E(
            "reverse_middle_text_segment",
            "지정 구간만 뒤집기",
            "def reverse_segment(text: str, start: int, stop: int) -> str:",
            "0 <= start <= stop <= len(text)라고 가정해 text[start:stop]만 뒤집은 문자열을 반환한다.",
            "앞·선택 구간·뒤의 세 슬라이스를 올바른 순서로 재조립한다.",
            "reverse_segment('abcdef', 1, 5) == 'aedcbf'",
            "reverse_segment('abc', 0, 3) == 'cba'",
            "reverse_segment('abc', 1, 1) == 'abc'",
        ),
        E(
            "check_normalized_palindrome",
            "공백과 대소문자를 무시한 회문",
            "def is_space_insensitive_palindrome(text: str) -> bool:",
            "공백 문자를 모두 제거하고 소문자로 바꾼 결과가 뒤집어도 같으면 True를 반환한다.",
            "비교 전에 정규화한 문자열 하나를 만들고 역순과 비교한다.",
            "is_space_insensitive_palindrome('Never odd or even') is True",
            "is_space_insensitive_palindrome('Python') is False",
            "is_space_insensitive_palindrome('   ') is True",
        ),
        E(
            "compare_reverse_pair",
            "서로 역순인 문자열인지 확인하기",
            "def are_reverse_pair(left: str, right: str) -> bool:",
            "right가 left의 정확한 역순일 때만 True를 반환한다.",
            "한 문자열의 역방향 슬라이스를 다른 문자열과 비교한다.",
            "are_reverse_pair('abc', 'cba') is True",
            "are_reverse_pair('abc', 'abc') is False",
            "are_reverse_pair('', '') is True",
        ),
    ],
    "strings_immutable": [
        E(
            "replace_one_character_copy",
            "한 글자를 바꾼 새 문자열",
            "def replace_character(text: str, index: int, replacement: str) -> str:",
            "index가 유효하고 replacement가 한 글자라고 가정해 해당 위치만 바꾼 새 문자열을 반환한다.",
            "문자열은 수정할 수 없으므로 앞·대체 글자·뒤를 재결합한다.",
            "replace_character('cat', 0, 'b') == 'bat'",
            "replace_character('code', 2, 'v') == 'cove'",
            "replace_character('A', 0, 'Z') == 'Z'",
        ),
        E(
            "insert_character_copy",
            "문자를 끼워 넣은 새 문자열",
            "def insert_character(text: str, index: int, character: str) -> str:",
            "0 <= index <= len(text)이고 character가 한 글자라고 가정해 index 위치에 삽입한 새 문자열을 반환한다.",
            "삽입 지점 앞뒤 슬라이스 사이에 새 글자를 결합한다.",
            "insert_character('cat', 1, 'r') == 'crat'",
            "insert_character('abc', 0, '!') == '!abc'",
            "insert_character('abc', 3, '!') == 'abc!'",
        ),
        E(
            "remove_character_copy",
            "한 글자를 제외한 새 문자열",
            "def remove_character_at(text: str, index: int) -> str:",
            "index가 유효하다고 가정해 해당 위치의 글자만 제외한 새 문자열을 반환한다.",
            "삭제 대상 앞과 뒤를 슬라이스해 새 값으로 결합한다.",
            "remove_character_at('python', 1) == 'pthon'",
            "remove_character_at('abc', 0) == 'bc'",
            "remove_character_at('abc', 2) == 'ab'",
        ),
        E(
            "replace_text_range_copy",
            "구간을 새 문자열로 교체하기",
            "def replace_text_range(text: str, start: int, stop: int, replacement: str) -> str:",
            "0 <= start <= stop <= len(text)라고 가정해 text[start:stop]을 replacement로 교체한 새 문자열을 반환한다.",
            "변경되지 않는 양쪽 슬라이스와 대체 문자열을 재조립한다.",
            "replace_text_range('abcdef', 2, 4, 'XY') == 'abXYef'",
            "replace_text_range('abc', 0, 3, '') == ''",
            "replace_text_range('abc', 1, 1, '-') == 'a-bc'",
        ),
        E(
            "replace_first_substring_copy",
            "첫 부분 문자열만 바꾸기",
            "def replace_first_substring(text: str, old: str, new: str) -> str:",
            "old가 비어 있지 않다고 가정하고 처음 등장한 old만 new로 바꾸며, 없으면 text를 그대로 반환한다.",
            "원본 변경 없이 첫 일치 위치를 기준으로 새 문자열을 만든다.",
            "replace_first_substring('one one', 'one', 'two') == 'two one'",
            "replace_first_substring('banana', 'na', 'X') == 'baXna'",
            "replace_first_substring('abc', 'z', '!') == 'abc'",
        ),
        E(
            "uppercase_one_character_copy",
            "한 위치만 대문자로 바꾸기",
            "def uppercase_character_at(text: str, index: int) -> str:",
            "index가 유효하다고 가정해 그 위치의 글자만 upper 결과로 교체한 새 문자열을 반환한다.",
            "읽은 한 글자를 변환하고 원본의 나머지 조각과 결합한다.",
            "uppercase_character_at('python', 0) == 'Python'",
            "uppercase_character_at('abc', 1) == 'aBc'",
            "uppercase_character_at('A', 0) == 'A'",
        ),
        E(
            "swap_two_characters_copy",
            "두 글자 위치 바꾸기",
            "def swap_characters_at(text: str, first: int, second: int) -> str:",
            "두 인덱스가 유효하다고 가정해 해당 글자들의 위치를 바꾼 새 문자열을 반환한다.",
            "문자열을 변경 가능한 글자 리스트로 복사한 뒤 다시 문자열로 만든다.",
            "swap_characters_at('abcd', 0, 3) == 'dbca'",
            "swap_characters_at('abcd', 1, 2) == 'acbd'",
            "swap_characters_at('abc', 1, 1) == 'abc'",
        ),
        E(
            "mask_selected_text_indices",
            "선택 위치 가리기",
            "def mask_text_indices(text: str, indices: list[int], mask: str) -> str:",
            "indices에는 유효한 0 이상 인덱스가 들어 있고 mask는 한 글자라고 가정해 지정 위치들을 mask로 바꾼 새 문자열을 반환한다.",
            "원본을 보존하면서 여러 위치를 변경 가능한 복사본에 반영한다.",
            "mask_text_indices('secret', [1, 3], '*') == 's*c*et'",
            "mask_text_indices('abc', [], '#') == 'abc'",
            "mask_text_indices('aaa', [0, 1, 2], '-') == '---'",
        ),
        E(
            "apply_character_replacements_copy",
            "여러 글자 교체 적용하기",
            "def apply_character_replacements(text: str, replacements: list[tuple[int, str]]) -> str:",
            "각 인덱스가 유효하고 각 대체값이 한 글자라고 가정해 모든 교체를 순서대로 반영한 새 문자열을 반환한다.",
            "하나의 변경 가능한 복사본에 여러 갱신을 적용한 뒤 불변 문자열로 변환한다.",
            "apply_character_replacements('abcd', [(0, 'A'), (3, 'D')]) == 'AbcD'",
            "apply_character_replacements('cat', [(1, 'u')]) == 'cut'",
            "apply_character_replacements('abc', []) == 'abc'",
        ),
        E(
            "replace_periodic_characters_copy",
            "일정 간격의 글자 교체하기",
            "def replace_every_nth_character(text: str, n: int, replacement: str) -> str:",
            "n이 양수이고 replacement가 한 글자라고 가정해 1부터 셌을 때 n번째마다 해당 글자를 교체한다.",
            "원본을 직접 고치지 않고 위치 조건으로 새 문자열을 생성한다.",
            "replace_every_nth_character('abcdefgh', 3, '*') == 'ab*de*gh'",
            "replace_every_nth_character('abc', 1, '-') == '---'",
            "replace_every_nth_character('', 2, '?') == ''",
        ),
    ],
    "string_formatting": [
        E(
            "format_purchase_receipt",
            "영수증 한 줄 만들기",
            "def format_receipt(item: str, quantity: int, price: float) -> str:",
            "총액 quantity * price를 소수점 둘째 자리까지 표시해 '<item> x<quantity> = <total>' 형식으로 반환한다.",
            "f-string 안에서 계산값과 소수점 형식 지정자를 사용한다.",
            "format_receipt('pen', 2, 1.5) == 'pen x2 = 3.00'",
            "format_receipt('book', 1, 12.0) == 'book x1 = 12.00'",
            "format_receipt('free', 3, 0.0) == 'free x3 = 0.00'",
        ),
        E(
            "format_person_name",
            "성명 표시 형식 만들기",
            "def format_person_name(first: str, last: str) -> str:",
            "'<last>, <first>' 형식의 문자열을 반환한다.",
            "f-string 자리의 순서를 입력 매개변수 순서와 다르게 배치한다.",
            "format_person_name('Ada', 'Lovelace') == 'Lovelace, Ada'",
            "format_person_name('Grace', 'Hopper') == 'Hopper, Grace'",
            "format_person_name('', 'Solo') == 'Solo, '",
        ),
        E(
            "format_score_fraction",
            "점수와 만점 표시하기",
            "def format_score_line(name: str, score: int, maximum: int) -> str:",
            "'<name>: <score>/<maximum>' 형식으로 반환한다.",
            "여러 타입의 값을 f-string 한 줄에 삽입한다.",
            "format_score_line('Ada', 95, 100) == 'Ada: 95/100'",
            "format_score_line('Kim', 0, 10) == 'Kim: 0/10'",
            "format_score_line('', 3, 5) == ': 3/5'",
        ),
        E(
            "format_xy_coordinates",
            "좌표 표시하기",
            "def format_coordinates(x: float, y: float) -> str:",
            "각 좌표를 소수점 한 자리로 표시해 '(x, y)' 형식으로 반환한다.",
            "두 실수에 동일한 고정 소수점 형식을 적용한다.",
            "format_coordinates(1, 2) == '(1.0, 2.0)'",
            "format_coordinates(-1.25, 3.76) == '(-1.2, 3.8)'",
            "format_coordinates(0.0, 0.0) == '(0.0, 0.0)'",
        ),
        E(
            "format_ratio_percentage",
            "비율을 퍼센트로 표시하기",
            "def format_percentage(ratio: float) -> str:",
            "0 이상인 ratio를 퍼센트로 바꾸어 소수점 한 자리와 '%'를 붙여 반환한다.",
            "f-string의 퍼센트 형식 지정자를 사용한다.",
            "format_percentage(0.125) == '12.5%'",
            "format_percentage(1.0) == '100.0%'",
            "format_percentage(0.0) == '0.0%'",
        ),
        E(
            "format_fixed_width_row",
            "고정 너비 표 한 줄",
            "def format_fixed_width_row(label: str, value: int) -> str:",
            "label은 너비 10에 왼쪽 정렬하고 value는 너비 5에 오른쪽 정렬해 두 필드를 바로 이어 반환한다.",
            "문자열과 정수에 서로 다른 정렬·너비 형식 지정자를 적용한다.",
            "format_fixed_width_row('apple', 42) == 'apple        42'",
            "format_fixed_width_row('x', 7) == 'x             7'",
            "format_fixed_width_row('abcdefghij', 12345) == 'abcdefghij12345'",
        ),
        E(
            "format_seconds_as_clock",
            "초를 시계 형식으로 표시하기",
            "def format_duration(total_seconds: int) -> str:",
            "0 이상인 total_seconds를 분과 초로 나누어 'MM:SS' 형식으로 반환한다.",
            "계산한 정수를 f-string에서 두 자리 0 채움으로 표현한다.",
            "format_duration(65) == '01:05'",
            "format_duration(9) == '00:09'",
            "format_duration(3599) == '59:59'",
        ),
        E(
            "format_currency_amount",
            "통화 금액 표시하기",
            "def format_currency(symbol: str, amount: float) -> str:",
            "symbol 뒤에 amount를 천 단위 쉼표와 소수점 둘째 자리까지 표시한다.",
            "숫자 형식 지정자의 그룹 구분과 정밀도를 함께 사용한다.",
            "format_currency('$', 1234.5) == '$1,234.50'",
            "format_currency('₩', 0) == '₩0.00'",
            "format_currency('€', -12.3) == '€-12.30'",
        ),
        E(
            "format_inventory_status",
            "재고 상태 한 줄",
            "def format_inventory(item: str, stock: int) -> str:",
            "stock이 0보다 크면 '<item>: <stock> left', 아니면 '<item>: out of stock'을 반환한다.",
            "조건으로 고른 값을 f-string의 일정한 접두사와 결합한다.",
            "format_inventory('pen', 3) == 'pen: 3 left'",
            "format_inventory('book', 0) == 'book: out of stock'",
            "format_inventory('', 1) == ': 1 left'",
        ),
        E(
            "format_calendar_date",
            "날짜를 0 채움 형식으로 표시하기",
            "def format_date(year: int, month: int, day: int) -> str:",
            "유효한 날짜 구성요소를 'YYYY-MM-DD' 형태로 0을 채워 반환한다.",
            "정수별 최소 너비와 0 채움 형식 지정자를 사용한다.",
            "format_date(2026, 8, 24) == '2026-08-24'",
            "format_date(7, 1, 2) == '0007-01-02'",
            "format_date(1999, 12, 31) == '1999-12-31'",
        ),
    ],
    "intro_lists": [
        E(
            "make_three_item_list",
            "세 값을 리스트에 담기",
            "def make_list(first: object, second: object, third: object) -> list[object]:",
            "세 값을 입력받은 순서 그대로 새 리스트에 담아 반환한다.",
            "서로 다른 타입도 한 리스트에 저장할 수 있음을 익힌다.",
            "make_list(1, 'a', True) == [1, 'a', True]",
            "make_list(None, 2.5, []) == [None, 2.5, []]",
            "make_list('x', 'y', 'z') == ['x', 'y', 'z']",
        ),
        E(
            "convert_pair_to_list",
            "두 값을 리스트로 바꾸기",
            "def pair_as_list(pair: tuple[object, object]) -> list[object]:",
            "두 원소 tuple의 값을 같은 순서의 새 리스트로 반환한다.",
            "tuple과 list의 표기 및 변환 결과 차이를 확인한다.",
            "pair_as_list(('a', 1)) == ['a', 1]",
            "pair_as_list((True, None)) == [True, None]",
            "pair_as_list(([], {})) == [[], {}]",
        ),
        E(
            "repeat_value_in_list",
            "같은 값으로 리스트 채우기",
            "def repeated_values(value: object, count: int) -> list[object]:",
            "value는 int, float, bool, str, tuple, None처럼 변경할 수 없는 값이고 count는 0 이상이라고 가정한다. value를 count번 담은 리스트를 반환한다.",
            "가변 객체의 참조 공유 문제 없이 불변 값을 정해진 횟수만큼 배치한다.",
            "repeated_values('x', 3) == ['x', 'x', 'x']",
            "repeated_values(0, 1) == [0]",
            "repeated_values(True, 0) == []",
        ),
        E(
            "make_inclusive_number_list",
            "연속 정수 리스트 만들기",
            "def make_inclusive_numbers(start: int, stop: int) -> list[int]:",
            "start <= stop이면 start부터 stop까지 포함한 정수 리스트를, 아니면 빈 리스트를 반환한다.",
            "range 결과를 list로 변환하고 포함 경계를 조정한다.",
            "make_inclusive_numbers(2, 5) == [2, 3, 4, 5]",
            "make_inclusive_numbers(-2, 0) == [-2, -1, 0]",
            "make_inclusive_numbers(4, 3) == []",
        ),
        E(
            "convert_text_to_character_list",
            "문자열을 글자 리스트로",
            "def text_as_character_list(text: str) -> list[str]:",
            "text의 각 글자를 순서대로 담은 새 리스트를 반환한다.",
            "list 생성자가 iterable을 원소 단위로 펼치는 동작을 확인한다.",
            "text_as_character_list('cat') == ['c', 'a', 't']",
            "text_as_character_list(' ') == [' ']",
            "text_as_character_list('') == []",
        ),
        E(
            "make_optional_singleton_list",
            "값이 있을 때만 한 칸 리스트",
            "def optional_singleton(value: object | None) -> list[object]:",
            "value가 None이면 빈 리스트를, 아니면 value 하나만 든 리스트를 반환한다.",
            "빈 리스트와 단일 원소 리스트를 조건에 따라 생성한다.",
            "optional_singleton('x') == ['x']",
            "optional_singleton(0) == [0]",
            "optional_singleton(None) == []",
        ),
        E(
            "make_alternating_value_list",
            "두 값을 번갈아 담기",
            "def alternating_values(first: object, second: object, pairs: int) -> list[object]:",
            "pairs가 0 이상이라고 가정해 [first, second] 순서를 pairs번 반복한 리스트를 반환한다.",
            "작은 리스트 단위의 반복과 원소 순서 보존을 연습한다.",
            "alternating_values('A', 'B', 3) == ['A', 'B', 'A', 'B', 'A', 'B']",
            "alternating_values(1, 2, 1) == [1, 2]",
            "alternating_values(True, False, 0) == []",
        ),
        E(
            "make_nested_pair_lists",
            "두 개의 안쪽 리스트 만들기",
            "def nested_pairs(a: object, b: object, c: object, d: object) -> list[list[object]]:",
            "[a, b]와 [c, d]를 각각 안쪽 리스트로 만들어 바깥 리스트에 담는다.",
            "중첩 리스트 리터럴의 계층과 원소 순서를 익힌다.",
            "nested_pairs(1, 2, 3, 4) == [[1, 2], [3, 4]]",
            "nested_pairs('a', True, None, 0) == [['a', True], [None, 0]]",
            "nested_pairs([], {}, (), '') == [[[], {}], [(), '']]",
        ),
        E(
            "tag_values_in_list",
            "이름표와 값들을 한 리스트에",
            "def tagged_values(tag: str, values: list[object]) -> list[object]:",
            "tag를 첫 원소로 두고 values의 원소들을 뒤에 같은 순서로 담은 새 리스트를 반환한다.",
            "한 원소 리스트와 기존 리스트를 결합해 새 컨테이너를 만든다.",
            "tagged_values('scores', [10, 20]) == ['scores', 10, 20]",
            "tagged_values('empty', []) == ['empty']",
            "tagged_values('', [True]) == ['', True]",
        ),
        E(
            "make_boolean_pattern_list",
            "참·거짓 패턴 리스트",
            "def boolean_pattern(length: int) -> list[bool]:",
            "length가 0 이상이라고 가정해 인덱스 0부터 짝수 위치는 True, 홀수 위치는 False인 리스트를 반환한다.",
            "리스트 원소의 위치에 따라 값을 생성한다.",
            "boolean_pattern(5) == [True, False, True, False, True]",
            "boolean_pattern(2) == [True, False]",
            "boolean_pattern(0) == []",
        ),
    ],
    "list_operations": [
        E(
            "update_list_index_copy",
            "복사본의 한 위치 수정하기",
            "def update_at(values: list[int], index: int, value: int) -> list[int]:",
            "index가 유효하다고 가정하고 values는 변경하지 않은 채 복사본의 index 위치만 value로 바꾸어 반환한다.",
            "얕은 복사 뒤 인덱스 할당을 수행해 원본과 결과를 분리한다.",
            "((items := [1, 2, 3]), update_at(items, 1, 9) == [1, 9, 3] and items == [1, 2, 3])[-1] is True",
            "update_at([5], 0, -1) == [-1]",
            "update_at([1, 2], -1, 7) == [1, 7]",
        ),
        E(
            "swap_list_indices_copy",
            "복사본에서 두 원소 맞바꾸기",
            "def swap_list_items(values: list[int], first: int, second: int) -> list[int]:",
            "두 인덱스가 유효하다고 가정해 values의 복사본에서 두 원소의 위치를 바꾸어 반환한다.",
            "리스트 복사와 다중 할당을 함께 사용한다.",
            "((items := [1, 2, 3]), swap_list_items(items, 0, 2) == [3, 2, 1] and items == [1, 2, 3])[-1] is True",
            "swap_list_items([4, 5], 1, 1) == [4, 5]",
            "swap_list_items([1, 2, 3], -1, 0) == [3, 2, 1]",
        ),
        E(
            "replace_matching_list_values",
            "일치하는 원소 모두 바꾸기",
            "def replace_list_values(values: list[int], old: int, new: int) -> list[int]:",
            "values는 변경하지 않고 old와 같은 모든 원소를 new로 바꾼 리스트를 반환한다.",
            "원소별 조건으로 변경된 새 리스트를 생성한다.",
            "((items := [1, 2, 1]), replace_list_values(items, 1, 9) == [9, 2, 9] and items == [1, 2, 1])[-1] is True",
            "replace_list_values([3, 4], 8, 0) == [3, 4]",
            "replace_list_values([], 1, 2) == []",
        ),
        E(
            "increment_one_list_item",
            "한 원소만 증가시키기",
            "def increment_list_item(values: list[int], index: int, amount: int) -> list[int]:",
            "index가 유효하다고 가정해 복사본의 해당 원소에 amount를 더하고 values는 그대로 둔다.",
            "리스트 원소 읽기와 제자리 산술 할당을 복사본에 적용한다.",
            "((items := [10, 20]), increment_list_item(items, 1, 5) == [10, 25] and items == [10, 20])[-1] is True",
            "increment_list_item([3], 0, -3) == [0]",
            "increment_list_item([1, 2, 3], -1, 10) == [1, 2, 13]",
        ),
        E(
            "delete_list_index_copy",
            "지정 위치를 제외한 복사본",
            "def delete_list_item(values: list[int], index: int) -> list[int]:",
            "index가 유효하다고 가정해 values는 바꾸지 않고 해당 위치를 삭제한 새 리스트를 반환한다.",
            "복사본에 del을 적용하거나 양쪽 슬라이스를 결합한다.",
            "((items := [1, 2, 3]), delete_list_item(items, 1) == [1, 3] and items == [1, 2, 3])[-1] is True",
            "delete_list_item([5], 0) == []",
            "delete_list_item([1, 2, 3], -1) == [1, 2]",
        ),
        E(
            "insert_list_item_copy",
            "지정 위치에 원소 삽입하기",
            "def insert_list_item(values: list[int], index: int, value: int) -> list[int]:",
            "Python list.insert와 같은 인덱스 규칙으로 values의 복사본에 value를 삽입해 반환한다.",
            "복사본의 insert 연산이 원본 길이에 영향을 주지 않도록 한다.",
            "((items := [1, 3]), insert_list_item(items, 1, 2) == [1, 2, 3] and items == [1, 3])[-1] is True",
            "insert_list_item([2, 3], 0, 1) == [1, 2, 3]",
            "insert_list_item([1], 99, 2) == [1, 2]",
        ),
        E(
            "replace_list_slice_copy",
            "리스트 구간 교체하기",
            "def replace_list_slice(values: list[int], start: int, stop: int, replacement: list[int]) -> list[int]:",
            "values를 변경하지 않고 복사본의 values[start:stop] 구간을 replacement 원소들로 교체한다.",
            "슬라이스 할당으로 리스트 길이가 달라질 수 있음을 연습한다.",
            "((items := [1, 2, 3, 4]), replace_list_slice(items, 1, 3, [8, 9]) == [1, 8, 9, 4] and items == [1, 2, 3, 4])[-1] is True",
            "replace_list_slice([1, 2], 1, 1, [7]) == [1, 7, 2]",
            "replace_list_slice([1, 2, 3], 0, 3, []) == []",
        ),
        E(
            "rotate_list_left_copy",
            "리스트 왼쪽 회전 복사본",
            "def rotate_list_items_left(values: list[int], amount: int) -> list[int]:",
            "values가 비어 있으면 []를 반환하고, 아니면 amount를 길이로 나눈 나머지만큼 왼쪽으로 회전한 새 리스트를 반환한다.",
            "두 리스트 슬라이스를 재결합하고 원본은 수정하지 않는다.",
            "((items := [1, 2, 3, 4]), rotate_list_items_left(items, 1) == [2, 3, 4, 1] and items == [1, 2, 3, 4])[-1] is True",
            "rotate_list_items_left([1, 2, 3], 4) == [2, 3, 1]",
            "rotate_list_items_left([], 2) == []",
        ),
        E(
            "apply_list_index_updates",
            "여러 위치 갱신하기",
            "def apply_list_updates(values: list[int], updates: list[tuple[int, int]]) -> list[int]:",
            "updates의 인덱스가 모두 유효하다고 가정해 각 (index, value)을 순서대로 복사본에 적용한다.",
            "하나의 복사본에 여러 인덱스 할당을 누적하고 원본을 보존한다.",
            "((items := [1, 2, 3]), apply_list_updates(items, [(0, 9), (2, 7)]) == [9, 2, 7] and items == [1, 2, 3])[-1] is True",
            "apply_list_updates([1, 2], [(1, 5), (1, 8)]) == [1, 8]",
            "apply_list_updates([], []) == []",
        ),
        E(
            "zero_list_segment_copy",
            "지정 구간을 0으로 바꾸기",
            "def zero_list_segment(values: list[int], start: int, stop: int) -> list[int]:",
            "0 <= start <= stop <= len(values)라고 가정해 해당 반열린 구간의 원소만 0으로 바꾼 새 리스트를 반환한다.",
            "복사본의 연속된 여러 인덱스를 갱신한다.",
            "((items := [1, 2, 3, 4]), zero_list_segment(items, 1, 3) == [1, 0, 0, 4] and items == [1, 2, 3, 4])[-1] is True",
            "zero_list_segment([5, 6], 0, 2) == [0, 0]",
            "zero_list_segment([1, 2], 1, 1) == [1, 2]",
        ),
    ],
    "list_looping": [
        E(
            "sum_list_by_loop",
            "반복문으로 리스트 합계",
            "def sum_list(values: list[int]) -> int:",
            "for loop로 values의 모든 정수를 더해 반환한다.",
            "누적 변수의 초기값을 0으로 두고 원소마다 갱신한다.",
            "sum_list([2, 3, 4]) == 9",
            "sum_list([-2, 2]) == 0",
            "sum_list([]) == 0",
        ),
        E(
            "multiply_list_by_loop",
            "반복문으로 리스트 곱",
            "def product_list(values: list[int]) -> int:",
            "for loop로 모든 정수를 곱하며 빈 리스트는 1을 반환한다.",
            "곱셈 누적 변수의 항등원 1을 초기값으로 사용한다.",
            "product_list([2, 3, 4]) == 24",
            "product_list([-2, 3]) == -6",
            "product_list([]) == 1",
        ),
        E(
            "count_positive_list_items",
            "양수 원소 개수",
            "def count_positive_items(values: list[int]) -> int:",
            "values를 순회해 0보다 큰 원소의 개수를 반환한다.",
            "반복 중 조건을 만족할 때만 카운터를 증가시킨다.",
            "count_positive_items([-1, 0, 2, 3]) == 2",
            "count_positive_items([1, 1]) == 2",
            "count_positive_items([]) == 0",
        ),
        E(
            "square_list_items_by_loop",
            "각 원소 제곱하기",
            "def square_list_items(values: list[int]) -> list[int]:",
            "for loop에서 각 정수의 제곱을 새 리스트에 추가해 반환한다.",
            "입력 순서를 유지하며 변환 결과를 append한다.",
            "square_list_items([1, 3, -2]) == [1, 9, 4]",
            "square_list_items([0]) == [0]",
            "square_list_items([]) == []",
        ),
        E(
            "build_list_running_sums",
            "리스트 누적 합 만들기",
            "def list_running_sums(values: list[int]) -> list[int]:",
            "각 원소까지의 누적 합을 같은 길이의 리스트로 반환한다.",
            "누적 상태를 갱신한 직후 결과 리스트에 기록한다.",
            "list_running_sums([2, 3, 4]) == [2, 5, 9]",
            "list_running_sums([-1, 1, 5]) == [-1, 0, 5]",
            "list_running_sums([]) == []",
        ),
        E(
            "calculate_adjacent_differences",
            "이웃 원소 차이",
            "def adjacent_differences(values: list[int]) -> list[int]:",
            "각 i >= 1에 대해 values[i] - values[i-1]을 순서대로 반환한다.",
            "이전 원소와 현재 원소를 인덱스 반복에서 함께 읽는다.",
            "adjacent_differences([3, 8, 6]) == [5, -2]",
            "adjacent_differences([4]) == []",
            "adjacent_differences([]) == []",
        ),
        E(
            "flatten_one_list_level",
            "중첩 리스트 한 단계 펼치기",
            "def flatten_lists(groups: list[list[int]]) -> list[int]:",
            "각 안쪽 리스트를 순서대로 순회해 모든 정수를 하나의 리스트로 반환한다.",
            "중첩 for loop와 append로 원소 순서를 보존한다.",
            "flatten_lists([[1, 2], [3], [4, 5]]) == [1, 2, 3, 4, 5]",
            "flatten_lists([[], [1], []]) == [1]",
            "flatten_lists([]) == []",
        ),
        E(
            "filter_even_list_items",
            "짝수만 새 리스트에 담기",
            "def even_list_items(values: list[int]) -> list[int]:",
            "for loop로 values의 짝수만 원래 순서대로 반환한다.",
            "나머지 조건과 조건부 append를 사용한다.",
            "even_list_items([1, 2, 4, 5]) == [2, 4]",
            "even_list_items([-2, -1, 0]) == [-2, 0]",
            "even_list_items([]) == []",
        ),
        E(
            "sum_corresponding_list_items",
            "같은 위치 원소끼리 더하기",
            "def positional_sums(left: list[int], right: list[int]) -> list[int]:",
            "두 리스트의 길이가 같다고 가정해 같은 인덱스 원소의 합을 리스트로 반환한다.",
            "인덱스 순회로 두 리스트를 동시에 읽는다.",
            "positional_sums([1, 2], [10, 20]) == [11, 22]",
            "positional_sums([-1, 0], [1, 5]) == [0, 5]",
            "positional_sums([], []) == []",
        ),
        E(
            "partition_list_by_sign",
            "음수·0·양수로 나누기",
            "def partition_by_sign(values: list[int]) -> tuple[list[int], list[int], list[int]]:",
            "values를 순회해 음수, 0, 양수를 각각 원래 순서의 리스트로 나누어 tuple로 반환한다.",
            "한 번의 순회에서 세 결과 리스트 중 알맞은 곳에 append한다.",
            "partition_by_sign([-2, 0, 3, -1, 0]) == ([-2, -1], [0, 0], [3])",
            "partition_by_sign([1, 2]) == ([], [], [1, 2])",
            "partition_by_sign([]) == ([], [], [])",
        ),
    ],
    "list_functions": [
        E(
            "report_core_list_statistics",
            "리스트 기본 통계",
            "def list_stats(values: list[int]) -> dict[str, int]:",
            "비어 있지 않은 values에 대해 len, min, max, sum 결과를 해당 이름의 키로 반환한다.",
            "여러 리스트 내장 함수를 하나의 명확한 결과 구조에 담는다.",
            "list_stats([2, 5]) == {'len': 2, 'min': 2, 'max': 5, 'sum': 7}",
            "list_stats([-3, 0, 4]) == {'len': 3, 'min': -3, 'max': 4, 'sum': 1}",
            "list_stats([7]) == {'len': 1, 'min': 7, 'max': 7, 'sum': 7}",
        ),
        E(
            "find_smallest_or_none",
            "최솟값 또는 None",
            "def smallest_or_none(values: list[int]) -> int | None:",
            "values가 비어 있으면 None을, 아니면 min 결과를 반환한다.",
            "min을 호출하기 전에 빈 리스트를 처리한다.",
            "smallest_or_none([4, 1, 7]) == 1",
            "smallest_or_none([-2, -5]) == -5",
            "smallest_or_none([]) is None",
        ),
        E(
            "find_largest_or_none",
            "최댓값 또는 None",
            "def largest_or_none(values: list[int]) -> int | None:",
            "values가 비어 있으면 None을, 아니면 max 결과를 반환한다.",
            "max가 요구하는 비어 있지 않은 입력 조건을 분기로 보장한다.",
            "largest_or_none([4, 1, 7]) == 7",
            "largest_or_none([-2, -5]) == -2",
            "largest_or_none([]) is None",
        ),
        E(
            "calculate_list_value_range",
            "최댓값과 최솟값의 차이",
            "def list_value_range(values: list[int]) -> int:",
            "비어 있지 않은 values의 max(values) - min(values)를 반환한다.",
            "최댓값과 최솟값 함수를 결합해 산포 범위를 구한다.",
            "list_value_range([2, 8, 5]) == 6",
            "list_value_range([-3, 4]) == 7",
            "list_value_range([9]) == 0",
        ),
        E(
            "sort_list_without_mutation",
            "정렬된 새 리스트",
            "def sorted_list_copy(values: list[int], descending: bool = False) -> list[int]:",
            "values를 변경하지 않고 오름차순 또는 descending이 참이면 내림차순으로 정렬된 새 리스트를 반환한다.",
            "sorted의 새 리스트 반환과 reverse 인자를 사용한다.",
            "((items := [3, 1, 2]), sorted_list_copy(items) == [1, 2, 3] and items == [3, 1, 2])[-1] is True",
            "sorted_list_copy([3, 1, 2], True) == [3, 2, 1]",
            "sorted_list_copy([]) == []",
        ),
        E(
            "reverse_list_without_mutation",
            "역순 복사 리스트",
            "def reversed_list_copy(values: list[int]) -> list[int]:",
            "values의 원소 순서를 뒤집은 새 리스트를 반환하고 원본은 변경하지 않는다.",
            "reversed 결과를 list로 변환하거나 역순 슬라이스를 사용한다.",
            "((items := [1, 2, 3]), reversed_list_copy(items) == [3, 2, 1] and items == [1, 2, 3])[-1] is True",
            "reversed_list_copy([7]) == [7]",
            "reversed_list_copy([]) == []",
        ),
        E(
            "count_list_occurrences",
            "리스트에서 값 개수 세기",
            "def occurrence_count(values: list[object], target: object) -> int:",
            "values에서 target과 같은 원소의 개수를 반환한다.",
            "list.count의 동등성 비교 동작을 사용한다.",
            "occurrence_count(['a', 'b', 'a'], 'a') == 2",
            "occurrence_count([1, 2, 3], 9) == 0",
            "occurrence_count([], None) == 0",
        ),
        E(
            "check_all_nonnegative",
            "모두 0 이상인지 확인하기",
            "def all_nonnegative(values: list[int]) -> bool:",
            "모든 원소가 0 이상이면 True를 반환하며 빈 리스트도 True로 본다.",
            "all에 원소별 비교 generator를 전달한다.",
            "all_nonnegative([0, 2, 5]) is True",
            "all_nonnegative([1, -1, 3]) is False",
            "all_nonnegative([]) is True",
        ),
        E(
            "check_any_duplicate_value",
            "중복 원소 존재 확인하기",
            "def has_duplicate_value(values: list[int]) -> bool:",
            "같은 정수가 두 번 이상 나타나면 True를 반환한다.",
            "전체 길이와 set으로 만든 고유 원소 수를 비교한다.",
            "has_duplicate_value([1, 2, 1]) is True",
            "has_duplicate_value([1, 2, 3]) is False",
            "has_duplicate_value([]) is False",
        ),
        E(
            "enumerate_list_values",
            "인덱스와 원소 묶기",
            "def enumerate_values(values: list[str], start: int = 0) -> list[tuple[int, str]]:",
            "enumerate의 start 값을 적용해 각 문자열을 번호와 묶은 리스트로 반환한다.",
            "enumerate 객체를 구체적인 tuple 리스트로 변환한다.",
            "enumerate_values(['a', 'b']) == [(0, 'a'), (1, 'b')]",
            "enumerate_values(['x', 'y'], 1) == [(1, 'x'), (2, 'y')]",
            "enumerate_values([], 5) == []",
        ),
    ],
    "list_append": [
        E(
            "append_missing_value_copy",
            "없는 값만 복사본에 추가하기",
            "def append_if_missing(values: list[int], value: int) -> list[int]:",
            "value가 values에 없을 때만 복사본 끝에 추가하고 원본은 변경하지 않는다.",
            "membership 검사 후 복사본에 append하는 조건부 갱신을 연습한다.",
            "((items := [1, 2]), append_if_missing(items, 3) == [1, 2, 3] and items == [1, 2])[-1] is True",
            "append_if_missing([1, 2], 2) == [1, 2]",
            "append_if_missing([], 5) == [5]",
        ),
        E(
            "append_value_in_place",
            "원본 리스트 끝에 직접 추가하기",
            "def append_value_in_place(values: list[int], value: int) -> None:",
            "values 자체의 끝에 value를 한 번 append하고 None을 반환한다.",
            "반환용 복사본을 만들지 않는 제자리 변경과 None 반환을 구분한다.",
            "((items := [1, 2]), append_value_in_place(items, 3) is None and items == [1, 2, 3])[-1] is True",
            "((items := []), append_value_in_place(items, 0) is None and items == [0])[-1] is True",
            "((items := [5]), append_value_in_place(items, 5) is None and items == [5, 5])[-1] is True",
        ),
        E(
            "append_multiple_values_copy",
            "여러 값을 하나씩 추가하기",
            "def append_many(values: list[int], additions: list[int]) -> list[int]:",
            "values의 복사본에 additions의 각 원소를 append해 반환하고 두 입력 리스트는 변경하지 않는다.",
            "extend 대신 반복문과 append로 여러 원소를 추가한다.",
            "((items := [1]), (extras := [2, 3]), append_many(items, extras) == [1, 2, 3] and items == [1] and extras == [2, 3])[-1] is True",
            "append_many([], [4]) == [4]",
            "append_many([1, 2], []) == [1, 2]",
        ),
        E(
            "append_squares_to_new_list",
            "제곱값을 차례로 추가하기",
            "def append_squares(values: list[int]) -> list[int]:",
            "빈 결과 리스트에서 시작해 values 각 원소의 제곱을 append하여 반환한다.",
            "원소 변환과 append를 반복해 결과 리스트를 구축한다.",
            "append_squares([1, 2, 3]) == [1, 4, 9]",
            "append_squares([-2, 0]) == [4, 0]",
            "append_squares([]) == []",
        ),
        E(
            "append_nonempty_strings",
            "빈 문자열은 추가하지 않기",
            "def collect_nonempty_strings(values: list[str]) -> list[str]:",
            "values를 순회하며 빈 문자열이 아닌 원소만 새 리스트에 append한다.",
            "조건을 통과한 원소만 결과에 추가한다.",
            "collect_nonempty_strings(['a', '', 'b']) == ['a', 'b']",
            "collect_nonempty_strings(['', '']) == []",
            "collect_nonempty_strings([]) == []",
        ),
        E(
            "build_list_with_repeated_append",
            "append로 반복 리스트 만들기",
            "def build_repeated_list(value: int, count: int) -> list[int]:",
            "count가 0 이상이라고 가정하고 리스트 곱셈 없이 value를 count번 append한 리스트를 반환한다.",
            "반복 횟수만큼 append하여 리스트 크기가 변하는 과정을 익힌다.",
            "build_repeated_list(7, 3) == [7, 7, 7]",
            "build_repeated_list(-1, 1) == [-1]",
            "build_repeated_list(0, 0) == []",
        ),
        E(
            "append_unique_values_in_order",
            "처음 본 값만 추가하기",
            "def append_unique_values(values: list[int]) -> list[int]:",
            "values를 순회하며 결과 리스트에 아직 없는 정수만 append해 최초 등장 순서를 보존한다.",
            "결과 리스트 membership 검사와 append를 조합한다.",
            "append_unique_values([2, 1, 2, 3, 1]) == [2, 1, 3]",
            "append_unique_values([5, 5, 5]) == [5]",
            "append_unique_values([]) == []",
        ),
        E(
            "append_index_value_pairs",
            "인덱스·값 쌍 추가하기",
            "def append_index_pairs(values: list[str]) -> list[tuple[int, str]]:",
            "각 문자열을 0부터 시작하는 인덱스와 tuple로 묶어 결과 리스트에 append한다.",
            "enumerate로 얻은 복합 값을 리스트 끝에 순서대로 쌓는다.",
            "append_index_pairs(['a', 'b']) == [(0, 'a'), (1, 'b')]",
            "append_index_pairs(['x']) == [(0, 'x')]",
            "append_index_pairs([]) == []",
        ),
        E(
            "append_running_totals",
            "누적 합을 append하기",
            "def append_running_totals(values: list[int]) -> list[int]:",
            "values를 순회하며 현재까지의 합계를 계산해 매 단계 결과 리스트 끝에 추가한다.",
            "상태 갱신 순서와 append 시점을 정확히 맞춘다.",
            "append_running_totals([1, 2, 3]) == [1, 3, 6]",
            "append_running_totals([5, -2]) == [5, 3]",
            "append_running_totals([]) == []",
        ),
        E(
            "append_separator_items",
            "원소 사이에 구분값 추가하기",
            "def intersperse_items(values: list[int], separator: int) -> list[int]:",
            "values의 원소 사이에만 separator를 append한 새 리스트를 반환한다.",
            "첫 원소 전과 마지막 원소 뒤에는 구분값을 넣지 않는 append 순서를 설계한다.",
            "intersperse_items([1, 2, 3], 0) == [1, 0, 2, 0, 3]",
            "intersperse_items([5], 9) == [5]",
            "intersperse_items([], 1) == []",
        ),
    ],
    "list_pop": [
        E(
            "pop_last_item_copy",
            "복사본의 마지막 원소 꺼내기",
            "def pop_last(values: list[int]) -> tuple[list[int], int | None]:",
            "values는 변경하지 않고, 복사본과 거기서 pop한 마지막 값을 반환하며 빈 리스트면 ([], None)을 반환한다.",
            "복사 후 pop의 반환값과 변경된 복사본을 함께 다룬다.",
            "((items := [1, 2]), pop_last(items) == ([1], 2) and items == [1, 2])[-1] is True",
            "pop_last([7]) == ([], 7)",
            "pop_last([]) == ([], None)",
        ),
        E(
            "pop_first_item_copy",
            "복사본의 첫 원소 꺼내기",
            "def pop_first(values: list[int]) -> tuple[list[int], int | None]:",
            "values는 변경하지 않고 복사본의 첫 원소를 pop해 (남은 리스트, 제거값)으로 반환하며 빈 리스트는 ([], None)이다.",
            "pop(0)의 결과와 복사본 상태를 함께 반환한다.",
            "((items := [1, 2, 3]), pop_first(items) == ([2, 3], 1) and items == [1, 2, 3])[-1] is True",
            "pop_first([8]) == ([], 8)",
            "pop_first([]) == ([], None)",
        ),
        E(
            "pop_index_item_copy",
            "지정 위치 원소 꺼내기",
            "def pop_at_index(values: list[int], index: int) -> tuple[list[int], int | None]:",
            "index가 유효하면 복사본에서 해당 원소를 pop해 남은 리스트와 제거값을 반환하고, 유효하지 않으면 복사본과 None을 반환한다.",
            "양수·음수 인덱스의 유효 범위를 확인한 뒤 pop(index)를 호출한다.",
            "((items := [10, 20, 30]), pop_at_index(items, 1) == ([10, 30], 20) and items == [10, 20, 30])[-1] is True",
            "pop_at_index([1, 2], -1) == ([1], 2)",
            "pop_at_index([1, 2], 5) == ([1, 2], None)",
        ),
        E(
            "pop_both_list_ends",
            "양 끝 원소 꺼내기",
            "def pop_both_ends(values: list[int]) -> tuple[list[int], tuple[int, int] | None]:",
            "원소가 두 개 이상이면 복사본의 첫 값과 마지막 값을 제거해 (남은 리스트, (첫 값, 마지막 값))을 반환하고 아니면 (복사본, None)을 반환한다.",
            "두 번의 pop에서 인덱스 이동과 제거 순서를 고려한다.",
            "((items := [1, 2, 3, 4]), pop_both_ends(items) == ([2, 3], (1, 4)) and items == [1, 2, 3, 4])[-1] is True",
            "pop_both_ends([1, 2]) == ([], (1, 2))",
            "pop_both_ends([1]) == ([1], None)",
        ),
        E(
            "pop_multiple_last_items",
            "마지막 원소 여러 개 꺼내기",
            "def pop_last_n(values: list[int], count: int) -> tuple[list[int], list[int]]:",
            "0 <= count <= len(values)라고 가정해 복사본에서 마지막 원소를 count번 pop하고, 제거값들은 실제 pop된 순서로 반환한다.",
            "반복되는 pop이 뒤에서 앞으로 값을 꺼내는 순서를 확인한다.",
            "((items := [1, 2, 3, 4]), pop_last_n(items, 2) == ([1, 2], [4, 3]) and items == [1, 2, 3, 4])[-1] is True",
            "pop_last_n([5], 1) == ([], [5])",
            "pop_last_n([1, 2], 0) == ([1, 2], [])",
        ),
        E(
            "pop_until_top_value",
            "맨 위가 목표값일 때까지 꺼내기",
            "def pop_until_top(values: list[int], target: int) -> tuple[list[int], list[int]]:",
            "복사본의 마지막 값이 target이거나 리스트가 빌 때까지 pop하고, 제거값을 pop된 순서로 함께 반환한다.",
            "스택의 top을 반복 검사하며 조건이 충족될 때 루프를 멈춘다.",
            "((items := [1, 2, 3, 4]), pop_until_top(items, 2) == ([1, 2], [4, 3]) and items == [1, 2, 3, 4])[-1] is True",
            "pop_until_top([1, 2], 9) == ([], [2, 1])",
            "pop_until_top([], 1) == ([], [])",
        ),
        E(
            "unwind_stack_copy",
            "스택을 모두 꺼낸 순서",
            "def unwind_stack(values: list[str]) -> list[str]:",
            "values를 변경하지 않고 복사본이 빌 때까지 pop한 값들을 순서대로 반환한다.",
            "후입선출 순서를 반복되는 pop 결과로 관찰한다.",
            "((items := ['a', 'b', 'c']), unwind_stack(items) == ['c', 'b', 'a'] and items == ['a', 'b', 'c'])[-1] is True",
            "unwind_stack(['x']) == ['x']",
            "unwind_stack([]) == []",
        ),
        E(
            "pop_last_matching_value",
            "마지막으로 등장한 목표값 꺼내기",
            "def pop_last_occurrence(values: list[int], target: int) -> tuple[list[int], int | None]:",
            "target의 마지막 등장 위치를 복사본에서 pop해 반환하고, 없으면 복사본과 None을 반환한다.",
            "뒤쪽부터 위치를 찾은 뒤 pop(index)로 한 원소만 제거한다.",
            "((items := [1, 2, 1, 3]), pop_last_occurrence(items, 1) == ([1, 2, 3], 1) and items == [1, 2, 1, 3])[-1] is True",
            "pop_last_occurrence([4, 5], 9) == ([4, 5], None)",
            "pop_last_occurrence([], 1) == ([], None)",
        ),
        E(
            "pop_alternating_from_end",
            "뒤에서 하나씩 교대로 분배하기",
            "def deal_from_stack(values: list[int]) -> tuple[list[int], list[int]]:",
            "복사본이 빌 때까지 pop하면서 첫 제거값은 left, 다음은 right에 번갈아 append해 두 리스트를 반환한다.",
            "스택 제거 순서와 차례 상태를 함께 관리한다.",
            "((items := [1, 2, 3, 4]), deal_from_stack(items) == ([4, 2], [3, 1]) and items == [1, 2, 3, 4])[-1] is True",
            "deal_from_stack([1, 2, 3]) == ([3, 1], [2])",
            "deal_from_stack([]) == ([], [])",
        ),
        E(
            "undo_recent_actions_copy",
            "최근 작업 되돌리기",
            "def undo_recent_actions(actions: list[str], count: int) -> tuple[list[str], list[str]]:",
            "count가 0 이상이라고 가정해 최대 count개의 최근 작업을 복사본에서 pop하고, 남은 작업과 취소된 작업의 pop 순서를 반환한다.",
            "요청 횟수가 리스트 길이보다 큰 경우에도 빈 스택을 안전하게 처리한다.",
            "((items := ['open', 'edit', 'save']), undo_recent_actions(items, 2) == (['open'], ['save', 'edit']) and items == ['open', 'edit', 'save'])[-1] is True",
            "undo_recent_actions(['open'], 5) == ([], ['open'])",
            "undo_recent_actions([], 3) == ([], [])",
        ),
    ],
    "list_find": [
        E(
            "find_first_value_index",
            "첫 일치 인덱스 찾기",
            "def find_index(values: list[object], target: object) -> int:",
            "target과 같은 첫 원소의 인덱스를 반환하고 없으면 -1을 반환한다.",
            "왼쪽부터 검색하며 첫 일치 즉시 위치를 반환한다.",
            "find_index(['a', 'b'], 'b') == 1",
            "find_index([1, 2, 1], 1) == 0",
            "find_index([], 'x') == -1",
        ),
        E(
            "find_last_value_index",
            "마지막 일치 인덱스 찾기",
            "def find_last_index(values: list[object], target: object) -> int:",
            "target과 같은 마지막 원소의 인덱스를 반환하고 없으면 -1을 반환한다.",
            "뒤에서 검색하되 원래 리스트의 인덱스를 정확히 반환한다.",
            "find_last_index(['a', 'b', 'a'], 'a') == 2",
            "find_last_index([1, 2, 3], 2) == 1",
            "find_last_index([], None) == -1",
        ),
        E(
            "find_all_value_indices",
            "모든 일치 위치 찾기",
            "def find_all_indices(values: list[object], target: object) -> list[int]:",
            "target과 같은 모든 원소의 인덱스를 왼쪽부터 반환한다.",
            "enumerate 순회 중 여러 일치 위치를 수집한다.",
            "find_all_indices(['a', 'b', 'a'], 'a') == [0, 2]",
            "find_all_indices([1, 2], 9) == []",
            "find_all_indices([], None) == []",
        ),
        E(
            "check_value_membership",
            "목표값 포함 여부",
            "def list_contains(values: list[object], target: object) -> bool:",
            "target과 같은 원소가 values에 하나라도 있으면 True를 반환한다.",
            "리스트 membership 연산으로 존재 여부를 표현한다.",
            "list_contains(['a', 'b'], 'b') is True",
            "list_contains([1, 2], 3) is False",
            "list_contains([], None) is False",
        ),
        E(
            "find_first_even_value",
            "첫 짝수 값 찾기",
            "def first_even_value(values: list[int]) -> int | None:",
            "왼쪽부터 처음 만나는 짝수를 반환하고 없으면 None을 반환한다.",
            "값 조건을 만족하는 첫 원소에서 검색을 종료한다.",
            "first_even_value([1, 5, 4, 2]) == 4",
            "first_even_value([1, 3]) is None",
            "first_even_value([0]) == 0",
        ),
        E(
            "find_first_value_above_threshold",
            "기준 초과 첫 위치",
            "def first_index_above(values: list[int], threshold: int) -> int:",
            "threshold보다 큰 첫 원소의 인덱스를 반환하고 없으면 -1을 반환한다.",
            "검색 조건이 값이 아니라 비교식인 경우의 선형 탐색을 연습한다.",
            "first_index_above([1, 7, 9], 5) == 1",
            "first_index_above([5, 5], 5) == -1",
            "first_index_above([], 0) == -1",
        ),
        E(
            "find_contiguous_sublist_start",
            "연속 부분 리스트 시작 위치",
            "def find_sublist_start(values: list[int], pattern: list[int]) -> int:",
            "pattern이 values에 연속으로 처음 등장하는 시작 인덱스를 반환하며, 빈 pattern은 0, 없으면 -1을 반환한다.",
            "가능한 시작 위치마다 같은 길이의 슬라이스를 비교한다.",
            "find_sublist_start([1, 2, 3, 2, 3], [2, 3]) == 1",
            "find_sublist_start([1, 2], [3]) == -1",
            "find_sublist_start([1, 2], []) == 0",
        ),
        E(
            "find_nearest_numeric_index",
            "목표에 가장 가까운 값의 위치",
            "def nearest_value_index(values: list[int], target: int) -> int:",
            "비어 있지 않은 values에서 target과 절댓값 차이가 가장 작은 원소의 인덱스를 반환하며 동률이면 앞 인덱스를 선택한다.",
            "현재 최선의 차이와 인덱스를 갱신하는 검색을 구현한다.",
            "nearest_value_index([1, 6, 10], 8) == 1",
            "nearest_value_index([2, 4], 3) == 0",
            "nearest_value_index([-5], 100) == 0",
        ),
        E(
            "find_first_duplicate_value",
            "처음 중복이 확인되는 값",
            "def first_duplicate_value(values: list[int]) -> int | None:",
            "왼쪽부터 읽을 때 이전에 이미 등장한 첫 값을 반환하고 끝까지 중복이 없으면 None을 반환한다.",
            "검색 과정에서 이미 본 값들을 별도로 추적한다.",
            "first_duplicate_value([2, 1, 3, 1, 2]) == 1",
            "first_duplicate_value([1, 2, 3]) is None",
            "first_duplicate_value([5, 5]) == 5",
        ),
        E(
            "find_first_string_prefix",
            "접두사가 맞는 첫 문자열",
            "def first_string_with_prefix(values: list[str], prefix: str) -> str | None:",
            "prefix로 시작하는 첫 문자열을 반환하고 없으면 None을 반환한다.",
            "리스트 선형 탐색과 str.startswith 조건을 결합한다.",
            "first_string_with_prefix(['cat', 'car', 'dog'], 'ca') == 'cat'",
            "first_string_with_prefix(['apple', 'banana'], 'z') is None",
            "first_string_with_prefix(['', 'a'], '') == ''",
        ),
    ],
    "list_slicing": [
        E(
            "take_middle_list_slice",
            "양 끝을 제외한 리스트",
            "def middle_slice(values: list[int]) -> list[int]:",
            "첫 원소와 마지막 원소를 제외한 새 리스트를 반환하며 길이가 2 이하면 []를 반환한다.",
            "리스트의 반열린 슬라이스와 짧은 입력 결과를 익힌다.",
            "middle_slice([1, 2, 3, 4]) == [2, 3]",
            "middle_slice([1, 2]) == []",
            "middle_slice([]) == []",
        ),
        E(
            "take_first_list_items",
            "앞에서 n개 복사하기",
            "def first_list_items(values: list[int], count: int) -> list[int]:",
            "count가 0 이상이라고 가정해 앞 count개 원소의 새 리스트를 반환한다.",
            "범위를 넘는 끝 인덱스도 안전한 리스트 슬라이싱을 사용한다.",
            "first_list_items([1, 2, 3], 2) == [1, 2]",
            "first_list_items([1, 2], 5) == [1, 2]",
            "first_list_items([1], 0) == []",
        ),
        E(
            "take_last_list_items",
            "뒤에서 n개 복사하기",
            "def last_list_items(values: list[int], count: int) -> list[int]:",
            "count가 0 이상이라고 가정해 뒤 count개 원소를 반환하되 count가 0이면 []를 반환한다.",
            "음수 시작 인덱스와 -0 슬라이스의 특수성을 구분한다.",
            "last_list_items([1, 2, 3], 2) == [2, 3]",
            "last_list_items([1, 2], 5) == [1, 2]",
            "last_list_items([1], 0) == []",
        ),
        E(
            "slice_list_between_bounds",
            "두 경계 사이 복사하기",
            "def list_slice_between(values: list[int], start: int, stop: int) -> list[int]:",
            "Python의 values[start:stop]과 같은 새 리스트를 반환한다.",
            "양수·음수·범위 밖 슬라이스 경계를 그대로 활용한다.",
            "list_slice_between([0, 1, 2, 3], 1, 3) == [1, 2]",
            "list_slice_between([1, 2, 3], -2, 3) == [2, 3]",
            "list_slice_between([1, 2], 5, 9) == []",
        ),
        E(
            "take_every_nth_list_item",
            "일정 간격으로 원소 고르기",
            "def every_nth_list_item(values: list[int], step: int) -> list[int]:",
            "step이 양수라고 가정해 0번 인덱스부터 step 간격의 원소를 반환한다.",
            "리스트 슬라이스의 보폭을 매개변수로 적용한다.",
            "every_nth_list_item([0, 1, 2, 3, 4], 2) == [0, 2, 4]",
            "every_nth_list_item([1, 2, 3, 4], 3) == [1, 4]",
            "every_nth_list_item([], 2) == []",
        ),
        E(
            "split_list_into_halves",
            "리스트를 절반으로 나누기",
            "def split_list_halves(values: list[int]) -> tuple[list[int], list[int]]:",
            "len(values) // 2를 경계로 두 새 리스트를 반환하며 홀수 길이의 가운데 원소는 오른쪽에 포함한다.",
            "계산한 중간 인덱스로 서로 겹치지 않는 두 슬라이스를 만든다.",
            "split_list_halves([1, 2, 3, 4]) == ([1, 2], [3, 4])",
            "split_list_halves([1, 2, 3]) == ([1], [2, 3])",
            "split_list_halves([]) == ([], [])",
        ),
        E(
            "chunk_list_by_size",
            "일정 크기 조각으로 나누기",
            "def chunk_list(values: list[int], size: int) -> list[list[int]]:",
            "size가 양수라고 가정해 values를 최대 size개씩의 연속된 새 리스트들로 나눈다.",
            "range의 step과 리스트 슬라이스를 조합해 마지막 짧은 조각까지 처리한다.",
            "chunk_list([1, 2, 3, 4, 5], 2) == [[1, 2], [3, 4], [5]]",
            "chunk_list([1, 2], 5) == [[1, 2]]",
            "chunk_list([], 3) == []",
        ),
        E(
            "rotate_list_right_by_slicing",
            "리스트 오른쪽 회전하기",
            "def rotate_list_right(values: list[int], amount: int) -> list[int]:",
            "빈 리스트는 []를 반환하고, 아니면 amount를 길이로 나눈 나머지만큼 오른쪽으로 회전한 새 리스트를 반환한다.",
            "뒤쪽과 앞쪽 슬라이스의 결합 순서를 바꿔 회전한다.",
            "rotate_list_right([1, 2, 3, 4], 1) == [4, 1, 2, 3]",
            "rotate_list_right([1, 2, 3], 4) == [3, 1, 2]",
            "rotate_list_right([], 2) == []",
        ),
        E(
            "remove_list_slice_copy",
            "선택 구간을 제외한 리스트",
            "def remove_list_slice(values: list[int], start: int, stop: int) -> list[int]:",
            "0 <= start <= stop <= len(values)라고 가정해 values[start:stop]을 제외한 새 리스트를 반환한다.",
            "선택 구간 양옆의 슬라이스를 더해 원본을 보존한다.",
            "remove_list_slice([1, 2, 3, 4], 1, 3) == [1, 4]",
            "remove_list_slice([1, 2], 0, 2) == []",
            "remove_list_slice([1, 2], 1, 1) == [1, 2]",
        ),
        E(
            "replace_list_range_with_copy",
            "슬라이스를 다른 값들로 바꾸기",
            "def splice_list(values: list[int], start: int, stop: int, replacement: list[int]) -> list[int]:",
            "0 <= start <= stop <= len(values)라고 가정해 해당 구간 대신 replacement가 들어간 새 리스트를 반환한다.",
            "앞 슬라이스, replacement, 뒤 슬라이스를 결합해 길이 변화도 처리한다.",
            "splice_list([1, 2, 3, 4], 1, 3, [8, 9]) == [1, 8, 9, 4]",
            "splice_list([1, 2], 1, 1, [7]) == [1, 7, 2]",
            "splice_list([1, 2, 3], 0, 3, []) == []",
        ),
    ],
    "tuples": [
        E(
            "swap_tuple_pair",
            "tuple 두 원소 맞바꾸기",
            "def swap_pair(pair: tuple[object, object]) -> tuple[object, object]:",
            "두 원소 tuple을 언패킹해 순서를 바꾼 새 tuple을 반환한다.",
            "고정 길이 tuple 언패킹과 tuple 반환을 연습한다.",
            "swap_pair(('a', 1)) == (1, 'a')",
            "swap_pair((True, None)) == (None, True)",
            "swap_pair(((1, 2), 'x')) == ('x', (1, 2))",
        ),
        E(
            "make_coordinate_tuple",
            "좌표 tuple 만들기",
            "def make_coordinate(x: float, y: float) -> tuple[float, float]:",
            "x와 y를 그 순서로 담은 2차원 좌표 tuple을 반환한다.",
            "쉼표로 고정된 구조의 불변 tuple을 생성한다.",
            "make_coordinate(1.5, 2.0) == (1.5, 2.0)",
            "make_coordinate(-1, 0) == (-1, 0)",
            "make_coordinate(0.0, 0.0) == (0.0, 0.0)",
        ),
        E(
            "unpack_profile_tuple",
            "프로필 tuple 풀어 쓰기",
            "def profile_sentence(profile: tuple[str, int]) -> str:",
            "(name, age)를 언패킹해 '<name> is <age>' 형식의 문자열을 반환한다.",
            "tuple 원소를 의미 있는 지역 변수로 언패킹한다.",
            "profile_sentence(('Ada', 36)) == 'Ada is 36'",
            "profile_sentence(('Kim', 0)) == 'Kim is 0'",
            "profile_sentence(('', 5)) == ' is 5'",
        ),
        E(
            "sum_numeric_tuple",
            "숫자 tuple 합계",
            "def tuple_total(values: tuple[int, ...]) -> int:",
            "길이에 제한이 없는 정수 tuple의 모든 원소 합을 반환한다.",
            "가변 길이 tuple 타입 힌트와 iterable로서의 tuple을 익힌다.",
            "tuple_total((1, 2, 3)) == 6",
            "tuple_total((-2, 2)) == 0",
            "tuple_total(()) == 0",
        ),
        E(
            "convert_tuple_to_list",
            "tuple을 리스트로 변환하기",
            "def tuple_as_list(values: tuple[int, ...]) -> list[int]:",
            "values와 같은 순서의 원소를 가진 새 리스트를 반환한다.",
            "불변 tuple에서 변경 가능한 list로 컨테이너 타입을 변환한다.",
            "tuple_as_list((1, 2, 3)) == [1, 2, 3]",
            "tuple_as_list((7,)) == [7]",
            "tuple_as_list(()) == []",
        ),
        E(
            "convert_list_to_tuple",
            "리스트를 tuple로 변환하기",
            "def list_as_tuple(values: list[str]) -> tuple[str, ...]:",
            "values와 같은 순서의 원소를 가진 새 tuple을 반환한다.",
            "변경 가능한 list를 불변 tuple로 변환한다.",
            "list_as_tuple(['a', 'b']) == ('a', 'b')",
            "list_as_tuple(['x']) == ('x',)",
            "list_as_tuple([]) == ()",
        ),
        E(
            "pair_adjacent_values_as_tuples",
            "인접 원소를 tuple로 묶기",
            "def adjacent_tuples(values: list[int]) -> list[tuple[int, int]]:",
            "서로 이웃한 원소 쌍을 왼쪽부터 tuple로 만들어 반환한다.",
            "리스트의 관련된 두 값을 고정 길이 tuple로 표현한다.",
            "adjacent_tuples([1, 2, 3]) == [(1, 2), (2, 3)]",
            "adjacent_tuples([5]) == []",
            "adjacent_tuples([]) == []",
        ),
        E(
            "find_tuple_extremes",
            "tuple의 최솟값과 최댓값",
            "def tuple_extremes(values: tuple[int, ...]) -> tuple[int, int] | None:",
            "values가 비어 있으면 None을, 아니면 (최솟값, 최댓값) tuple을 반환한다.",
            "입력 tuple을 읽어 요약 결과를 새로운 고정 길이 tuple로 만든다.",
            "tuple_extremes((3, 1, 8)) == (1, 8)",
            "tuple_extremes((-2, -5)) == (-5, -2)",
            "tuple_extremes(()) is None",
        ),
        E(
            "update_tuple_index_copy",
            "tuple 한 원소 교체하기",
            "def update_tuple_at(values: tuple[int, ...], index: int, value: int) -> tuple[int, ...]:",
            "index가 유효하다고 가정해 해당 위치만 value로 교체한 새 tuple을 반환한다.",
            "tuple은 직접 수정할 수 없으므로 슬라이스와 단일 원소 tuple을 결합한다.",
            "update_tuple_at((1, 2, 3), 1, 9) == (1, 9, 3)",
            "update_tuple_at((5,), 0, 7) == (7,)",
            "update_tuple_at((1, 2, 3), -1, 0) == (1, 2, 0)",
        ),
        E(
            "flatten_pairs_to_tuple",
            "tuple 쌍들을 하나로 펼치기",
            "def flatten_tuple_pairs(pairs: list[tuple[int, int]]) -> tuple[int, ...]:",
            "pairs의 각 두 원소를 순서대로 이어 하나의 tuple로 반환한다.",
            "중첩된 고정 길이 tuple을 읽어 가변 길이 tuple 결과를 구축한다.",
            "flatten_tuple_pairs([(1, 2), (3, 4)]) == (1, 2, 3, 4)",
            "flatten_tuple_pairs([(5, 6)]) == (5, 6)",
            "flatten_tuple_pairs([]) == ()",
        ),
    ],
}
