from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ChallengeTemplate:
    slug: str
    title: str
    signature_suffix: str
    task: str
    focus: str
    tests: tuple[str, str, str]
    source_checks: tuple[str, ...] = ()
    time_cap: int = 240


def T(
    slug: str,
    title: str,
    signature_suffix: str,
    task: str,
    focus: str,
    test_1: str,
    test_2: str,
    test_3: str,
    *source_checks: str,
    time_cap: int = 240,
) -> ChallengeTemplate:
    return ChallengeTemplate(
        slug=slug,
        title=title,
        signature_suffix=signature_suffix,
        task=task,
        focus=focus,
        tests=(test_1, test_2, test_3),
        source_checks=source_checks,
        time_cap=time_cap,
    )


SORTING = (
    T(
        "edge_values",
        "경계값 정렬",
        "(values: list[int]) -> list[int]:",
        "빈 리스트·중복·음수를 포함한 정수를 오름차순 새 리스트로 반환하세요.",
        "정렬의 기본 계약과 경계 입력",
        "__FN__([]) == []",
        "__FN__([4]) == [4]",
        "__FN__([3, -1, 3, 0]) == [-1, 0, 3, 3]",
        "sorted_call",
        time_cap=180,
    ),
    T(
        "preserve_input",
        "원본 보존 정렬",
        "(values: list[int]) -> tuple[list[int], list[int]]:",
        "정렬한 새 리스트와 호출 전 원본 내용의 복사본을 함께 반환하고 입력은 수정하지 마세요.",
        "sorted와 입력 불변성",
        "__FN__([3, 1, 2]) == ([1, 2, 3], [3, 1, 2])",
        "__FN__([]) == ([], [])",
        "((data := [2, 1]), __FN__(data), data) == ([2, 1], ([1, 2], [2, 1]), [2, 1])",
        "sorted_call",
    ),
    T(
        "stable_priorities",
        "안정적인 우선순위 정렬",
        "(records: list[tuple[int, str]]) -> list[tuple[int, str]]:",
        "(우선순위, 이름) 레코드를 우선순위만 기준으로 정렬해 동률의 입력 순서를 보존하세요.",
        "Python 정렬의 stability",
        "__FN__([(2, 'b'), (1, 'x'), (2, 'a')]) == [(1, 'x'), (2, 'b'), (2, 'a')]",
        "__FN__([]) == []",
        "__FN__([(1, 'z'), (1, 'a')]) == [(1, 'z'), (1, 'a')]",
        "sorted_call",
    ),
    T(
        "itemgetter_field",
        "itemgetter 필드 정렬",
        "(records: list[dict[str, object]], field: str) -> list[dict[str, object]]:",
        "operator.itemgetter를 key로 사용해 딕셔너리 레코드를 field 값 오름차순으로 정렬하세요.",
        "operator.itemgetter와 레코드 정렬",
        "__FN__([{'n': 'b', 's': 2}, {'n': 'a', 's': 1}], 's') == [{'n': 'a', 's': 1}, {'n': 'b', 's': 2}]",
        "__FN__([], 'x') == []",
        "__FN__([{'x': 2}, {'x': -1}, {'x': 2}], 'x') == [{'x': -1}, {'x': 2}, {'x': 2}]",
        "sorted_call",
        "itemgetter_call",
    ),
    T(
        "lambda_word_key",
        "lambda 복합 key 정렬",
        "(words: list[str]) -> list[str]:",
        "lambda key로 단어를 길이 오름차순, 길이가 같으면 소문자 사전순으로 정렬하세요.",
        "lambda와 tuple key",
        "__FN__(['BB', 'a', 'Ab']) == ['a', 'Ab', 'BB']",
        "__FN__([]) == []",
        "__FN__(['bbb', 'A', 'cc']) == ['A', 'cc', 'bbb']",
        "sorted_call",
        "lambda",
    ),
    T(
        "score_ranking",
        "점수 순위 정렬",
        "(records: list[tuple[str, int]]) -> list[tuple[str, int]]:",
        "(이름, 점수)를 점수 내림차순, 동률이면 이름 오름차순으로 정렬하세요.",
        "내림차순 숫자와 오름차순 문자열의 복합 key",
        "__FN__([('B', 90), ('A', 90), ('C', 80)]) == [('A', 90), ('B', 90), ('C', 80)]",
        "__FN__([]) == []",
        "__FN__([('x', -1), ('y', 0)]) == [('y', 0), ('x', -1)]",
        "sorted_call",
    ),
    T(
        "descending_unique",
        "중복 제거 내림차순",
        "(values: list[int]) -> list[int]:",
        "중복을 제거한 뒤 값을 내림차순으로 반환하세요.",
        "set과 reverse 정렬",
        "__FN__([3, 1, 3, 2]) == [3, 2, 1]",
        "__FN__([]) == []",
        "__FN__([-1, 0, -1]) == [0, -1]",
        "sorted_call",
    ),
    T(
        "smallest_k",
        "작은 값 K개",
        "(values: list[int], k: int) -> list[int]:",
        "heapq를 사용해 가장 작은 값 k개를 오름차순으로 반환하세요. k가 범위를 넘으면 가능한 값만 반환합니다.",
        "heapq.nsmallest와 K 경계",
        "__FN__([5, 1, 4, 2], 2) == [1, 2]",
        "__FN__([2, 1], 0) == []",
        "__FN__([2, 1], 5) == [1, 2]",
        "heapq_call",
    ),
    T(
        "kth_smallest",
        "K번째 작은 값",
        "(values: list[int], k: int) -> int | None:",
        "k를 1부터 시작하는 순위로 해석해 k번째 작은 값을 반환하고 범위 밖이면 None을 반환하세요.",
        "순위 인덱스와 경계 검사",
        "__FN__([4, 1, 3, 2], 3) == 3",
        "__FN__([], 1) is None",
        "__FN__([1, 2], 0) is None",
        "sorted_call",
    ),
    T(
        "merge_sorted",
        "두 정렬열 병합",
        "(left: list[int], right: list[int]) -> list[int]:",
        "이미 오름차순인 두 리스트를 다시 전체 정렬하지 말고 두 포인터로 병합하세요.",
        "merge 단계와 선형 시간",
        "__FN__([1, 4], [2, 3]) == [1, 2, 3, 4]",
        "__FN__([], [1]) == [1]",
        "__FN__([-2, 2], [-1, 2]) == [-2, -1, 2, 2]",
        "while",
    ),
    T(
        "nearly_sorted_heap",
        "거의 정렬된 배열",
        "(values: list[int], distance: int) -> list[int]:",
        "각 값이 최종 위치에서 최대 distance만큼 떨어진 배열을 크기 distance+1 heap으로 정렬하세요.",
        "작은 heap을 이용한 O(n log k) 정렬",
        "__FN__([3, 1, 2, 5, 4], 2) == [1, 2, 3, 4, 5]",
        "__FN__([], 3) == []",
        "__FN__([2, 1], 1) == [1, 2]",
        "heapq_call",
    ),
    T(
        "frequency_order",
        "빈도 기반 정렬",
        "(values: list[int]) -> list[int]:",
        "값을 빈도 내림차순, 동률이면 값 오름차순으로 모든 발생 횟수만큼 정렬하세요.",
        "Counter와 복합 정렬 key",
        "__FN__([2, 1, 2, 3, 1, 2]) == [2, 2, 2, 1, 1, 3]",
        "__FN__([]) == []",
        "__FN__([3, 2, 1]) == [1, 2, 3]",
        "counter_call",
        "sorted_call",
    ),
    T(
        "natural_codes",
        "자연스러운 코드 정렬",
        "(codes: list[str]) -> list[str]:",
        "re로 각 문자열의 마지막 연속 숫자를 추출해 숫자 오름차순, 동률이면 문자열순으로 정렬하세요. 숫자가 없으면 0입니다.",
        "정규표현식 추출과 자연 정렬 key",
        "__FN__(['item10', 'item2', 'item1']) == ['item1', 'item2', 'item10']",
        "__FN__(['b', 'a']) == ['a', 'b']",
        "__FN__([]) == []",
        "re_call",
        "sorted_call",
    ),
    T(
        "numeric_text",
        "숫자 문자열 정렬",
        "(texts: list[str]) -> list[str]:",
        "정수로 변환한 값을 기준으로 오름차순 정렬하되 같은 숫자는 입력 순서를 보존하세요.",
        "표현과 정렬 key 분리",
        "__FN__(['10', '2', '-1']) == ['-1', '2', '10']",
        "__FN__(['02', '2', '1']) == ['1', '02', '2']",
        "__FN__([]) == []",
        "sorted_call",
    ),
    T(
        "merge_batches",
        "여러 정렬 배치 병합",
        "(batches: list[list[int]]) -> list[int]:",
        "heapq.merge를 사용해 여러 오름차순 배치를 하나의 오름차순 리스트로 병합하세요.",
        "lazy K-way merge",
        "__FN__([[1, 4], [2, 3], [0, 5]]) == [0, 1, 2, 3, 4, 5]",
        "__FN__([]) == []",
        "__FN__([[], [1]]) == [1]",
        "heapq_call",
    ),
    T(
        "sort_contract",
        "sort 반환 계약",
        "(values: list[int]) -> dict[str, object]:",
        "입력의 사본에 list.sort()를 호출하고 {'values': 정렬된 사본, 'returned_none': 반환값이 None인지}를 반환하세요.",
        "in-place sort의 반환값",
        "__FN__([3, 1]) == {'values': [1, 3], 'returned_none': True}",
        "__FN__([]) == {'values': [], 'returned_none': True}",
        "((data := [2, 1]), __FN__(data), data) == ([2, 1], {'values': [1, 2], 'returned_none': True}, [2, 1])",
        "list_sort_call",
    ),
    T(
        "counting_sort",
        "범위 제한 계수 정렬",
        "(values: list[int], low: int, high: int) -> list[int]:",
        "모든 값이 low 이상 high 이하일 때 빈도 배열로 오름차순 결과를 만드세요.",
        "값 범위를 이용한 O(n + range) 정렬",
        "__FN__([3, 1, 2, 1], 1, 3) == [1, 1, 2, 3]",
        "__FN__([], 0, 0) == []",
        "__FN__([-1, 0, -1], -1, 0) == [-1, -1, 0]",
        "for",
    ),
    T(
        "insertion_sort",
        "삽입 정렬 구현",
        "(values: list[int]) -> list[int]:",
        "원본을 보존하며 삽입 정렬로 오름차순 새 리스트를 만드세요.",
        "직접 구현하는 안정 정렬",
        "__FN__([3, 1, 2]) == [1, 2, 3]",
        "__FN__([]) == []",
        "__FN__([2, 2, -1]) == [-1, 2, 2]",
        "for",
    ),
    T(
        "fraction_cmp",
        "분수 comparator 정렬",
        "(fractions: list[tuple[int, int]]) -> list[tuple[int, int]]:",
        "functools.cmp_to_key와 교차 곱 comparator로 양의 분모를 가진 분수를 값 오름차순 정렬하세요.",
        "부동소수점 변환 없는 comparator",
        "__FN__([(1, 2), (1, 3), (3, 4)]) == [(1, 3), (1, 2), (3, 4)]",
        "__FN__([]) == []",
        "__FN__([(2, 4), (1, 2)]) == [(2, 4), (1, 2)]",
        "cmp_to_key_call",
        "sorted_call",
        time_cap=300,
    ),
)


PYTHONIC = (
    T("swap_unpack", "두 값 unpacking", "(pair: tuple[int, int]) -> tuple[int, int, int]:", "tuple unpacking으로 두 값을 바꾸고 합계까지 반환하세요.", "대입 unpacking", "__FN__((2, 5)) == (5, 2, 7)", "__FN__((0, 0)) == (0, 0, 0)", "__FN__((-1, 3)) == (3, -1, 2)", "tuple_unpack", time_cap=180),
    T("consume_iterator", "iterator 한 번 소비", "(values: object) -> list[object]:", "iter()와 next()를 사용해 iterable을 한 번만 순회하여 리스트로 반환하세요. None도 정상 원소이므로 별도 sentinel로 종료를 구분하세요.", "iterator protocol과 sentinel", "__FN__([1, 2]) == [1, 2]", "__FN__(iter([])) == []", "__FN__([None, 1]) == [None, 1]", "iter_call", "next_call"),
    T("yield_even_squares", "짝수 제곱 generator", "(values: list[int]) -> object:", "짝수의 제곱을 입력 순서대로 yield하는 generator function을 작성하세요.", "yield와 lazy evaluation", "list(__FN__([1, 2, 4])) == [4, 16]", "list(__FN__([])) == []", "list(__FN__([-2, 3, 0])) == [4, 0]", "yield"),
    T("sum_products", "loop unpacking 곱합", "(pairs: list[tuple[int, int]]) -> int:", "for 문에서 각 pair를 직접 unpack해 곱의 합을 반환하세요.", "for target unpacking", "__FN__([(2, 3), (4, 5)]) == 26", "__FN__([]) == 0", "__FN__([(-1, 2)]) == -2", "for", "tuple_unpack"),
    T("indexed_labels", "enumerate 라벨", "(values: list[str], start: int = 0) -> list[str]:", "enumerate의 start를 사용해 '<index>:<value>' 라벨을 만드세요.", "enumerate 시작값", "__FN__(['a', 'b']) == ['0:a', '1:b']", "__FN__(['x'], 5) == ['5:x']", "__FN__([]) == []", "enumerate_call"),
    T("zip_equal", "길이 확인 zip", "(left: list[int], right: list[int]) -> list[tuple[int, int]] | None:", "두 리스트 길이가 다르면 None, 같으면 zip한 tuple 리스트를 반환하세요.", "zip 절단 방지", "__FN__([1, 2], [3, 4]) == [(1, 3), (2, 4)]", "__FN__([1], []) is None", "__FN__([], []) == []", "zip_call"),
    T("pathlib_summary", "pathlib 경로 분석", "(path_text: str) -> dict[str, str]:", "pathlib.Path로 path_text를 해석해 name, stem, suffix, parent 문자열을 딕셔너리로 반환하세요.", "Path의 경로 구성 요소", "__FN__('report/data.json') == {'name': 'data.json', 'stem': 'data', 'suffix': '.json', 'parent': 'report'}", "__FN__('archive.tar.gz') == {'name': 'archive.tar.gz', 'stem': 'archive.tar', 'suffix': '.gz', 'parent': '.'}", "__FN__('') == {'name': '', 'stem': '', 'suffix': '', 'parent': '.'}", "pathlib_call"),
    T("json_object_summary", "JSON 객체 파싱", "(text: str) -> dict[str, object]:", "json.loads로 JSON object를 파싱하고 정렬된 keys, key 개수, 원본 data를 딕셔너리로 반환하세요.", "JSON 역직렬화와 구조 확인", "__FN__('{\"b\": 2, \"a\": 1}') == {'keys': ['a', 'b'], 'count': 2, 'data': {'b': 2, 'a': 1}}", "__FN__('{}') == {'keys': [], 'count': 0, 'data': {}}", "__FN__('{\"x\": [1, 2]}') == {'keys': ['x'], 'count': 1, 'data': {'x': [1, 2]}}", "json_call"),
    T("csv_column_totals", "CSV 숫자 열 합계", "(text: str) -> dict[str, int]:", "csv.reader로 첫 행을 header로 읽고 이후 정수 행들의 열별 합계를 반환하세요. 빈 text는 빈 딕셔너리입니다.", "CSV parsing과 열 누적", "__FN__('apples,oranges\\n1,2\\n3,4') == {'apples': 4, 'oranges': 6}", "__FN__('') == {}", "__FN__('x,y\\n') == {'x': 0, 'y': 0}", "csv_call"),
    T("first_default", "첫 원소 기본값", "(values: object, default: object = None) -> object:", "iter와 next의 기본값 인자를 사용해 첫 원소 또는 default를 반환하세요.", "next(iterator, default)", "__FN__([3, 4], 0) == 3", "__FN__([], 0) == 0", "__FN__((x for x in ['a']), '') == 'a'", "iter_call", "next_call"),
    T("lru_climb_ways", "lru_cache 계단 경우의 수", "(steps: int) -> int:", "functools.lru_cache(maxsize=None)를 target 함수에 적용하고 1칸 또는 2칸씩 steps에 도달하는 경우의 수를 재귀로 반환하세요. steps=0은 1입니다.", "lru_cache decorator와 재귀 DP", "__FN__(0) == 1", "__FN__(1) == 1", "__FN__(5) == 8", "lru_cache_decorator", time_cap=300),
    T("flatten_records", "중첩 레코드 unpacking", "(records: list[tuple[str, tuple[int, int]]]) -> list[tuple[str, int, int]]:", "중첩 tuple을 loop target에서 unpack해 평평한 tuple로 반환하세요.", "중첩 unpacking", "__FN__([('a', (1, 2))]) == [('a', 1, 2)]", "__FN__([]) == []", "__FN__([('x', (0, -1)), ('y', (2, 3))]) == [('x', 0, -1), ('y', 2, 3)]", "for", "tuple_unpack"),
    T("positive_square_pipeline", "filter-map 파이프라인", "(values: list[int]) -> list[int]:", "양수만 고른 뒤 제곱하는 generator expression을 만들고 마지막에 리스트로 소비하세요.", "lazy filter-map 파이프라인", "__FN__([-1, 2, 3]) == [4, 9]", "__FN__([]) == []", "__FN__([0, 1]) == [1]", "comprehension"),
    T("take_islice", "lazy 앞부분 취하기", "(values: object, count: int) -> list[object]:", "itertools.islice로 iterable의 앞 count개만 소비해 리스트로 반환하세요.", "부분 소비와 무한 iterable 대응", "__FN__([1, 2, 3], 2) == [1, 2]", "__FN__([], 3) == []", "__FN__((x for x in range(5)), 0) == []", "itertools_call"),
    T("pairwise_differences", "연속 차이", "(values: list[int]) -> list[int]:", "itertools.pairwise로 뒤 값에서 앞 값을 뺀 연속 차이를 반환하세요.", "pairwise iterator", "__FN__([1, 4, 9]) == [3, 5]", "__FN__([]) == []", "__FN__([5]) == []", "itertools_call"),
    T("cartesian_labels", "곱집합 라벨", "(left: list[str], right: list[int]) -> list[str]:", "itertools.product 순서대로 '<문자>:<숫자>' 라벨을 반환하세요.", "Cartesian product", "__FN__(['a', 'b'], [1, 2]) == ['a:1', 'a:2', 'b:1', 'b:2']", "__FN__([], [1]) == []", "__FN__(['x'], []) == []", "itertools_call"),
    T("accumulated_totals", "누적 합", "(values: list[int]) -> list[int]:", "itertools.accumulate로 prefix sum 리스트를 반환하세요.", "lazy 누적 연산", "__FN__([1, 2, 3]) == [1, 3, 6]", "__FN__([]) == []", "__FN__([-1, 2]) == [-1, 1]", "itertools_call"),
    T("cached_fibonacci", "cache 재귀 피보나치", "(n: int) -> int:", "functools.cache 또는 lru_cache decorator를 붙인 재귀 함수로 n번째 피보나치 수를 반환하세요. F(0)=0, F(1)=1입니다.", "memoization decorator", "__FN__(0) == 0", "__FN__(1) == 1", "__FN__(10) == 55", "cache_decorator", time_cap=300),
    T("math_toolkit", "math 수치 도구", "(a: int, b: int, value: float) -> dict[str, object]:", "math의 gcd, lcm, isqrt, ceil, inf를 사용해 지정된 다섯 결과를 딕셔너리로 반환하세요. isqrt에는 abs(a)를 사용합니다.", "math 표준 라이브러리 조합", "__FN__(12, 18, 2.1) == {'gcd': 6, 'lcm': 36, 'isqrt': 3, 'ceil': 3, 'sentinel': float('inf')}", "__FN__(0, 5, -1.2) == {'gcd': 5, 'lcm': 0, 'isqrt': 0, 'ceil': -1, 'sentinel': float('inf')}", "__FN__(-9, 6, 3.0) == {'gcd': 3, 'lcm': 18, 'isqrt': 3, 'ceil': 3, 'sentinel': float('inf')}", "math_call", time_cap=270),
)


LISTS = (
    T("append_copy", "복사본에 순차 추가", "(start: list[int], additions: list[int]) -> list[int]:", "start를 보존하고 사본 끝에 additions를 append로 차례대로 추가하세요.", "copy와 append", "__FN__([1], [2, 3]) == [1, 2, 3]", "__FN__([], []) == []", "((data := [1]), __FN__(data, [2]), data) == ([1], [1, 2], [1])", "append_call"),
    T("insert_remove_negative", "삽입 후 음수 제거", "(values: list[int], index: int, new_value: int) -> list[int]:", "사본의 index에 new_value를 삽입한 뒤 처음 등장하는 음수 하나만 제거하세요.", "insert와 remove의 순서", "__FN__([1, -1, 3], 1, 2) == [1, 2, 3]", "__FN__([], 0, 5) == [5]", "__FN__([-1, -2], 0, 0) == [0, -2]"),
    T("concat_without_alias", "두 리스트 결합", "(left: list[int], right: list[int]) -> list[int]:", "두 원본과 별개의 새 리스트에 left와 right를 순서대로 결합하세요.", "리스트 연결과 alias 방지", "__FN__([1, 2], [3]) == [1, 2, 3]", "__FN__([], []) == []", "((a := [1]), (b := [2]), (r := __FN__(a, b)), r is not a and r is not b) == ([1], [2], [1, 2], True)"),
    T("independent_rows", "독립적인 빈 행 초기화", "(count: int) -> list[list[int]]:", "서로 같은 객체를 공유하지 않는 빈 리스트 count개를 만드세요.", "중첩 리스트 곱셈의 aliasing 회피", "((rows := __FN__(3)), rows == [[], [], []] and len({id(row) for row in rows}) == 3) == ([[], [], []], True)", "__FN__(0) == []", "((rows := __FN__(1)), rows == [[]]) == ([[]], True)", "comprehension"),
    T("clone_update", "사본 위치 갱신", "(values: list[int], index: int, value: int) -> tuple[list[int], list[int]]:", "shallow copy의 index를 바꾸고 (수정본, 원본 내용 복사본)을 반환하세요.", "copy 후 index 대입", "__FN__([1, 2], 0, 9) == ([9, 2], [1, 2])", "__FN__([0], -1, 1) == ([1], [0])", "((data := [1, 2]), __FN__(data, 1, 7), data) == ([1, 2], ([1, 7], [1, 2]), [1, 2])"),
    T("even_squares", "짝수 제곱 comprehension", "(values: list[int]) -> list[int]:", "list comprehension으로 짝수만 골라 제곱하세요.", "filter와 map comprehension", "__FN__([1, 2, 3, 4]) == [4, 16]", "__FN__([]) == []", "__FN__([-2, -1, 0]) == [4, 0]", "comprehension"),
    T("slice_window", "안전한 구간 슬라이스", "(values: list[int], start: int, stop: int, step: int = 1) -> list[int]:", "Python 슬라이스 규칙으로 start:stop:step의 새 리스트를 반환하세요. step은 0이 아닙니다.", "슬라이스 경계와 음수 인덱스", "__FN__([0, 1, 2, 3], 1, 4, 2) == [1, 3]", "__FN__([], 0, 3) == []", "__FN__([1, 2, 3], -2, 3) == [2, 3]", "slice"),
    T("rotate_right", "오른쪽 회전", "(values: list[int], steps: int) -> list[int]:", "원본을 보존하고 리스트를 steps만큼 오른쪽으로 회전하세요. 빈 리스트는 그대로 반환합니다.", "모듈러와 슬라이싱", "__FN__([1, 2, 3, 4], 1) == [4, 1, 2, 3]", "__FN__([], 5) == []", "__FN__([1, 2, 3], -1) == [2, 3, 1]", "slice"),
    T("two_sum_sorted", "정렬 리스트 두 수 합", "(values: list[int], target: int) -> tuple[int, int] | None:", "오름차순 values에서 두 포인터로 합이 target인 두 값의 인덱스를 반환하세요. 없으면 None입니다.", "양끝 포인터 이동", "__FN__([1, 2, 4, 6], 6) == (1, 2)", "__FN__([], 1) is None", "__FN__([1, 2, 3], 10) is None", "while"),
    T("stable_remove", "안정적인 값 삭제", "(values: list[int], target: int) -> list[int]:", "target과 같은 모든 값을 제거하되 나머지의 상대 순서를 유지하세요.", "안정적 필터", "__FN__([1, 2, 1, 3], 1) == [2, 3]", "__FN__([], 0) == []", "__FN__([1, 2], 9) == [1, 2]", "comprehension"),
    T("flatten_once", "한 단계 평탄화", "(groups: list[list[int]]) -> list[int]:", "각 내부 리스트를 입력 순서대로 한 단계만 펼치세요.", "중첩 loop와 append", "__FN__([[1, 2], [], [3]]) == [1, 2, 3]", "__FN__([]) == []", "__FN__([[-1]]) == [-1]", "nested_loop", "append_call"),
    T("chunk_by_size", "고정 크기 청크", "(values: list[int], size: int) -> list[list[int]]:", "양수 size 단위로 연속 청크를 만들고 마지막의 짧은 청크도 포함하세요.", "range step과 slicing", "__FN__([1, 2, 3, 4, 5], 2) == [[1, 2], [3, 4], [5]]", "__FN__([], 3) == []", "__FN__([1, 2], 5) == [[1, 2]]", "range", "slice"),
    T("prefix_sums", "Prefix Sum", "(values: list[int]) -> list[int]:", "첫 원소가 0이고 이후에 각 prefix 합이 오는 길이 n+1 리스트를 만드세요.", "누적합 전처리", "__FN__([2, -1, 3]) == [0, 2, 1, 4]", "__FN__([]) == [0]", "__FN__([0]) == [0, 0]", "for", "append_call"),
    T("difference_updates", "Difference Array 구간 갱신", "(length: int, updates: list[tuple[int, int, int]]) -> list[int]:", "0으로 시작한 length 배열에 각 (start, end, delta)를 양끝 포함 구간으로 더한 최종 배열을 반환하세요.", "차분 배열과 prefix 복원", "__FN__(5, [(1, 3, 2), (2, 4, 1)]) == [0, 2, 3, 3, 1]", "__FN__(0, []) == []", "__FN__(3, [(0, 2, -1)]) == [-1, -1, -1]", "for"),
    T("merge_intervals", "겹치는 구간 병합", "(intervals: list[tuple[int, int]]) -> list[tuple[int, int]]:", "닫힌 구간을 시작점 순으로 정렬한 뒤 겹치거나 맞닿는 구간을 병합하세요.", "정렬 후 선형 병합", "__FN__([(1, 3), (2, 5), (8, 9)]) == [(1, 5), (8, 9)]", "__FN__([]) == []", "__FN__([(1, 2), (2, 3)]) == [(1, 3)]", "sorted_call"),
    T("window_sums", "고정 창 합", "(values: list[int], size: int) -> list[int]:", "size 길이의 모든 연속 구간 합을 O(n)에 반환하세요. 유효한 창이 없으면 빈 리스트입니다.", "sliding window 갱신", "__FN__([1, 2, 3, 4], 2) == [3, 5, 7]", "__FN__([], 1) == []", "__FN__([1, 2], 3) == []", "for"),
    T("move_zeros", "0을 뒤로 이동", "(values: list[int]) -> list[int]:", "0이 아닌 값의 상대 순서를 유지하며 모든 0을 뒤로 보낸 새 리스트를 반환하세요.", "안정적 partition", "__FN__([0, 1, 0, 3, 2]) == [1, 3, 2, 0, 0]", "__FN__([]) == []", "__FN__([0, 0]) == [0, 0]"),
    T("product_except_self", "자기 자신 제외 곱", "(values: list[int]) -> list[int]:", "나눗셈 없이 각 위치에 자신을 제외한 모든 값의 곱을 반환하세요.", "왼쪽·오른쪽 누적 곱", "__FN__([1, 2, 3, 4]) == [24, 12, 8, 6]", "__FN__([2]) == [1]", "__FN__([0, 2, 3]) == [6, 0, 0]", "for"),
    T("interval_intersections", "두 구간 목록 교집합", "(left: list[tuple[int, int]], right: list[tuple[int, int]]) -> list[tuple[int, int]]:", "각 목록이 서로 겹치지 않는 정렬된 닫힌 구간일 때 두 포인터로 교집합을 반환하세요.", "구간 두 포인터", "__FN__([(0, 2), (5, 10)], [(1, 5), (8, 12)]) == [(1, 2), (5, 5), (8, 10)]", "__FN__([], [(1, 2)]) == []", "__FN__([(1, 2)], [(3, 4)]) == []", "while"),
)


STACKS_QUEUES = (
    T("safe_stack", "underflow 안전 stack", "(operations: list[tuple[str, int | None]]) -> list[int | None]:", "push와 pop을 처리하고 빈 stack의 pop은 None을 결과에 추가하세요.", "LIFO와 underflow 계약", "__FN__([('pop', None), ('push', 2), ('pop', None)]) == [None, 2]", "__FN__([]) == []", "__FN__([('push', 1), ('push', 2), ('pop', None)]) == [2]", "append_call", "pop_call"),
    T("stack_peek", "stack peek", "(operations: list[tuple[str, int | None]]) -> list[int | None]:", "push, pop, peek를 처리하고 peek는 제거 없이 최상단 값을, 빈 구조에서는 None을 기록하세요.", "제거 없는 top 조회", "__FN__([('push', 1), ('peek', None), ('pop', None), ('peek', None)]) == [1, 1, None]", "__FN__([]) == []", "__FN__([('peek', None)]) == [None]", "append_call", "pop_call"),
    T("bounded_stack", "용량 제한 stack", "(values: list[int], capacity: int) -> list[int]:", "값을 차례로 push하되 capacity를 넘으면 가장 아래의 오래된 값을 제거해 최종 stack을 반환하세요.", "bounded LIFO 저장소", "__FN__([1, 2, 3], 2) == [2, 3]", "__FN__([], 3) == []", "__FN__([1, 2], 0) == []"),
    T("valid_pop_order", "stack pop 순서 판정", "(pushed: list[int], popped: list[int]) -> bool:", "pushed 순서로 push할 때 popped가 가능한 pop 순서인지 판정하세요.", "stack 시뮬레이션", "__FN__([1, 2, 3], [2, 3, 1]) is True", "__FN__([1, 2, 3], [3, 1, 2]) is False", "__FN__([], []) is True", "append_call", "pop_call"),
    T("queue_two_stacks", "두 stack으로 queue", "(operations: list[tuple[str, int | None]]) -> list[int | None]:", "list stack 두 개로 enqueue/dequeue를 처리하고 빈 dequeue는 None을 기록하세요.", "두 stack의 amortized FIFO", "__FN__([('enqueue', 1), ('enqueue', 2), ('dequeue', None)]) == [1]", "__FN__([('dequeue', None)]) == [None]", "__FN__([]) == []"),
    T("undo_text", "문자열 Undo", "(operations: list[tuple[str, str]]) -> str:", "('add', text)는 끝에 추가하고 ('undo', '')는 마지막 add를 취소하는 편집 기록기를 구현하세요.", "stack 기반 명령 취소", "__FN__([('add', 'a'), ('add', 'b'), ('undo', '')]) == 'a'", "__FN__([]) == ''", "__FN__([('undo', ''), ('add', 'x')]) == 'x'", "append_call", "pop_call"),
    T("valid_brackets", "괄호 문자열 검사", "(text: str) -> bool:", "(), [], {} 세 종류 괄호가 올바르게 중첩되고 닫히는지 stack으로 판정하세요.", "괄호 매칭 stack", "__FN__('([]{})') is True", "__FN__('([)]') is False", "__FN__('') is True", "append_call", "pop_call"),
    T("evaluate_rpn", "후위 표기식 계산", "(tokens: list[str]) -> int:", "+, -, *, /를 지원하는 유효한 정수 RPN을 stack으로 계산하세요. 나누는 수는 0이 아닙니다. 나눗셈은 0 방향으로 버리고 큰 정수도 float 변환 없이 정확히 처리하세요.", "피연산자 stack과 정확한 정수 나눗셈", "__FN__(['2', '1', '+', '3', '*']) == 9", "__FN__(['-7', '3', '/']) == -2", "__FN__(['100000000000000000001', '3', '/']) == 33333333333333333333", "append_call", "pop_call"),
    T("next_greater", "다음 큰 값", "(values: list[int]) -> list[int]:", "각 위치 오른쪽에서 처음으로 더 큰 값을 단조 stack으로 찾고 없으면 -1을 반환하세요.", "monotonic stack", "__FN__([2, 1, 3]) == [3, 3, -1]", "__FN__([]) == []", "__FN__([3, 2, 1]) == [-1, -1, -1]", "append_call", "pop_call"),
    T("daily_temperatures", "더 따뜻한 날까지", "(temperatures: list[int]) -> list[int]:", "각 날보다 더 따뜻한 다음 날까지의 거리, 없으면 0을 단조 stack으로 반환하세요.", "인덱스 monotonic stack", "__FN__([73, 74, 75, 71, 69, 72, 76, 73]) == [1, 1, 4, 2, 1, 1, 0, 0]", "__FN__([]) == []", "__FN__([3, 2, 1]) == [0, 0, 0]", "append_call", "pop_call"),
    T("remove_adjacent_duplicates", "인접 중복 제거", "(text: str) -> str:", "같은 문자가 인접하면 쌍으로 제거하고 새 인접 쌍도 계속 제거하세요.", "문자 stack 축약", "__FN__('abbaca') == 'ca'", "__FN__('') == ''", "__FN__('aaaa') == ''", "append_call", "pop_call"),
    T("bfs_order", "deque BFS 순회", "(graph: dict[str, list[str]], start: str) -> list[str]:", "collections.deque로 start부터 BFS 방문 순서를 반환하고 이웃은 주어진 순서를 따르세요. 각 정점은 한 번만 방문하며 key가 없는 정점의 이웃은 빈 목록입니다.", "FIFO graph traversal과 순환·합류 처리", "__FN__({'a': ['b', 'c'], 'b': ['d'], 'c': [], 'd': []}, 'a') == ['a', 'b', 'c', 'd']", "__FN__({'a': ['b', 'c'], 'b': ['a', 'd'], 'c': ['d']}, 'a') == ['a', 'b', 'c', 'd']", "__FN__({}, 'x') == ['x']", "deque_call"),
    T("sliding_max", "단조 deque 창 최댓값", "(values: list[int], size: int) -> list[int]:", "단조 deque로 모든 size 길이 창의 최댓값을 O(n)에 반환하세요.", "monotonic deque", "__FN__([1, 3, -1, -3, 5, 3, 6, 7], 3) == [3, 3, 5, 5, 6, 7]", "__FN__([], 1) == []", "__FN__([2, 1], 1) == [2, 1]", "deque_call"),
    T("circular_buffer", "고정 길이 원형 버퍼", "(values: list[int], capacity: int) -> list[int]:", "deque(maxlen=capacity)에 값을 넣어 마지막 capacity개를 순서대로 반환하세요.", "deque maxlen", "__FN__([1, 2, 3, 4], 3) == [2, 3, 4]", "__FN__([], 2) == []", "__FN__([1, 2], 0) == []", "deque_call"),
    T("min_stack", "최솟값 stack", "(operations: list[tuple[str, int | None]]) -> list[int | None]:", "push, pop, min을 처리하며 min은 현재 최솟값, 빈 pop/min은 None을 기록하세요.", "보조 최소 stack", "__FN__([('push', 3), ('push', 1), ('min', None), ('pop', None), ('min', None)]) == [1, 1, 3]", "__FN__([('min', None)]) == [None]", "__FN__([]) == []"),
    T("asteroid_collision", "소행성 충돌", "(asteroids: list[int]) -> list[int]:", "양수는 오른쪽, 음수는 왼쪽으로 움직일 때 stack으로 모든 충돌 후 남은 값을 반환하세요.", "반복 충돌 stack", "__FN__([5, 10, -5]) == [5, 10]", "__FN__([8, -8]) == []", "__FN__([-2, -1, 1, 2]) == [-2, -1, 1, 2]", "append_call", "pop_call"),
    T("decode_string", "반복 문자열 해독", "(text: str) -> str:", "k[encoded] 중첩 형식의 문자열을 stack으로 해독하세요. k는 양의 정수입니다.", "중첩 상태 stack", "__FN__('3[a2[c]]') == 'accaccacc'", "__FN__('2[ab]') == 'abab'", "__FN__('x') == 'x'", "append_call", "pop_call"),
    T("largest_rectangle", "히스토그램 최대 직사각형", "(heights: list[int]) -> int:", "증가 단조 stack으로 히스토그램에서 만들 수 있는 최대 직사각형 넓이를 반환하세요.", "sentinel과 monotonic stack", "__FN__([2, 1, 5, 6, 2, 3]) == 10", "__FN__([]) == 0", "__FN__([2, 4]) == 4", "append_call", "pop_call", time_cap=300),
    T("shortest_subarray", "합이 K 이상인 최단 구간", "(values: list[int], target: int) -> int:", "prefix sum과 단조 deque로 합이 target 이상인 가장 짧은 비어 있지 않은 구간 길이를 반환하고 없으면 -1입니다.", "prefix monotonic deque", "__FN__([2, -1, 2], 3) == 3", "__FN__([1, 2], 4) == -1", "__FN__([5], 5) == 1", "deque_call", time_cap=300),
)


GRIDS = (
    T("matrix_shape", "행렬 shape", "(matrix: list[list[object]]) -> tuple[int, int]:", "직사각형 matrix의 (행 수, 열 수)를 반환하고 빈 행렬은 (0, 0)으로 처리하세요.", "2D 구조의 행·열 크기", "__FN__([[1, 2], [3, 4]]) == (2, 2)", "__FN__([]) == (0, 0)", "__FN__([[]]) == (1, 0)"),
    T("rectangular_check", "직사각형 판정", "(matrix: list[list[object]]) -> bool:", "모든 행 길이가 같으면 True를 반환하세요. 빈 행렬도 직사각형으로 봅니다.", "jagged row 검증", "__FN__([[1, 2], [3, 4]]) is True", "__FN__([[1], [2, 3]]) is False", "__FN__([]) is True"),
    T("update_cell_copy", "셀 변경 깊은 복사", "(matrix: list[list[int]], row: int, col: int, value: int) -> list[list[int]]:", "모든 행을 복사한 새 행렬의 지정 셀만 바꾸고 원본은 보존하세요.", "중첩 리스트 독립 복사", "__FN__([[1, 2], [3, 4]], 0, 1, 9) == [[1, 9], [3, 4]]", "__FN__([[1]], 0, 0, 0) == [[0]]", "((grid := [[1, 2]]), __FN__(grid, 0, 0, 7), grid) == ([[1, 2]], [[7, 2]], [[1, 2]])", "comprehension"),
    T("row_major", "행 우선 순회", "(matrix: list[list[int]]) -> list[int]:", "각 행의 왼쪽부터 오른쪽으로 읽는 row-major 순서를 반환하세요.", "중첩 loop 순서", "__FN__([[1, 2], [3, 4]]) == [1, 2, 3, 4]", "__FN__([]) == []", "__FN__([[], [1]]) == [1]", "nested_loop"),
    T("column_major", "열 우선 순회", "(matrix: list[list[int]]) -> list[int]:", "직사각형 matrix를 열별로 위에서 아래로 읽어 반환하세요.", "열 index 바깥 loop", "__FN__([[1, 2], [3, 4]]) == [1, 3, 2, 4]", "__FN__([]) == []", "__FN__([[1, 2, 3]]) == [1, 2, 3]", "nested_loop"),
    T("row_column_sums", "행·열 합", "(matrix: list[list[int]]) -> tuple[list[int], list[int]]:", "직사각형 matrix의 각 행 합과 각 열 합을 두 리스트로 반환하세요.", "2D 집계", "__FN__([[1, 2], [3, 4]]) == ([3, 7], [4, 6])", "__FN__([]) == ([], [])", "__FN__([[]]) == ([0], [])", "nested_loop"),
    T("transpose", "행렬 전치", "(matrix: list[list[int]]) -> list[list[int]]:", "직사각형 matrix의 행과 열을 바꾼 새 행렬을 반환하세요.", "index 전환과 nested comprehension", "__FN__([[1, 2, 3], [4, 5, 6]]) == [[1, 4], [2, 5], [3, 6]]", "__FN__([]) == []", "__FN__([[1]]) == [[1]]", "comprehension"),
    T("rotate_clockwise", "90도 시계 회전", "(matrix: list[list[int]]) -> list[list[int]]:", "직사각형 matrix를 시계 방향으로 90도 회전한 새 행렬을 반환하세요.", "전치와 행 방향 변환", "__FN__([[1, 2, 3], [4, 5, 6]]) == [[4, 1], [5, 2], [6, 3]]", "__FN__([]) == []", "__FN__([[1]]) == [[1]]"),
    T("diagonals", "두 대각선", "(matrix: list[list[int]]) -> tuple[list[int], list[int]]:", "정사각형 matrix의 주대각선과 부대각선을 각각 반환하세요.", "대각선 index 관계", "__FN__([[1, 2], [3, 4]]) == ([1, 4], [2, 3])", "__FN__([]) == ([], [])", "__FN__([[7]]) == ([7], [7])", "range"),
    T("boundary_clockwise", "테두리 시계 순회", "(matrix: list[list[int]]) -> list[int]:", "직사각형 matrix의 바깥 테두리를 좌상단에서 시작해 시계 방향으로 중복 없이 반환하세요.", "경계별 순회와 단일 행·열", "__FN__([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) == [1, 2, 3, 6, 9, 8, 7, 4]", "__FN__([[1, 2, 3]]) == [1, 2, 3]", "__FN__([]) == []"),
    T("orthogonal_neighbors", "상하좌우 이웃", "(grid: list[list[int]], row: int, col: int) -> list[int]:", "위, 아래, 왼쪽, 오른쪽 순서로 범위 안의 이웃 값만 반환하세요.", "4방향 경계 검사", "__FN__([[1, 2], [3, 4]], 0, 0) == [3, 2]", "__FN__([[1, 2], [3, 4]], 1, 1) == [2, 3]", "__FN__([[1]], 0, 0) == []"),
    T("eight_neighbors", "8방향 이웃", "(grid: list[list[int]], row: int, col: int) -> list[int]:", "대상 셀을 제외한 8방향 이웃을 행 우선 좌표 순서로 반환하세요.", "방향 delta 중첩 순회", "__FN__([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 1, 1) == [1, 2, 3, 4, 6, 7, 8, 9]", "__FN__([[1, 2], [3, 4]], 0, 0) == [2, 3, 4]", "__FN__([[1]], 0, 0) == []", "nested_loop"),
    T("spiral_order", "나선 순회", "(matrix: list[list[int]]) -> list[int]:", "직사각형 matrix를 바깥쪽부터 시계 방향 나선 순서로 반환하세요.", "네 경계 수축", "__FN__([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) == [1, 2, 3, 6, 9, 8, 7, 4, 5]", "__FN__([]) == []", "__FN__([[1, 2]]) == [1, 2]", "while"),
    T("flood_fill", "Flood Fill", "(grid: list[list[int]], row: int, col: int, color: int) -> list[list[int]]:", "원본을 보존하고 시작 셀과 4방향으로 연결된 같은 색 영역만 새 color로 바꾸세요.", "grid BFS/DFS", "__FN__([[1, 1, 0], [1, 0, 0]], 0, 0, 2) == [[2, 2, 0], [2, 0, 0]]", "__FN__([[1]], 0, 0, 1) == [[1]]", "__FN__([[0, 1]], 0, 1, 3) == [[0, 3]]"),
    T("prefix_matrix", "2D Prefix Sum", "(matrix: list[list[int]]) -> list[list[int]]:", "행과 열 앞에 0 padding을 둔 (rows+1)x(cols+1) 2D prefix sum을 반환하세요.", "포함-배제 전처리", "__FN__([[1, 2], [3, 4]]) == [[0, 0, 0], [0, 1, 3], [0, 4, 10]]", "__FN__([]) == [[0]]", "__FN__([[5]]) == [[0, 0], [0, 5]]", "nested_loop"),
    T("region_sums", "여러 직사각형 합", "(matrix: list[list[int]], queries: list[tuple[int, int, int, int]]) -> list[int]:", "각 (top,left,bottom,right) 양끝 포함 영역 합을 2D prefix sum으로 처리하세요.", "O(1) 영역 합 query", "__FN__([[1, 2], [3, 4]], [(0, 0, 1, 1), (0, 1, 1, 1)]) == [10, 6]", "__FN__([], []) == []", "__FN__([[5]], [(0, 0, 0, 0)]) == [5]", "nested_loop"),
    T("count_islands", "섬 개수", "(grid: list[list[int]]) -> int:", "1이 육지일 때 4방향으로 연결된 섬의 개수를 반환하세요.", "grid DFS/BFS와 방문 집합", "__FN__([[1, 1, 0], [0, 1, 0], [1, 0, 1]]) == 3", "__FN__([]) == 0", "__FN__([[0, 0]]) == 0"),
    T("shortest_grid_path", "격자 최단 거리", "(grid: list[list[int]]) -> int:", "0은 통과 가능, 1은 벽인 직사각형에서 좌상단부터 우하단까지 4방향 최소 이동 수를 BFS로 반환하고 불가능하면 -1입니다.", "deque 기반 최단 경로", "__FN__([[0, 0], [1, 0]]) == 2", "__FN__([[0, 1], [1, 0]]) == -1", "__FN__([[0]]) == 0", "deque_call"),
    T("min_path_sum", "최소 경로 합 memoization", "(grid: list[list[int]]) -> int:", "우측 또는 아래로만 이동해 좌상단에서 우하단까지의 최소 합을 구하고, 중첩 재귀 helper에 functools.cache를 사용하세요.", "top-down DP와 cache", "__FN__([[1, 3, 1], [1, 5, 1], [4, 2, 1]]) == 7", "__FN__([[5]]) == 5", "__FN__([]) == 0", "cache_decorator", time_cap=300),
)


HASHING = (
    T("last_value_by_key", "마지막 값 index", "(records: list[tuple[str, int]]) -> dict[str, int]:", "(key, value)를 순회해 key별 마지막 값을 저장하세요.", "dict 삽입·갱신", "__FN__([('a', 1), ('a', 2)]) == {'a': 2}", "__FN__([]) == {}", "__FN__([('x', -1), ('y', 0)]) == {'x': -1, 'y': 0}"),
    T("group_by_initial", "첫 글자 defaultdict 그룹", "(words: list[str]) -> dict[str, list[str]]:", "빈 문자열은 '' key로, 나머지는 첫 글자 key로 defaultdict(list)에 입력 순서대로 그룹화하세요.", "defaultdict grouping", "__FN__(['ant', 'apple', 'bee']) == {'a': ['ant', 'apple'], 'b': ['bee']}", "__FN__([]) == {}", "__FN__(['']) == {'': ['']}", "defaultdict_call"),
    T("most_common_tiebreak", "Counter 최빈값", "(values: list[str]) -> tuple[str, int] | None:", "Counter로 최빈값과 빈도를 반환하고 동률이면 문자열 사전순 최소를 선택하세요.", "Counter와 결정적 tie-break", "__FN__(['b', 'a', 'b']) == ('b', 2)", "__FN__(['b', 'a']) == ('a', 1)", "__FN__([]) is None", "counter_call"),
    T("has_duplicate", "중복 조기 탐지", "(values: list[int]) -> bool:", "set으로 첫 중복을 발견하는 즉시 True를 반환하고 끝까지 없으면 False를 반환하세요.", "seen set", "__FN__([1, 2, 1]) is True", "__FN__([1, 2, 3]) is False", "__FN__([]) is False"),
    T("coordinate_counts", "tuple 좌표 빈도", "(points: list[tuple[int, int]]) -> dict[tuple[int, int], int]:", "좌표 tuple을 dict key로 사용해 각 좌표의 빈도를 반환하세요.", "hashable composite key", "__FN__([(0, 0), (0, 0), (1, 2)]) == {(0, 0): 2, (1, 2): 1}", "__FN__([]) == {}", "__FN__([(-1, 2)]) == {(-1, 2): 1}"),
    T("normalize_keys", "문자열 key 정규화", "(records: list[tuple[str, int]]) -> dict[str, int]:", "key의 앞뒤 공백을 제거하고 소문자로 바꿔 값을 합산하세요.", "정규화된 hash key", "__FN__([(' A ', 1), ('a', 2)]) == {'a': 3}", "__FN__([]) == {}", "__FN__([('', 1), (' ', 2)]) == {'': 3}"),
    T("group_anagrams", "애너그램 그룹", "(words: list[str]) -> list[list[str]]:", "문자의 Counter 빈도를 hashable key로 사용해 애너그램을 입력 그룹 생성 순서와 그룹 내부 입력 순서대로 묶으세요.", "Counter signature grouping", "__FN__(['eat', 'tea', 'tan', 'ate']) == [['eat', 'tea', 'ate'], ['tan']]", "__FN__([]) == []", "__FN__(['', '']) == [['', '']]", "counter_call", "defaultdict_call"),
    T("two_sum_indices", "두 수 합 index", "(values: list[int], target: int) -> tuple[int, int] | None:", "한 번의 순회와 hashmap으로 합이 target인 0-based (i, j), i < j를 반환하세요. j가 가장 작은 쌍을 고르고 j가 같으면 i가 가장 작은 쌍을 선택합니다. 없으면 None입니다.", "complement lookup과 첫 index 보존", "__FN__([2, 7, 11, 15], 9) == (0, 1)", "(__FN__([3, 3], 6), __FN__([1, 1, 4], 5)) == ((0, 1), (0, 2))", "__FN__([1, 2], 9) is None"),
    T("multiset_intersection", "Counter 다중집합 교집합", "(left: list[int], right: list[int]) -> list[int]:", "Counter 교집합으로 공통 원소를 작은 값부터 중복 횟수만큼 반환하세요.", "Counter multiset 연산", "__FN__([1, 2, 2, 3], [2, 2, 4]) == [2, 2]", "__FN__([], [1]) == []", "__FN__([1, 1], [1]) == [1]", "counter_call", "sorted_call"),
    T("anagram_windows", "애너그램 시작 index", "(text: str, pattern: str) -> list[int]:", "고정 길이 sliding Counter로 text에서 pattern의 애너그램이 시작하는 모든 index를 반환하세요.", "증감 Counter window", "__FN__('cbaebabacd', 'abc') == [0, 6]", "__FN__('', 'a') == []", "__FN__('aaaa', 'aa') == [0, 1, 2]", "counter_call"),
    T("hash_join", "두 레코드 hash join", "(left: list[tuple[str, int]], right: list[tuple[str, str]]) -> list[tuple[str, int, str]]:", "right를 key로 index하되 중복 key는 마지막 값을 사용하세요. left 입력 순서와 중복 레코드를 유지하여 공통 key만 결합합니다.", "hash join과 중복 key 정책", "__FN__([('a', 1), ('b', 2)], [('b', 'B'), ('a', 'A')]) == [('a', 1, 'A'), ('b', 2, 'B')]", "__FN__([('a', 1), ('a', 2)], [('a', 'old'), ('a', 'new')]) == [('a', 1, 'new'), ('a', 2, 'new')]", "(__FN__([], [('a', 'A')]), __FN__([('x', 1)], [])) == ([], [])"),
    T("subarray_sum_count", "합이 K인 부분배열 수", "(values: list[int], target: int) -> int:", "prefix sum 빈도 hashmap으로 합이 target인 연속 부분배열 개수를 반환하세요.", "prefix frequency", "__FN__([1, 1, 1], 2) == 2", "__FN__([1, -1, 0], 0) == 3", "__FN__([], 0) == 0"),
    T("first_unique", "첫 비반복 값", "(values: list[str]) -> str | None:", "Counter를 만든 뒤 입력을 다시 순회해 빈도 1인 첫 문자열을 반환하세요.", "빈도 전처리와 안정적 선택", "__FN__(['a', 'b', 'a', 'c']) == 'b'", "__FN__([]) is None", "__FN__(['x', 'x']) is None", "counter_call"),
    T("longest_consecutive", "최장 연속 수열", "(values: list[int]) -> int:", "set을 사용해 정렬 없이 연속한 정수의 가장 긴 길이를 O(n)에 반환하세요.", "수열 시작점만 확장", "__FN__([100, 4, 200, 1, 3, 2]) == 4", "__FN__([]) == 0", "__FN__([1, 1, 2]) == 2"),
    T("regex_word_frequency", "정규표현식 단어 빈도", "(text: str) -> dict[str, int]:", "re로 영문자와 숫자로 이루어진 단어를 추출하고 소문자 Counter 빈도를 반환하세요.", "re tokenization과 Counter", "__FN__('Hi, hi! 42') == {'hi': 2, '42': 1}", "__FN__('') == {}", "__FN__('A_b') == {'a': 1, 'b': 1}", "re_call", "counter_call"),
    T("isomorphic_strings", "동형 문자열", "(left: str, right: str) -> bool:", "문자열 길이가 같고 각 위치의 문자 대응이 양방향 일대일이면 True를 반환하세요.", "bijection hash maps와 길이 검증", "__FN__('egg', 'add') is True", "(__FN__('foo', 'bar'), __FN__('ab', 'aa'), __FN__('ab', 'abc')) == (False, False, False)", "__FN__('', '') is True"),
    T("top_k_frequent", "상위 K개 빈도", "(values: list[int], k: int) -> list[int]:", "Counter 결과를 빈도 내림차순, 동률이면 값 오름차순으로 정렬해 앞 k개 고유 값을 반환하세요.", "Counter ranking", "__FN__([1, 1, 2, 2, 3], 2) == [1, 2]", "__FN__([], 3) == []", "__FN__([3, 2, 1], 2) == [1, 2]", "counter_call", "sorted_call"),
    T("equal_row_column_pairs", "같은 행·열 쌍", "(grid: list[list[int]]) -> int:", "각 행과 열을 tuple key로 세어 내용이 같은 행·열 쌍의 개수를 반환하세요.", "tuple key frequency", "__FN__([[3, 2, 1], [1, 7, 6], [2, 7, 7]]) == 1", "__FN__([[1]]) == 1", "__FN__([]) == 0", "counter_call"),
    T("word_break_cached", "문자열 분할 cache", "(text: str, words: list[str]) -> bool:", "중첩 재귀 helper와 functools.cache로 text를 사전 단어들의 연결로 만들 수 있는지 판정하세요. 단어는 반복 사용할 수 있고 빈 사전 단어는 무시합니다. 빈 text는 True입니다.", "hash set과 진행하는 memoized DFS", "__FN__('leetcode', ['leet', 'code']) is True", "__FN__('catsandog', ['cats', 'dog', 'sand', 'and', 'cat']) is False", "(__FN__('', ['a']), __FN__('aa', ['', 'a']), __FN__('b', [''])) == (True, True, False)", "cache_decorator", time_cap=300),
)


HEAPS = (
    T("running_minimum", "삽입별 최솟값", "(values: list[int]) -> list[int]:", "각 값을 heap에 push한 직후 현재 최솟값을 기록하세요.", "heappush와 root peek", "__FN__([3, 1, 2]) == [3, 1, 1]", "__FN__([]) == []", "__FN__([-1, -2]) == [-1, -2]", "heapq_call"),
    T("stable_priority", "안정적 우선순위 queue", "(tasks: list[tuple[int, str]]) -> list[str]:", "priority가 작을수록 먼저 처리하고 동률이면 입력 순서를 유지하도록 heap tuple에 sequence를 포함하세요.", "heap tie-break sequence", "__FN__([(1, 'b'), (1, 'a'), (0, 'x')]) == ['x', 'b', 'a']", "__FN__([]) == []", "__FN__([(2, 'a')]) == ['a']", "heapq_call"),
    T("max_heap_top_k", "음수 max-heap Top-K", "(values: list[int], k: int) -> list[int]:", "음수 변환 max heap으로 큰 값 k개를 내림차순 반환하세요.", "min heap을 max heap으로 표현", "__FN__([3, 1, 5, 2], 2) == [5, 3]", "__FN__([2, 2, 1], 5) == [2, 2, 1]", "__FN__([1], 0) == []", "heapq_call"),
    T("heapify_preserve", "원본 보존 heapify", "(values: list[int]) -> tuple[int | None, list[int]]:", "사본을 heapify하고 (최솟값 또는 None, 원본 내용 복사본)을 반환하며 입력은 수정하지 마세요.", "heapify와 copy", "__FN__([4, 2, 3]) == (2, [4, 2, 3])", "__FN__([]) == (None, [])", "((data := [2, 1]), __FN__(data), data) == ([2, 1], (1, [2, 1]), [2, 1])", "heapq_call"),
    T("heap_build_comparison", "heapify와 반복 push 비교", "(values: list[int]) -> tuple[list[int], list[int]]:", "사본을 heapify한 heap과 빈 heap에 하나씩 push한 heap에서 모두 pop하세요. (heapify 쪽 pop 결과, 반복 push 쪽 pop 결과)를 실제 두 리스트로 반환하고 원본은 보존하세요.", "두 heap 구성 방법의 관찰 가능한 결과", "__FN__([3, 1, 2]) == ([1, 2, 3], [1, 2, 3])", "__FN__([]) == ([], [])", "((data := [2, 2, -1]), __FN__(data), data) == ([2, 2, -1], ([-1, 2, 2], [-1, 2, 2]), [2, 2, -1])", "heapq_call"),
    T("peek_minimum", "heap peek", "(values: list[int]) -> int | None:", "사본을 heapify한 뒤 pop하지 않고 최솟값을 반환하고 빈 입력은 None으로 처리하세요.", "heap root 조회", "__FN__([4, 2, 3]) == 2", "__FN__([]) is None", "__FN__([-1]) == -1", "heapq_call"),
    T("kth_smallest_heap", "heap K번째 작은 값", "(values: list[int], k: int) -> int | None:", "heapify 후 k번 pop해 1-indexed k번째 작은 값을 반환하고 범위 밖이면 None을 반환하세요.", "반복 heappop", "__FN__([4, 1, 3, 2], 3) == 3", "__FN__([], 1) is None", "__FN__([1, 2], 0) is None", "heapq_call"),
    T("merge_k_lists", "K개 정렬 리스트 병합", "(lists: list[list[int]]) -> list[int]:", "각 리스트의 현재 원소와 위치를 heap에 저장해 K개 오름차순 리스트를 병합하세요.", "K-way merge heap", "__FN__([[1, 4], [1, 3, 5], [2, 6]]) == [1, 1, 2, 3, 4, 5, 6]", "__FN__([]) == []", "__FN__([[], [1]]) == [1]", "heapq_call"),
    T("task_schedule", "작업 스케줄러", "(tasks: list[tuple[int, int, str]]) -> list[str]:", "(0 이상 도착시각, 양수 처리시간, 고유 이름) 작업을 단일 CPU에서 비선점 실행하세요. CPU가 빌 때 도착한 작업 중 처리시간이 짧은 순서, 동률이면 이름순으로 고르고, 대기 작업이 없으면 다음 도착시각으로 이동합니다.", "event sorting과 available-task heap", "__FN__([(0, 3, 'a'), (1, 1, 'b'), (1, 1, 'c')]) == ['a', 'b', 'c']", "__FN__([]) == []", "__FN__([(0, 4, 'a'), (1, 3, 'b'), (1, 1, 'c'), (10, 1, 'd')]) == ['a', 'c', 'b', 'd']", "heapq_call", "sorted_call", time_cap=300),
    T("streaming_top_k", "prefix별 Top-K", "(values: list[int], k: int) -> list[list[int]]:", "값이 하나씩 도착할 때 크기 k min heap을 유지하고 각 prefix의 큰 값들을 내림차순으로 기록하세요.", "bounded streaming heap", "__FN__([3, 1, 5], 2) == [[3], [3, 1], [5, 3]]", "__FN__([], 2) == []", "__FN__([1, 2], 0) == [[], []]", "heapq_call"),
    T("balanced_halves", "두 heap 절반 분할", "(values: list[int]) -> tuple[list[int], list[int]]:", "max heap lower와 min heap upper를 유지해 lower 크기가 upper와 같거나 하나 크도록 한 뒤 두 절반을 오름차순 리스트로 반환하세요.", "two-heaps balancing", "__FN__([4, 1, 3, 2]) == ([1, 2], [3, 4])", "__FN__([3, 1, 2]) == ([1, 2], [3])", "__FN__([]) == ([], [])", "heapq_call"),
    T("running_medians", "실시간 중앙값", "(values: list[int]) -> list[float]:", "max heap과 min heap 두 개로 각 prefix의 중앙값을 반환하세요. 짝수 개면 두 중앙값 평균입니다.", "two-heaps median", "__FN__([2, 1, 5, 7, 2, 0, 5]) == [2.0, 1.5, 2.0, 3.5, 2.0, 2.0, 2.0]", "__FN__([]) == []", "__FN__([1, 3]) == [1.0, 2.0]", "heapq_call", time_cap=300),
    T("lazy_delete_min", "Lazy deletion 최소값", "(operations: list[tuple[str, int]]) -> list[int | None]:", "add, remove, min 명령을 heap과 삭제 예약 Counter로 처리하세요. remove는 현재 존재하는 값 한 개만 제거하고 없는 값은 무시합니다. min마다 유효한 최솟값 또는 None을 기록하며 min의 값 인자는 무시합니다.", "heap lazy deletion과 실제 빈도 관리", "__FN__([('add', 2), ('add', 1), ('remove', 1), ('min', 0)]) == [2]", "__FN__([('min', 0)]) == [None]", "__FN__([('remove', 1), ('add', 1), ('add', 1), ('remove', 1), ('min', 0), ('remove', 1), ('min', 0)]) == [1, None]", "heapq_call", "counter_call", time_cap=300),
    T("keep_largest_k", "가장 큰 K개 유지", "(values: list[int], k: int) -> list[int]:", "크기 k min heap만 유지해 전체 입력의 가장 큰 k개를 내림차순 반환하세요.", "O(n log k) bounded heap", "__FN__([5, 1, 4, 2, 3], 3) == [5, 4, 3]", "__FN__([], 2) == []", "__FN__([1, 2], 0) == []", "heapq_call"),
    T("k_closest_points", "원점에 가까운 K개 점", "(points: list[tuple[int, int]], k: int) -> list[tuple[int, int]]:", "거리 제곱, x, y 순서를 우선순위로 가장 가까운 점 k개를 반환하세요.", "tuple priority와 nsmallest", "__FN__([(1, 3), (-2, 2), (2, -2)], 2) == [(-2, 2), (2, -2)]", "__FN__([], 2) == []", "__FN__([(0, 0)], 0) == []", "heapq_call"),
    T("meeting_rooms", "필요 회의실 수", "(intervals: list[tuple[int, int]]) -> int:", "시작 시각 순으로 보며 종료 시각 min heap으로 동시에 필요한 최소 회의실 수를 반환하세요.", "interval scheduling heap", "__FN__([(0, 30), (5, 10), (15, 20)]) == 2", "__FN__([]) == 0", "__FN__([(1, 2), (2, 3)]) == 1", "heapq_call", "sorted_call"),
    T("reorganize_text", "인접 중복 없는 문자열", "(text: str) -> str:", "Counter와 max heap으로 같은 문자가 인접하지 않는 문자열을 만들고 불가능하면 ''를 반환하세요. 동률이면 문자순을 사용하세요.", "빈도 max heap과 이전 문자 보류", "__FN__('aab') == 'aba'", "__FN__('aaab') == ''", "__FN__('') == ''", "heapq_call", "counter_call", time_cap=300),
    T("kth_matrix", "정렬 행렬 K번째 값", "(matrix: list[list[int]], k: int) -> int | None:", "각 행이 오름차순인 matrix에서 행별 현재 원소 heap으로 1-indexed k번째 작은 값을 반환하세요.", "matrix K-way merge", "__FN__([[1, 5, 9], [10, 11, 13], [12, 13, 15]], 8) == 13", "__FN__([], 1) is None", "__FN__([[1]], 2) is None", "heapq_call"),
    T("smallest_covering_range", "K개 목록을 덮는 최소 구간", "(lists: list[list[int]]) -> tuple[int, int] | None:", "각 오름차순 목록에서 적어도 하나의 값을 포함하는 길이 최소 구간을 heap으로 찾고 동률이면 시작이 작은 구간을 반환하세요.", "K-way heap과 현재 최댓값", "__FN__([[4, 10, 15], [1, 12], [7, 8, 10]]) == (10, 12)", "__FN__([]) is None", "__FN__([[1], []]) is None", "heapq_call", time_cap=300),
)


SORTED_STRUCTURES = (
    T("bisect_positions", "bisect 좌우 위치", "(values: list[int], target: int) -> tuple[int, int]:", "오름차순 values에서 bisect_left와 bisect_right 위치를 반환하세요.", "lower/upper bound", "__FN__([1, 2, 2, 4], 2) == (1, 3)", "__FN__([], 3) == (0, 0)", "__FN__([1, 3], 2) == (1, 1)", "bisect_call"),
    T("ordered_insertions", "정렬 상태 삽입", "(start: list[int], additions: list[int]) -> list[int]:", "start가 오름차순일 때 bisect.insort로 additions를 순서대로 삽입한 새 리스트를 반환하세요.", "online sorted insertion", "__FN__([1, 4], [3, 2]) == [1, 2, 3, 4]", "__FN__([], []) == []", "__FN__([1, 1], [1]) == [1, 1, 1]", "bisect_call"),
    T("range_count", "정렬 범위 개수", "(values: list[int], low: int, high: int) -> int:", "오름차순 values에서 low 이상 high 이하 값의 개수를 두 bisect로 반환하세요.", "inclusive range query", "__FN__([1, 2, 2, 4, 5], 2, 4) == 3", "__FN__([], 0, 1) == 0", "__FN__([1, 3], 4, 2) == 0", "bisect_call"),
    T("neighbors", "전임자와 후임자", "(values: list[int], target: int) -> tuple[int | None, int | None]:", "오름차순 values에서 target보다 엄격히 작은 최댓값과 엄격히 큰 최솟값을 반환하세요.", "bisect predecessor/successor", "__FN__([1, 2, 2, 4], 2) == (1, 4)", "__FN__([], 2) == (None, None)", "__FN__([1, 3], 0) == (None, 1)", "bisect_call"),
    T("nearest_value", "가장 가까운 정렬 값", "(values: list[int], target: int) -> int | None:", "오름차순 values에서 target과 절댓값 차이가 가장 작은 값을 반환하고 동률이면 작은 값을 선택하세요. 빈 입력은 None입니다.", "삽입 위치 양옆 비교", "__FN__([1, 4, 8], 6) == 4", "__FN__([], 0) is None", "__FN__([1, 3], 2) == 1", "bisect_call"),
    T("batch_insert_positions", "연속 삽입 위치", "(start: list[int], additions: list[int]) -> tuple[list[int], list[int]]:", "각 addition을 bisect_left 위치에 삽입하면서 그 삽입 위치 목록과 최종 리스트를 반환하세요.", "동적 lower-bound insertion", "__FN__([1, 4], [3, 2]) == ([1, 1], [1, 2, 3, 4])", "__FN__([], []) == ([], [])", "__FN__([1, 1], [1]) == ([0], [1, 1, 1])", "bisect_call"),
    T("online_medians", "정렬 리스트 실시간 중앙값", "(values: list[int]) -> list[float]:", "각 값을 insort로 정렬 상태에 넣고 prefix별 중앙값을 반환하세요.", "bisect 기반 online median", "__FN__([2, 1, 5]) == [2.0, 1.5, 2.0]", "__FN__([]) == []", "__FN__([1, 3]) == [1.0, 2.0]", "bisect_call"),
    T("interval_lookup", "구간 포함 조회", "(intervals: list[tuple[int, int, str]], points: list[int]) -> list[str | None]:", "겹치지 않고 시작점순인 닫힌 구간에서 각 point가 속한 label을 bisect로 찾고 없으면 None을 반환하세요.", "시작점 index와 끝점 확인", "__FN__([(0, 2, 'a'), (5, 7, 'b')], [1, 4, 7]) == ['a', None, 'b']", "__FN__([], [1]) == [None]", "__FN__([(1, 1, 'x')], [1]) == ['x']", "bisect_call"),
    T("coordinate_compress", "좌표 압축", "(values: list[int]) -> list[int]:", "정렬된 고유 값에서 bisect_left로 각 원본 값의 0-based rank를 반환하세요.", "sorted unique와 rank lookup", "__FN__([50, 10, 50, 20]) == [2, 0, 2, 1]", "__FN__([]) == []", "__FN__([-1, -2]) == [1, 0]", "bisect_call", "sorted_call"),
    T("lis_length", "최장 증가 부분수열 길이", "(values: list[int]) -> int:", "tails 리스트와 bisect_left로 엄격히 증가하는 부분수열의 최대 길이를 O(n log n)에 반환하세요.", "patience sorting tails", "__FN__([10, 9, 2, 5, 3, 7, 101, 18]) == 4", "__FN__([]) == 0", "__FN__([2, 2, 2]) == 1", "bisect_call"),
    T("pair_sum_count", "목표 이하 쌍 개수", "(values: list[int], target: int) -> int:", "값을 정렬한 뒤 각 위치에서 bisect_right로 합이 target 이하인 서로 다른 index 쌍 i < j의 개수를 반환하세요.", "정렬과 upper bound counting", "__FN__([1, 2, 3, 4], 5) == 4", "__FN__([], 0) == 0", "(__FN__([2, 2, 2], 3), __FN__([2, 2, 2], 4)) == (0, 3)", "bisect_call", "sorted_call"),
    T("time_map", "시각별 이전 값 조회", "(records: list[tuple[str, int, str]], queries: list[tuple[str, int]]) -> list[str | None]:", "입력 순서와 무관하게 key별 기록을 timestamp로 정렬하고 query 시각 이하의 가장 최근 값을 bisect로 반환하세요. 같은 key와 timestamp는 입력의 마지막 값을 사용하며 이전 기록이 없으면 None입니다.", "per-key sorted history와 동일 시각 갱신", "__FN__([('a', 1, 'x'), ('a', 3, 'y')], [('a', 2), ('a', 3), ('b', 1)]) == ['x', 'y', None]", "__FN__([], []) == []", "__FN__([('a', 3, 'late'), ('a', 2, 'z'), ('a', 2, 'a')], [('a', 1), ('a', 2), ('a', 3)]) == [None, 'a', 'late']", "bisect_call"),
    T("calendar_insert", "겹치지 않는 일정 삽입", "(intervals: list[tuple[int, int]], new_interval: tuple[int, int]) -> list[tuple[int, int]] | None:", "시작점순 비겹침 반열린 구간에 bisect로 삽입 위치를 찾고 이웃과 겹치면 None을 반환하세요.", "ordered interval validation", "__FN__([(1, 3), (5, 7)], (3, 5)) == [(1, 3), (3, 5), (5, 7)]", "__FN__([(1, 4)], (3, 5)) is None", "__FN__([], (0, 1)) == [(0, 1)]", "bisect_call"),
    T("sorted_union", "두 정렬 집합 합집합", "(left: list[int], right: list[int]) -> list[int]:", "각 입력이 중복 없는 오름차순일 때 두 포인터로 정렬 합집합을 반환하세요.", "ordered set merge", "__FN__([1, 3], [2, 3]) == [1, 2, 3]", "__FN__([], [1]) == [1]", "__FN__([-1], []) == [-1]", "while"),
    T("sorted_multiset", "정렬 multiset 명령", "(operations: list[tuple[str, int]]) -> list[int]:", "add는 insort, remove는 존재할 때 한 개만 bisect로 제거하고 마지막 정렬 상태를 반환하세요.", "bisect 기반 multiset", "__FN__([('add', 2), ('add', 1), ('add', 2), ('remove', 2)]) == [1, 2]", "__FN__([('remove', 1)]) == []", "__FN__([]) == []", "bisect_call"),
    T("sliding_medians", "Sliding Window 중앙값", "(values: list[int], size: int) -> list[float]:", "정렬 리스트에 bisect 삽입·삭제를 적용해 모든 size 창의 중앙값을 반환하세요.", "ordered window maintenance", "__FN__([1, 3, -1, -3, 5, 3, 6, 7], 3) == [1.0, -1.0, -1.0, 3.0, 5.0, 6.0]", "__FN__([], 1) == []", "__FN__([1, 2], 2) == [1.5]", "bisect_call", time_cap=300),
    T("count_smaller_right", "오른쪽 작은 값 개수", "(values: list[int]) -> list[int]:", "오른쪽부터 정렬 리스트를 유지하며 각 위치 오른쪽의 더 작은 값 개수를 bisect_left로 반환하세요.", "reverse online rank", "__FN__([5, 2, 6, 1]) == [2, 1, 1, 0]", "__FN__([]) == []", "__FN__([2, 2]) == [0, 0]", "bisect_call"),
    T("reverse_pairs", "중요 역순 쌍", "(values: list[int]) -> int:", "i < j이고 values[i] > 2*values[j]인 쌍의 수를 정렬된 오른쪽 값과 bisect로 세세요.", "ordered threshold counting", "__FN__([1, 3, 2, 3, 1]) == 2", "__FN__([]) == 0", "__FN__([2, 4, 3, 5, 1]) == 3", "bisect_call", time_cap=300),
    T("floor_ceil_queries", "floor·ceil 다중 조회", "(values: list[int], queries: list[int]) -> list[tuple[int | None, int | None]]:", "오름차순 values에서 각 query 이하 최댓값 floor와 이상 최솟값 ceil을 bisect로 반환하세요.", "lower bound 양옆 query", "__FN__([1, 3, 5], [0, 3, 4, 6]) == [(None, 1), (3, 3), (3, 5), (5, None)]", "__FN__([], [1]) == [(None, None)]", "__FN__([2], []) == []", "bisect_call"),
)


TEMPLATES: dict[str, tuple[ChallengeTemplate, ...]] = {
    "Sorting": SORTING,
    "Pythonic Code": PYTHONIC,
    "Lists": LISTS,
    "Stacks and Queues": STACKS_QUEUES,
    "2-D Lists": GRIDS,
    "Hashmaps and Hashsets": HASHING,
    "Heaps / Priority Queues": HEAPS,
    "Sorted Dicts and Sorted Sets": SORTED_STRUCTURES,
}


BASELINE_SOURCE_CHECKS: dict[str, tuple[str, ...]] = {
    "sort_ascending": ("sorted_call",),
    "sort_descending": ("sorted_call",),
    "sort_custom": ("sorted_call",),
    "sort_lambda": ("sorted_call", "lambda"),
    "sorted_copy": ("sorted_call",),
    "unpacking": ("tuple_unpack",),
    "loop_unpacking": ("for", "tuple_unpack"),
    "enumerate": ("enumerate_call",),
    "zip": ("zip_call",),
    "list_comprehension": ("comprehension",),
    "queue_enqueue_dequeue": ("deque_call",),
    "double_ended_queue": ("deque_call",),
    "nested_list_comprehension": ("comprehension",),
    "default_dict": ("defaultdict_call",),
    "counter": ("counter_call",),
    "dict_comprehension": ("comprehension",),
    "dict_items": ("dict_items_call",),
    "set_comprehension": ("comprehension",),
    "heap_push": ("heapq_call",),
    "heap_pop": ("heapq_call",),
    "heapify": ("heapq_call",),
    "max_heap": ("heapq_call",),
    "custom_heap": ("heapq_call",),
    "heap_nsmallest": ("heapq_call",),
    "heap_nlargest": ("heapq_call",),
    "sorted_dict_basics": ("sorted_call",),
    "sorted_set_basics": ("sorted_call",),
}


for _chapter, _templates in TEMPLATES.items():
    if len(_templates) != 19:
        raise RuntimeError(f"{_chapter}: expected 19 templates, found {len(_templates)}")
